lsst.meas.algorithms: lsst::meas::algorithms::ShapeletInterpolation Class Reference
lsst::meas::algorithms::ShapeletInterpolation Class Reference
#include <ShapeletInterpolation.h>
Public Types
typedef boost::shared_ptr
< ShapeletInterpolation > Ptr
This class is an interpolator to get a Shapelet at an arbitrary position.
typedef boost::shared_ptr
< const ShapeletInterpolation > ConstPtr
typedef float PixelT
typedef lsst::pex::policy::Policy Policy
typedef
lsst::afw::math::SpatialCellSet SpatialCellSet
typedef
lsst::afw::image::Exposure
< PixelT > Exposure
typedef lsst::afw::geom::PointD PointD
typedef
lsst::meas::algorithms::Shapelet Shapelet
Public Member Functions
ShapeletInterpolation (const Policy &policy)
Basic constructor just loads parameters from a policy file.
~ShapeletInterpolation ()
Destructor needs to delete pImpl.
ShapeletInterpolation (const ShapeletInterpolation &rhs)
Copy constructor does a shallow copy.
ShapeletInterpolation & operator= (const ShapeletInterpolation &rhs)
op= does a shallow copy
int getOrder () const
get the order of the shapelet
int getFitOrder () const
get the order of the fit
double getSigma () const
get the scale size of the shapelet
int getSize () const
the size of the shapelet vector
int getFitSize () const
the number of fit coefficients
void setSigma (double sigma)
set a new value of sigma
void calculate (SpatialCellSet::Ptr cellSet, const Exposure &exposure)
Calculate the interpolation parameters from a SpatialCellSet.
Shapelet::ConstPtr interpolate (const PointD &pos) const
Perform the interpolation.
Shapelet::ConstPtr interpolate (double x, double y) const
double interpolateSingleElement (const PointD &pos, int i) const
Perform the interpolation for only one shapelet coefficient.
double interpolateSingleElement (double x, double y, int i) const
Member Typedef Documentation
typedef boost::shared_ptr<const ShapeletInterpolation> lsst::meas::algorithms::ShapeletInterpolation::ConstPtr
typedef lsst::afw::image::Exposure<PixelT> lsst::meas::algorithms::ShapeletInterpolation::Exposure
typedef float lsst::meas::algorithms::ShapeletInterpolation::PixelT
typedef lsst::afw::geom::PointD lsst::meas::algorithms::ShapeletInterpolation::PointD
typedef lsst::pex::policy::Policy lsst::meas::algorithms::ShapeletInterpolation::Policy
typedef boost::shared_ptr<ShapeletInterpolation> lsst::meas::algorithms::ShapeletInterpolation::Ptr
This class is an interpolator to get a Shapelet at an arbitrary position.
In addition to providing an interface to an interpolation function for Shapelets, it also measures the interpolating function.
Thus, the constructor actually just loads some parameters from a Policy file that are needed for the measurement and interpolation.
The measurement and interpolation is then done with the calculate() function.
In practice, the ShapeletInterpolation object is made by ShapeletPsf, and is used by it to implement the interpolation. I don't think there is any reason to make this object separately from a ShapeletPsf.
typedef lsst::meas::algorithms::Shapelet lsst::meas::algorithms::ShapeletInterpolation::Shapelet
typedef lsst::afw::math::SpatialCellSet lsst::meas::algorithms::ShapeletInterpolation::SpatialCellSet
Constructor & Destructor Documentation
lsst::meas::algorithms::ShapeletInterpolation::ShapeletInterpolation (const Policy & policy)
Basic constructor just loads parameters from a policy file.
Parameters
[in] policy,: see policy/ShapeletPsfDeterminerDictionary.paf; sizeCellX/Y are ignored;
lsst::meas::algorithms::ShapeletInterpolation::~ShapeletInterpolation ()
Destructor needs to delete pImpl.
lsst::meas::algorithms::ShapeletInterpolation::ShapeletInterpolation (const ShapeletInterpolation & rhs)
Copy constructor does a shallow copy.
Member Function Documentation
void lsst::meas::algorithms::ShapeletInterpolation::calculate (SpatialCellSet::Ptr cellSet, const Exposure & exposure)
Calculate the interpolation parameters from a SpatialCellSet.
The candidates must be ShapeletPsfCandidate's.
Parameters
cellSet the set of candidates
exposure the exposure on which to measure the PSF
References lsst::meas::algorithms::ShapeletInterpolationImpl::calculate().
int lsst::meas::algorithms::ShapeletInterpolation::getFitOrder () const
get the order of the fit
References lsst::meas::algorithms::ShapeletInterpolationImpl::getFitOrder().
int lsst::meas::algorithms::ShapeletInterpolation::getFitSize () const
the number of fit coefficients
References lsst::meas::algorithms::ShapeletInterpolationImpl::getFitSize().
int lsst::meas::algorithms::ShapeletInterpolation::getOrder () const
get the order of the shapelet
References lsst::meas::algorithms::ShapeletInterpolationImpl::getOrder().
double lsst::meas::algorithms::ShapeletInterpolation::getSigma () const
get the scale size of the shapelet
References lsst::meas::algorithms::ShapeletInterpolationImpl::getSigma().
int lsst::meas::algorithms::ShapeletInterpolation::getSize () const
the size of the shapelet vector
References lsst::meas::algorithms::ShapeletInterpolationImpl::getSize().
Shapelet::ConstPtr lsst::meas::algorithms::ShapeletInterpolation::interpolate (const PointD & pos) const
Perform the interpolation.
Shapelet::ConstPtr lsst::meas::algorithms::ShapeletInterpolation::interpolate (double x, double y) const
References lsst::meas::algorithms::ShapeletInterpolationImpl::interpolate().
double lsst::meas::algorithms::ShapeletInterpolation::interpolateSingleElement (const PointD & pos, int i) const
Perform the interpolation for only one shapelet coefficient.
double lsst::meas::algorithms::ShapeletInterpolation::interpolateSingleElement (double x, double y, int i) const
References lsst::meas::algorithms::ShapeletInterpolationImpl::interpolateSingleElement().
ShapeletInterpolation & lsst::meas::algorithms::ShapeletInterpolation::operator= (const ShapeletInterpolation & rhs)
op= does a shallow copy
void lsst::meas::algorithms::ShapeletInterpolation::setSigma (double sigma)
set a new value of sigma
References lsst::meas::algorithms::ShapeletInterpolationImpl::setSigma().
The documentation for this class was generated from the following files:
include/lsst/meas/algorithms/ShapeletInterpolation.h
src/ShapeletInterpolation.cc