lsst.meas.algorithms: lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo Class Reference
lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo Class Reference
#include <SizeMagnitudeStarSelectorAlgo.h>
Public Member Functions
SizeMagnitudeStarSelectorAlgo (const ConfigFile &params, std::string keyPrefix)
std::vector< PotentialStar * > findStars (std::vector< PotentialStar * > &allObj)
void findMinMax (const std::vector< PotentialStar * > &list, double *min, double *max, const Function2D &f)
void rejectOutliers (std::vector< PotentialStar * > &list, double nSigma, double minSigma, const Function2D &f)
std::vector< PotentialStar * > getPeakList (const std::vector< PotentialStar * > &objList, double binSize, double minSize, double maxSize, int nStart, int minIter, double magStep, double maxSignifRatio, bool isFirstPass, const Function2D &f)
void fitStellarSizes (Function2D *f, int order, double sigClip, const std::vector< PotentialStar * > &starList, double *outSigma)
void roughlyFitBrightStars (const std::vector< PotentialStar * > &objList, Function2D *f, double *outSigma)
void setParams (const ConfigFile &params, std::string keyPrefix, bool mustExist=false)
bool isOkSize (const double size)
bool isOkMag (const double mag)
bool isOkOutputMag (const double mag)
double convertToLogSize (const double size)
double getMinSize () const
double getMaxSize () const
double getMinMag () const
double getMaxMag () const
Constructor & Destructor Documentation
lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::SizeMagnitudeStarSelectorAlgo (const ConfigFile & params, std::string keyPrefix)
References findstars_params_default, findstars_params_default_len, lsst::meas::algorithms::shapelet::ConfigFile::read(), lsst::meas::algorithms::shapelet::ConfigFile::setComment(), lsst::meas::algorithms::shapelet::ConfigFile::setDelimiter(), and setParams().
Member Function Documentation
double lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::convertToLogSize (const double size) inline
void lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::findMinMax (const std::vector< PotentialStar * > & list, double * min, double * max, const Function2D & f)
References k.
Referenced by findStars().
std::vector< PotentialStar * > lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::findStars (std::vector< PotentialStar * > & allObj)
References dbg, lsst::meas::algorithms::shapelet::Bounds::divide(), findMinMax(), fitStellarSizes(), getPeakList(), lsst::meas::algorithms::shapelet::PotentialStar::isBrighterThan(), k, rejectOutliers(), roughlyFitBrightStars(), and xdbg.
void lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::fitStellarSizes (Function2D * f, int order, double sigClip, const std::vector< PotentialStar * > & starList, double * outSigma)
References lsst::meas::algorithms::shapelet::PotentialStar::getPos(), lsst::meas::algorithms::shapelet::PotentialStar::getSize(), lsst::meas::algorithms::shapelet::Function2D::outlierFit(), and xdbg.
Referenced by findStars(), and roughlyFitBrightStars().
double lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::getMaxMag () const inline
double lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::getMaxSize () const inline
double lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::getMinMag () const inline
double lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::getMinSize () const inline
std::vector< PotentialStar * > lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::getPeakList (const std::vector< PotentialStar * > & objList, double binSize, double minSize, double maxSize, int nStart, int minIter, double magStep, double maxSignifRatio, bool isFirstPass, const Function2D & f)
References lsst::meas::algorithms::shapelet::Histogram< T >::add(), Assert, dbg, dbgout, lsst::meas::algorithms::shapelet::Histogram< T >::findFirstPeakAfter(), lsst::meas::algorithms::shapelet::Histogram< T >::findFirstValleyAfter(), k, lsst::meas::algorithms::shapelet::Histogram< T >::print(), xdbg, and XDEBUG.
Referenced by findStars().
bool lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::isOkMag (const double mag) inline
bool lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::isOkOutputMag (const double mag) inline
bool lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::isOkSize (const double size) inline
void lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::rejectOutliers (std::vector< PotentialStar * > & list, double nSigma, double minSigma, const Function2D & f)
References lsst::meas::algorithms::shapelet::PotentialStar::getSize(), lsst::meas::algorithms::shapelet::PotentialStar::isSmallerThan(), k, and xdbg.
Referenced by findStars().
void lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::roughlyFitBrightStars (const std::vector< PotentialStar * > & objList, Function2D * f, double * outSigma)
References Assert, fitStellarSizes(), lsst::meas::algorithms::shapelet::PotentialStar::isSmallerThan(), k, and xdbg.
Referenced by findStars().
void lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::setParams (const ConfigFile & params, std::string keyPrefix, bool mustExist = false)
References SFKeyAssign.
Referenced by SizeMagnitudeStarSelectorAlgo().
The documentation for this class was generated from the following files:
include/lsst/meas/algorithms/shapelet/SizeMagnitudeStarSelectorAlgo.h
src/shapelet/SizeMagnitudeStarSelectorAlgo.cc