lsst.meas.algorithms: lsst::meas::algorithms::shapelet::Position Class Reference
lsst::meas::algorithms::shapelet::Position Class Reference
#include <Bounds.h>
Public Member Functions
Position ()
Position (const Position &rhs)
Position (const std::complex< double > &rhs)
~Position ()
Position (double x, double y)
Position & operator= (const Position &rhs)
Position & operator= (const std::complex< double > &rhs)
operator std::complex< double > ()
std::complex< double > operator- (const Position &p2) const
Position & operator*= (double x)
Position & operator/= (double x)
Position & operator+= (const std::complex< double > &z2)
Position operator+ (const std::complex< double > &z2) const
Position & operator-= (const std::complex< double > &z2)
Position operator- (const std::complex< double > &z2) const
double getX () const
double getY () const
void read (std::istream &fin)
void write (std::ostream &fout) const
Constructor & Destructor Documentation
lsst::meas::algorithms::shapelet::Position::Position () inline
Referenced by operator+(), and operator-().
lsst::meas::algorithms::shapelet::Position::Position (const Position & rhs) inline
lsst::meas::algorithms::shapelet::Position::Position (const std::complex< double > & rhs) inline
lsst::meas::algorithms::shapelet::Position::~Position () inline
lsst::meas::algorithms::shapelet::Position::Position (double x, double y) inline
Member Function Documentation
double lsst::meas::algorithms::shapelet::Position::getX () const inline
Referenced by lsst::meas::algorithms::shapelet::Bounds::includes(), lsst::meas::algorithms::shapelet::Function2D::operator()(), lsst::meas::algorithms::shapelet::Bounds::operator+=(), and write().
double lsst::meas::algorithms::shapelet::Position::getY () const inline
Referenced by lsst::meas::algorithms::shapelet::Bounds::includes(), lsst::meas::algorithms::shapelet::Function2D::operator()(), lsst::meas::algorithms::shapelet::Bounds::operator+=(), and write().
lsst::meas::algorithms::shapelet::Position::operator std::complex< double > () inline
Position& lsst::meas::algorithms::shapelet::Position::operator*= (double x) inline
Position lsst::meas::algorithms::shapelet::Position::operator+ (const std::complex< double > & z2) const inline
References Position().
Position& lsst::meas::algorithms::shapelet::Position::operator+= (const std::complex< double > & z2) inline
std::complex<double> lsst::meas::algorithms::shapelet::Position::operator- (const Position & p2) const inline
Position lsst::meas::algorithms::shapelet::Position::operator- (const std::complex< double > & z2) const inline
References Position().
Position& lsst::meas::algorithms::shapelet::Position::operator-= (const std::complex< double > & z2) inline
Position& lsst::meas::algorithms::shapelet::Position::operator/= (double x) inline
Position& lsst::meas::algorithms::shapelet::Position::operator= (const Position & rhs) inline
Position& lsst::meas::algorithms::shapelet::Position::operator= (const std::complex< double > & rhs) inline
void lsst::meas::algorithms::shapelet::Position::read (std::istream & fin)
Referenced by lsst::meas::algorithms::shapelet::operator>>().
void lsst::meas::algorithms::shapelet::Position::write (std::ostream & fout) const
References getX(), and getY().
Referenced by lsst::meas::algorithms::shapelet::operator<<().
The documentation for this class was generated from the following files:
include/lsst/meas/algorithms/shapelet/Bounds.h
src/shapelet/Bounds.cc