lsst.meas.algorithms: lsst::meas::algorithms::evalChi2Visitor< PixelT > Class Template Reference
lsst::meas::algorithms::evalChi2Visitor< PixelT > Class Template Reference
A class to pass around to all our PsfCandidates to evaluate the PSF fit's X^2.
Public Member Functions
evalChi2Visitor (afwMath::Kernel const &kernel, double lambda)
void reset ()
void processCandidate (afwMath::SpatialCellCandidate *candidate)
double getValue () const
Public Member Functions inherited from lsst::afw::math::CandidateVisitor
CandidateVisitor ()
virtual ~CandidateVisitor ()
Detailed Description
template<typename PixelT>
class lsst::meas::algorithms::evalChi2Visitor< PixelT >
A class to pass around to all our PsfCandidates to evaluate the PSF fit's X^2.
Constructor & Destructor Documentation
template<typename PixelT> lsst::meas::algorithms::evalChi2Visitor< PixelT >::evalChi2Visitor (afwMath::Kernel const & kernel, double lambda) inline explicit
Member Function Documentation
template<typename PixelT> double lsst::meas::algorithms::evalChi2Visitor< PixelT >::getValue () const inline
Referenced by lsst::meas::algorithms::fitSpatialKernelFromPsfCandidates().
template<typename PixelT> void lsst::meas::algorithms::evalChi2Visitor< PixelT >::processCandidate (afwMath::SpatialCellCandidate * candidate) inline virtual
Reimplemented from lsst::afw::math::CandidateVisitor.
References lsst::afw::math::SpatialCellCandidate::BAD, lsst::afw::math::Kernel::computeImage(), lsst::meas::algorithms::PsfCandidate< PixelT >::getOffsetImage(), lsst::meas::algorithms::PsfCandidate< PixelT >::getSource(), LSST_EXCEPT, lsst::meas::algorithms::PsfCandidate< PixelT >::setAmplitude(), lsst::afw::math::SpatialCellMaskedImageCandidate< PixelT >::setChi2(), and lsst::afw::math::SpatialCellMaskedImageCandidate< PixelT >::setStatus().
template<typename PixelT> void lsst::meas::algorithms::evalChi2Visitor< PixelT >::reset () inline virtual
Reimplemented from lsst::afw::math::CandidateVisitor.
The documentation for this class was generated from the following file:
src/SpatialModelPsf.cc