lsst.meas.algorithms: lsst::meas::algorithms::shapelet::PotentialStar Class Reference
lsst::meas::algorithms::shapelet::PotentialStar Class Reference
#include <PotentialStar.h>
Public Member Functions
PotentialStar (Position pos, double mag, double size, long index, const std::string &line)
~PotentialStar ()
const Position & getPos () const
double getMag () const
double getSize () const
long getIndex () const
const std::string & getLine () const
void setSize (double newsize)
bool isBrighterThan (const PotentialStar *rhs) const
bool isSmallerThan (const PotentialStar *rhs) const
Constructor & Destructor Documentation
lsst::meas::algorithms::shapelet::PotentialStar::PotentialStar (Position pos, double mag, double size, long index, const std::string & line) inline
lsst::meas::algorithms::shapelet::PotentialStar::~PotentialStar () inline
Member Function Documentation
long lsst::meas::algorithms::shapelet::PotentialStar::getIndex () const inline
const std::string& lsst::meas::algorithms::shapelet::PotentialStar::getLine () const inline
double lsst::meas::algorithms::shapelet::PotentialStar::getMag () const inline
const Position& lsst::meas::algorithms::shapelet::PotentialStar::getPos () const inline
Referenced by lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::fitStellarSizes().
double lsst::meas::algorithms::shapelet::PotentialStar::getSize () const inline
Referenced by lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::fitStellarSizes(), and lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::rejectOutliers().
bool lsst::meas::algorithms::shapelet::PotentialStar::isBrighterThan (const PotentialStar * rhs) const inline
Referenced by lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::findStars().
bool lsst::meas::algorithms::shapelet::PotentialStar::isSmallerThan (const PotentialStar * rhs) const inline
Referenced by lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::rejectOutliers(), and lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::roughlyFitBrightStars().
void lsst::meas::algorithms::shapelet::PotentialStar::setSize (double newsize) inline
The documentation for this class was generated from the following file:
include/lsst/meas/algorithms/shapelet/PotentialStar.h