lsst.meas.algorithms: lsst::meas::algorithms::PsfImagePca< ImageT > Class Template Reference
lsst::meas::algorithms::PsfImagePca< ImageT > Class Template Reference
#include <ImagePca.h>
Public Member Functions
PsfImagePca (bool constantWeight=true, int border=3)
Ctor.
virtual void analyze ()
Public Member Functions inherited from lsst::afw::image::ImagePca< ImageT >
ImagePca (bool constantWeight=true)
virtual ~ImagePca ()
void addImage (typename ImageT::Ptr img, double flux=0.0)
ImageList getImageList () const
geom::Extent2I const getDimensions () const
ImageT::Ptr getMean () const
virtual double updateBadPixels (unsigned long mask, int const ncomp)
std::vector< double > const & getEigenValues () const
ImageList const & getEigenImages () const
Additional Inherited Members
Public Types inherited from lsst::afw::image::ImagePca< ImageT >
typedef boost::shared_ptr< ImageT > Ptr
typedef boost::shared_ptr
< const ImageT > ConstPtr
typedef std::vector< typename
ImageT::Ptr > ImageList
Constructor & Destructor Documentation
template<typename ImageT> lsst::meas::algorithms::PsfImagePca< ImageT >::PsfImagePca (bool constantWeight = true, int border = 3) inline explicit
Ctor.
Member Function Documentation
template<typename ImageT > void lsst::meas::algorithms::PsfImagePca< ImageT >::analyze () virtual
Generate eigenimages that are normalised and background-subtracted
The background subtraction ensures PSF variation doesn't couple with small background errors.
Reimplemented from lsst::afw::image::ImagePca< ImageT >.
References lsst::afw::math::Statistics::getValue(), lsst::afw::math::makeStatistics(), lsst::afw::math::MAX, lsst::afw::math::MEDIAN, lsst::afw::math::MIN, and PTR.
Referenced by lsst::meas::algorithms::createKernelFromPsfCandidates().
The documentation for this class was generated from the following files:
include/lsst/meas/algorithms/ImagePca.h
src/ImagePca.cc