lsst.meas.algorithms: lsst::meas::algorithms::shapelet::Histogram< T > Class Template Reference
lsst::meas::algorithms::shapelet::Histogram< T > Class Template Reference
#include <Histogram.h>
Public Member Functions
Histogram (double binSize, double minValue, double maxValue)
~Histogram ()
void add (double value, const T &ref)
double findPeak (double minVal, double maxVal) const
bool hasSinglePeak (double minVal, double maxVal) const
double findValley (double minVal, double maxVal) const
double findFirstValueAfter (double start) const
double findFirstValleyAfter (double val1, bool hasPoissonNoise=false) const
double findFirstValleyBefore (double val1, bool hasPoissonNoise=false) const
double findFirstPeakAfter (double val1, bool hasPoissonNoise=false) const
double findFirstPeakBefore (double val1, bool hasPoissonNoise=false) const
int getTotalCountBefore (double val1) const
int getTotalCountAfter (double val1) const
int operator[] (double value) const
double findThresh (double minVal, double maxVal) const
std::vector< T > getRefsInRange (double min, double max) const
std::vector< double > getValuesInRange (double min, double max) const
int getRefinedPeakCount (double *peak) const
int getRefinedValleyCount (double *valley) const
void print (std::ostream &fout, double val1=-1.e10, double val2=1.e10) const
Constructor & Destructor Documentation
template<typename T > lsst::meas::algorithms::shapelet::Histogram< T >::Histogram (double binSize, double minValue, double maxValue)
References dbg.
template<typename T> lsst::meas::algorithms::shapelet::Histogram< T >::~Histogram () inline
Member Function Documentation
template<typename T > void lsst::meas::algorithms::shapelet::Histogram< T >::add (double value, const T & ref)
Referenced by lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::getPeakList().
template<typename T > double lsst::meas::algorithms::shapelet::Histogram< T >::findFirstPeakAfter (double val1, bool hasPoissonNoise = false) const
References Assert.
Referenced by lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::getPeakList().
template<typename T > double lsst::meas::algorithms::shapelet::Histogram< T >::findFirstPeakBefore (double val1, bool hasPoissonNoise = false) const
References Assert.
template<typename T > double lsst::meas::algorithms::shapelet::Histogram< T >::findFirstValleyAfter (double val1, bool hasPoissonNoise = false) const
References Assert, and dbg.
Referenced by lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::getPeakList().
template<typename T > double lsst::meas::algorithms::shapelet::Histogram< T >::findFirstValleyBefore (double val1, bool hasPoissonNoise = false) const
References Assert.
template<typename T > double lsst::meas::algorithms::shapelet::Histogram< T >::findFirstValueAfter (double start) const
template<typename T > double lsst::meas::algorithms::shapelet::Histogram< T >::findPeak (double minVal, double maxVal) const
References Assert.
template<typename T > double lsst::meas::algorithms::shapelet::Histogram< T >::findThresh (double minVal, double maxVal) const
References Assert, dbg, and dbgout.
template<typename T > double lsst::meas::algorithms::shapelet::Histogram< T >::findValley (double minVal, double maxVal) const
References Assert.
template<typename T > int lsst::meas::algorithms::shapelet::Histogram< T >::getRefinedPeakCount (double * peak) const
References Assert.
template<typename T > int lsst::meas::algorithms::shapelet::Histogram< T >::getRefinedValleyCount (double * valley) const
References Assert.
template<typename T > std::vector< T > lsst::meas::algorithms::shapelet::Histogram< T >::getRefsInRange (double min, double max) const
References dbg, and k.
template<typename T > int lsst::meas::algorithms::shapelet::Histogram< T >::getTotalCountAfter (double val1) const
References Assert.
template<typename T > int lsst::meas::algorithms::shapelet::Histogram< T >::getTotalCountBefore (double val1) const
References Assert.
template<typename T > std::vector< double > lsst::meas::algorithms::shapelet::Histogram< T >::getValuesInRange (double min, double max) const
References k.
template<typename T > bool lsst::meas::algorithms::shapelet::Histogram< T >::hasSinglePeak (double minVal, double maxVal) const
References Assert.
template<typename T > int lsst::meas::algorithms::shapelet::Histogram< T >::operator[] (double value) const
References Assert.
template<typename T > void lsst::meas::algorithms::shapelet::Histogram< T >::print (std::ostream & fout, double val1 = -1.e10, double val2 = 1.e10) const
References Assert, lsst::meas::algorithms::shapelet::Form::prec(), lsst::meas::algorithms::shapelet::Form::sci(), and lsst::meas::algorithms::shapelet::Form::width().
Referenced by lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::getPeakList().
The documentation for this class was generated from the following files:
include/lsst/meas/algorithms/shapelet/Histogram.h
src/shapelet/Histogram.cc