lsst.meas.algorithms: lsst::meas::algorithms::Algorithm Class Reference
lsst::meas::algorithms::Algorithm Class Reference abstract
Base class for source measurement algorithms.
#include <Algorithm.h>
Public Member Functions
Algorithm (AlgorithmControl const &ctrl)
virtual ~Algorithm ()
AlgorithmControl const & getControl () const
Return a clone of the control object used to construct the algorithm.
template<typename PixelT >
void apply (afw::table::SourceRecord &source, afw::image::Exposure< PixelT > const &exposure, afw::geom::Point2D const &center) const
Run the algorithm, filling appropriate fields in the given source.
Protected Member Functions
template<typename PixelT >
void _apply (afw::table::SourceRecord &source, afw::image::Exposure< PixelT > const &exposure, afw::geom::Point2D const &center) const
Simulated virtual function that all algorithms must implement.
Detailed Description
Base class for source measurement algorithms.
Algorithm simulates template virtual functions, with the following mechanism:
Users call the public, templated, non-virtual "apply" member function, which is defined only in the base class.
"apply" delegates to the overloaded, non-templated, virtual "_applyT" member functions.
"_applyT" delegates to the private, templated, non-virtual "_apply" member function, which must be defined by the derived class.
Algorithm subclasses will generally declare and define "_applyT" using the macro LSST_MEAS_ALGORITHM_PRIVATE_INTERFACE (in the private or protected section of the class declaration). Similarly, LSST_MEAS_ALGORITHM_PRIVATE_IMPLEMENTATION (at namespace scope in the same source file that contains the implementation of "_apply") will ensure that the needed versions of "_apply" are instantiated.
Algorithms should generally be immutable; this will prevent letting Python have access to CONST_PTR(Algorithm) objects from causing problems.
Most algorithms will have a constructor that takes a control object, a non-const reference to an afw::table::Schema, and a PTR(daf::base::PropertyList). This is effectively enforced by the signature of AlgorithmControl::makeAlgorithm.
Constructor & Destructor Documentation
lsst::meas::algorithms::Algorithm::Algorithm (AlgorithmControl const & ctrl) inline explicit
virtual lsst::meas::algorithms::Algorithm::~Algorithm () inline virtual
Member Function Documentation
template<typename PixelT > void lsst::meas::algorithms::Algorithm::_apply (afw::table::SourceRecord & source, afw::image::Exposure< PixelT > const & exposure, afw::geom::Point2D const & center) const inline protected
Simulated virtual function that all algorithms must implement.
template<typename PixelT > void lsst::meas::algorithms::Algorithm::apply (afw::table::SourceRecord & source, afw::image::Exposure< PixelT > const & exposure, afw::geom::Point2D const & center) const inline
Run the algorithm, filling appropriate fields in the given source.
This is the public interface to the algorithm; it delegates to virtual functions that are overloaded for all the allowed template types. These in turn delegate the templated _apply function.
AlgorithmControl const& lsst::meas::algorithms::Algorithm::getControl () const inline
Return a clone of the control object used to construct the algorithm.
The returned reference can be considered completely immutable, and should never be changed. Subclasses that reimplement to cast to a derived type should use returnCopy (in p_lsstSwig.i) to prevent dangling references and keep Python from const-casting the result.
Referenced by lsst::meas::algorithms::CentroidAlgorithm::getControl(), lsst::meas::algorithms::ShapeAlgorithm::getControl(), and lsst::meas::algorithms::FluxAlgorithm::getControl().
The documentation for this class was generated from the following file:
include/lsst/meas/algorithms/Algorithm.h