lsst.meas.algorithms: lsst::meas::algorithms::SizeMagnitudeStarSelector Class Reference
lsst::meas::algorithms::SizeMagnitudeStarSelector Class Reference
#include <SizeMagnitudeStarSelector.h>
Public Types
typedef float PixelT
typedef
lsst::afw::image::Exposure
< PixelT > Exposure
typedef lsst::afw::geom::PointD PointD
typedef lsst::pex::policy::Policy Policy
typedef
lsst::afw::table::SourceRecord SourceRecord
typedef
lsst::afw::table::SourceTable SourceTable
typedef
lsst::afw::table::SourceCatalog SourceCatalog
typedef
lsst::meas::algorithms::PsfCandidate
< PixelT > PsfCandidateT
typedef PsfCandidateT::PtrList PsfCandidateList
Public Member Functions
SizeMagnitudeStarSelector (const Policy &policy)
Create a size-magnitude star selector from a policy.
~SizeMagnitudeStarSelector ()
Destructor.
PsfCandidateList selectStars (const Exposure &exposure, const SourceCatalog &sourceList, boost::shared_ptr< afw::table::ReferenceMatchVector const > matches=boost::shared_ptr< afw::table::ReferenceMatchVector const >()) const
Find a set of stars from an input list of Sources.
Member Typedef Documentation
typedef lsst::afw::image::Exposure<PixelT> lsst::meas::algorithms::SizeMagnitudeStarSelector::Exposure
typedef float lsst::meas::algorithms::SizeMagnitudeStarSelector::PixelT
typedef lsst::afw::geom::PointD lsst::meas::algorithms::SizeMagnitudeStarSelector::PointD
typedef lsst::pex::policy::Policy lsst::meas::algorithms::SizeMagnitudeStarSelector::Policy
typedef PsfCandidateT::PtrList lsst::meas::algorithms::SizeMagnitudeStarSelector::PsfCandidateList
typedef lsst::meas::algorithms::PsfCandidate<PixelT> lsst::meas::algorithms::SizeMagnitudeStarSelector::PsfCandidateT
typedef lsst::afw::table::SourceCatalog lsst::meas::algorithms::SizeMagnitudeStarSelector::SourceCatalog
typedef lsst::afw::table::SourceRecord lsst::meas::algorithms::SizeMagnitudeStarSelector::SourceRecord
typedef lsst::afw::table::SourceTable lsst::meas::algorithms::SizeMagnitudeStarSelector::SourceTable
Constructor & Destructor Documentation
lsst::meas::algorithms::SizeMagnitudeStarSelector::SizeMagnitudeStarSelector (const Policy & policy)
Create a size-magnitude star selector from a policy.
Parameters
[in] policy,: see policy/SizeMagnitudeStarSelectorDictionary.paf
References lsst::pex::policy::Policy::getBool(), lsst::pex::policy::Policy::getDouble(), and lsst::pex::policy::Policy::getInt().
lsst::meas::algorithms::SizeMagnitudeStarSelector::~SizeMagnitudeStarSelector () inline
Destructor.
Member Function Documentation
SizeMagnitudeStarSelector::PsfCandidateList lsst::meas::algorithms::SizeMagnitudeStarSelector::selectStars (const Exposure & exposure, const SourceCatalog & sourceList, boost::shared_ptr< afw::table::ReferenceMatchVector const > matches = boost::shared_ptr< afw::table::ReferenceMatchVector const>()) const
Find a set of stars from an input list of Sources.
This function uses an algorithm based on looking for a stellar locus in the size-magnitude diagram that has constant size.
It basically construct a histogram of counts with respect to size, starting with just the bright objects and then pushing down in magnitude until the stellar peak starts to bleed into the galaxies, at which point it stops.
Parameters
exposure the exposure on which the sources are found
sourceList The input list of sources to consider
matches astrometric matches (ignored by this algorithm)
References CONST_PTR, lsst::pex::logging::Debug::debug(), lsst::afw::table::SortedCatalogT< RecordT >::get(), lsst::pex::logging::Log::getDefaultLog(), k, lsst::pex::logging::Log::log(), PTR, lsst::afw::table::SortedCatalogT< RecordT >::size(), and lsst::pex::logging::Log::WARN.
The documentation for this class was generated from the following files:
include/lsst/meas/algorithms/SizeMagnitudeStarSelector.h
src/SizeMagnitudeStarSelector.cc