lsst.meas.algorithms: lsst::meas::algorithms::shapelet::ConfigFile Class Reference
lsst::meas::algorithms::shapelet::ConfigFile Class Reference
#include <ConfigFile.h>
Public Member Functions
ConfigFile ()
ConfigFile (const std::string fileName, const std::string delimiter="=", const std::string comment="#", const std::string include="+", const std::string sentry="EndConfigFile")
void load (const std::string fileName)
void load (const std::string fileName, const std::string delimiter, const std::string comment="", const std::string include="", const std::string sentry="")
void read (std::istream &is)
void append (const std::string &s)
void write (std::ostream &os) const
void writeAsComment (std::ostream &os) const
ConvertibleString & getNoCheck (const std::string &key)
ConvertibleString get (const std::string &key) const
ConvertibleString & operator[] (const std::string &key)
ConvertibleString operator[] (const std::string &key) const
template<typename T >
T read (const std::string &key) const
template<typename T >
T read (const std::string &key, const T &value) const
template<typename T >
bool readInto (T &var, const std::string &key) const
template<typename T >
bool readInto (T &var, const std::string &key, const T &value) const
std::string getstr (const std::string key) const throw (const char*)
std::string getstr (const std::string key, const std::string defval)
template<typename T >
void add (std::string key, const T &value)
void remove (const std::string &key)
bool keyExists (const std::string &key) const
std::string getDelimiter () const
std::string getComment () const
std::string getInclude () const
std::string getSentry () const
std::string setDelimiter (const std::string &s)
std::string setComment (const std::string &s)
std::string setInclude (const std::string &s)
std::string setSentry (const std::string &s)
size_t size ()
Protected Types
typedef std::map< std::string,
ConvertibleString >::iterator MapIt
typedef std::map< std::string,
ConvertibleString >
::const_iterator MapCIt
Static Protected Member Functions
static void trim (std::string &s)
Protected Attributes
std::string _delimiter
std::string _comment
std::string _include
std::string _sentry
std::map< std::string,
ConvertibleString > _contents
Member Typedef Documentation
typedef std::map<std::string,ConvertibleString>::const_iterator lsst::meas::algorithms::shapelet::ConfigFile::MapCIt protected
typedef std::map<std::string,ConvertibleString>::iterator lsst::meas::algorithms::shapelet::ConfigFile::MapIt protected
Constructor & Destructor Documentation
lsst::meas::algorithms::shapelet::ConfigFile::ConfigFile ()
lsst::meas::algorithms::shapelet::ConfigFile::ConfigFile (const std::string fileName, const std::string delimiter = "=", const std::string comment = "#", const std::string include = "+", const std::string sentry = "EndConfigFile")
Member Function Documentation
template<typename T > void lsst::meas::algorithms::shapelet::ConfigFile::add (std::string key, const T & value) inline
References _contents, and trim().
void lsst::meas::algorithms::shapelet::ConfigFile::append (const std::string & s) inline
References read().
ConvertibleString lsst::meas::algorithms::shapelet::ConfigFile::get (const std::string & key) const
References _contents, and trim().
std::string lsst::meas::algorithms::shapelet::ConfigFile::getComment () const inline
References _comment.
std::string lsst::meas::algorithms::shapelet::ConfigFile::getDelimiter () const inline
References _delimiter.
std::string lsst::meas::algorithms::shapelet::ConfigFile::getInclude () const inline
References _include.
ConvertibleString & lsst::meas::algorithms::shapelet::ConfigFile::getNoCheck (const std::string & key)
References _contents, and trim().
Referenced by operator[]().
std::string lsst::meas::algorithms::shapelet::ConfigFile::getSentry () const inline
References _sentry.
std::string lsst::meas::algorithms::shapelet::ConfigFile::getstr (const std::string key) const throw (const char*)
References val.
std::string lsst::meas::algorithms::shapelet::ConfigFile::getstr (const std::string key, const std::string defval)
References _contents, and val.
bool lsst::meas::algorithms::shapelet::ConfigFile::keyExists (const std::string & key) const
References _contents.
Referenced by lsst::meas::algorithms::shapelet::FittedPsf::calculate().
void lsst::meas::algorithms::shapelet::ConfigFile::load (const std::string fileName) inline
References read().
Referenced by read().
void lsst::meas::algorithms::shapelet::ConfigFile::load (const std::string fileName, const std::string delimiter, const std::string comment = "", const std::string include = "", const std::string sentry = "")
References _comment, _delimiter, _include, and _sentry.
ConvertibleString& lsst::meas::algorithms::shapelet::ConfigFile::operator[] (const std::string & key) inline
References getNoCheck().
ConvertibleString lsst::meas::algorithms::shapelet::ConfigFile::operator[] (const std::string & key) const inline
void lsst::meas::algorithms::shapelet::ConfigFile::read (std::istream & is)
References _comment, _contents, _delimiter, _include, _sentry, line(), load(), and trim().
Referenced by append(), lsst::meas::algorithms::shapelet::FittedPsf::calculate(), load(), lsst::meas::algorithms::shapelet::operator>>(), lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::SizeMagnitudeStarSelectorAlgo(), and lsst::meas::algorithms::shapelet::Status().
template<typename T > T lsst::meas::algorithms::shapelet::ConfigFile::read (const std::string & key) const inline
References _contents, trim(), and xdbg.
template<typename T > T lsst::meas::algorithms::shapelet::ConfigFile::read (const std::string & key, const T & value) const inline
References _contents, trim(), and xdbg.
template<typename T > bool lsst::meas::algorithms::shapelet::ConfigFile::readInto (T & var, const std::string & key) const inline
References _contents, trim(), and xdbg.
template<typename T > bool lsst::meas::algorithms::shapelet::ConfigFile::readInto (T & var, const std::string & key, const T & value) const inline
References _contents, trim(), and xdbg.
void lsst::meas::algorithms::shapelet::ConfigFile::remove (const std::string & key)
References _contents.
std::string lsst::meas::algorithms::shapelet::ConfigFile::setComment (const std::string & s) inline
References _comment.
Referenced by lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::SizeMagnitudeStarSelectorAlgo().
std::string lsst::meas::algorithms::shapelet::ConfigFile::setDelimiter (const std::string & s) inline
References _delimiter.
Referenced by lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::SizeMagnitudeStarSelectorAlgo().
std::string lsst::meas::algorithms::shapelet::ConfigFile::setInclude (const std::string & s) inline
References _include.
std::string lsst::meas::algorithms::shapelet::ConfigFile::setSentry (const std::string & s) inline
References _sentry.
size_t lsst::meas::algorithms::shapelet::ConfigFile::size () inline
References _contents.
void lsst::meas::algorithms::shapelet::ConfigFile::trim (std::string & s) static protected
Referenced by add(), get(), getNoCheck(), read(), and readInto().
void lsst::meas::algorithms::shapelet::ConfigFile::write (std::ostream & os) const
References _contents, and _delimiter.
Referenced by lsst::meas::algorithms::shapelet::operator<<().
void lsst::meas::algorithms::shapelet::ConfigFile::writeAsComment (std::ostream & os) const
References _comment, _contents, and _delimiter.
Member Data Documentation
std::string lsst::meas::algorithms::shapelet::ConfigFile::_comment protected
Referenced by getComment(), load(), read(), setComment(), and writeAsComment().
std::map<std::string,ConvertibleString> lsst::meas::algorithms::shapelet::ConfigFile::_contents protected
Referenced by add(), get(), getNoCheck(), getstr(), keyExists(), read(), readInto(), remove(), size(), write(), and writeAsComment().
std::string lsst::meas::algorithms::shapelet::ConfigFile::_delimiter protected
Referenced by getDelimiter(), load(), read(), setDelimiter(), write(), and writeAsComment().
std::string lsst::meas::algorithms::shapelet::ConfigFile::_include protected
Referenced by getInclude(), load(), read(), and setInclude().
std::string lsst::meas::algorithms::shapelet::ConfigFile::_sentry protected
Referenced by getSentry(), load(), read(), and setSentry().
The documentation for this class was generated from the following files:
include/lsst/meas/algorithms/shapelet/ConfigFile.h
src/shapelet/ConfigFile.cc