lsst.meas.algorithms: lsst::meas::algorithms::shapelet::Ellipse Class Reference
lsst::meas::algorithms::shapelet::Ellipse Class Reference
#include <Ellipse.h>
Public Member Functions
Ellipse ()
Ellipse (std::complex< double > cen, std::complex< double > gamma, std::complex< double > mu)
Ellipse (double vals[])
Ellipse (const Ellipse &e2)
Ellipse & operator= (const Ellipse &e2)
bool measure (const std::vector< PixelList > &pix, int order, int order2, int maxm, double sigma, long &flag, double thresh, DMatrix *cov=0)
bool measure (const std::vector< PixelList > &pix, const std::vector< BVec > &psf, int order, int order2, int maxm, double sigma, long &flag, double thresh, DMatrix *cov=0)
bool findRoundFrame (const BVec &b, bool psf, int galOrder2, double thresh, long &flag, DMatrix *cov=0)
void crudeMeasure (const PixelList &pix, double sigma)
void crudeMeasure (const std::vector< PixelList > &pix, double sigma)
void peakCentroid (const PixelList &pix, double maxr)
bool measureShapelet (const std::vector< PixelList > &pix, BVec &bret, int order, int order2, int maxm, DMatrix *bcov=0) const
bool measureShapelet (const std::vector< PixelList > &pix, const std::vector< BVec > &psf, BVec &bret, int order, int order2, int maxm, DMatrix *bcov=0) const
bool altMeasureShapelet (const std::vector< PixelList > &pix, const std::vector< BVec > &psf, BVec &bret, int order, int order2, double pixScale, DMatrix *bcov=0) const
bool altMeasureShapelet (const std::vector< PixelList > &pix, BVec &bret, int order, int order2, double pixScale, DMatrix *bcov=0) const
void preShiftBy (const std::complex< double > &cen, const std::complex< double > &gamma, const std::complex< double > &mu)
void postShiftBy (const std::complex< double > &cen, const std::complex< double > &gamma, const std::complex< double > &mu)
void removeRotation ()
std::complex< double > getCen () const
std::complex< double > getGamma () const
double getMu () const
double getTheta () const
void setCen (const std::complex< double > &cen)
void setGamma (const std::complex< double > &gamma)
void setMu (double mu)
void setTheta (double theta)
void fixCen ()
void fixGam ()
void fixMu ()
void unfixCen ()
void unfixGam ()
void unfixMu ()
bool isFixedCen () const
bool isFixedGamma () const
bool isFixedMu () const
void doTimings ()
void write (std::ostream &os) const
Constructor & Destructor Documentation
lsst::meas::algorithms::shapelet::Ellipse::Ellipse () inline
lsst::meas::algorithms::shapelet::Ellipse::Ellipse (std::complex< double > cen, std::complex< double > gamma, std::complex< double > mu) inline
lsst::meas::algorithms::shapelet::Ellipse::Ellipse (double vals[]) inline
lsst::meas::algorithms::shapelet::Ellipse::Ellipse (const Ellipse & e2) inline
Member Function Documentation
bool lsst::meas::algorithms::shapelet::Ellipse::altMeasureShapelet (const std::vector< PixelList > & pix, const std::vector< BVec > & psf, BVec & bret, int order, int order2, double pixScale, DMatrix * bcov = 0) const
bool lsst::meas::algorithms::shapelet::Ellipse::altMeasureShapelet (const std::vector< PixelList > & pix, BVec & bret, int order, int order2, double pixScale, DMatrix * bcov = 0) const
void lsst::meas::algorithms::shapelet::Ellipse::crudeMeasure (const PixelList & pix, double sigma)
References dbg, dbgout, EIGEN_Transpose, isFixedCen(), isFixedMu(), norm(), lsst::meas::algorithms::shapelet::NLSolver::noUseCholesky(), real(), lsst::meas::algorithms::shapelet::NLSolver::setDelta0(), lsst::meas::algorithms::shapelet::NLSolver::setFTol(), lsst::meas::algorithms::shapelet::NLSolver::setMinStep(), lsst::meas::algorithms::shapelet::NLSolver::setOutput(), lsst::meas::algorithms::shapelet::NLSolver::setTau(), lsst::meas::algorithms::shapelet::NLSolver::setTol(), lsst::meas::algorithms::shapelet::PixelList::size(), lsst::meas::algorithms::shapelet::NLSolver::solve(), lsst::meas::algorithms::shapelet::NLSolver::useHybrid(), xdbg, and XDEBUG.
Referenced by crudeMeasure().
void lsst::meas::algorithms::shapelet::Ellipse::crudeMeasure (const std::vector< PixelList > & pix, double sigma)
References crudeMeasure(), and k.
void lsst::meas::algorithms::shapelet::Ellipse::doTimings () inline
bool lsst::meas::algorithms::shapelet::Ellipse::findRoundFrame (const BVec & b, bool psf, int galOrder2, double thresh, long & flag, DMatrix * cov = 0)
References dbg, dbgout, lsst::meas::algorithms::shapelet::EllipseSolver3::dontZeroB11(), EIGEN_Transpose, lsst::meas::algorithms::shapelet::EllipseSolver3::getCovariance(), lsst::meas::algorithms::shapelet::NLSolver::getFTol(), lsst::meas::algorithms::shapelet::BVec::getSigma(), lsst::meas::algorithms::shapelet::NLSolver::noUseCholesky(), preShiftBy(), lsst::meas::algorithms::shapelet::NLSolver::setDelta0(), lsst::meas::algorithms::shapelet::NLSolver::setMaxIter(), lsst::meas::algorithms::shapelet::NLSolver::setMinStep(), lsst::meas::algorithms::shapelet::NLSolver::setOutput(), lsst::meas::algorithms::shapelet::NLSolver::setTol(), lsst::meas::algorithms::shapelet::EllipseSolver3::solve(), lsst::meas::algorithms::shapelet::NLSolver::useDogleg(), lsst::meas::algorithms::shapelet::NLSolver::useHybrid(), lsst::meas::algorithms::shapelet::NLSolver::useSVD(), lsst::meas::algorithms::shapelet::NLSolver::useVerboseOutput(), xdbg, and XDEBUG.
void lsst::meas::algorithms::shapelet::Ellipse::fixCen () inline
void lsst::meas::algorithms::shapelet::Ellipse::fixGam () inline
void lsst::meas::algorithms::shapelet::Ellipse::fixMu () inline
std::complex<double> lsst::meas::algorithms::shapelet::Ellipse::getCen () const inline
Referenced by operator=().
std::complex<double> lsst::meas::algorithms::shapelet::Ellipse::getGamma () const inline
Referenced by operator=().
double lsst::meas::algorithms::shapelet::Ellipse::getMu () const inline
References real().
Referenced by operator=(), and setTheta().
double lsst::meas::algorithms::shapelet::Ellipse::getTheta () const inline
Referenced by operator=(), and setMu().
bool lsst::meas::algorithms::shapelet::Ellipse::isFixedCen () const inline
Referenced by crudeMeasure().
bool lsst::meas::algorithms::shapelet::Ellipse::isFixedGamma () const inline
bool lsst::meas::algorithms::shapelet::Ellipse::isFixedMu () const inline
Referenced by crudeMeasure().
bool lsst::meas::algorithms::shapelet::Ellipse::measure (const std::vector< PixelList > & pix, int order, int order2, int maxm, double sigma, long & flag, double thresh, DMatrix * cov = 0)
bool lsst::meas::algorithms::shapelet::Ellipse::measure (const std::vector< PixelList > & pix, const std::vector< BVec > & psf, int order, int order2, int maxm, double sigma, long & flag, double thresh, DMatrix * cov = 0)
bool lsst::meas::algorithms::shapelet::Ellipse::measureShapelet (const std::vector< PixelList > & pix, BVec & bret, int order, int order2, int maxm, DMatrix * bcov = 0) const
bool lsst::meas::algorithms::shapelet::Ellipse::measureShapelet (const std::vector< PixelList > & pix, const std::vector< BVec > & psf, BVec & bret, int order, int order2, int maxm, DMatrix * bcov = 0) const
Ellipse& lsst::meas::algorithms::shapelet::Ellipse::operator= (const Ellipse & e2) inline
References getCen(), getGamma(), getMu(), and getTheta().
void lsst::meas::algorithms::shapelet::Ellipse::peakCentroid (const PixelList & pix, double maxr)
References lsst::meas::algorithms::shapelet::PixelList::size().
void lsst::meas::algorithms::shapelet::Ellipse::postShiftBy (const std::complex< double > & cen, const std::complex< double > & gamma, const std::complex< double > & mu)
References lsst::meas::algorithms::shapelet::CalculateShift().
void lsst::meas::algorithms::shapelet::Ellipse::preShiftBy (const std::complex< double > & cen, const std::complex< double > & gamma, const std::complex< double > & mu)
References lsst::meas::algorithms::shapelet::CalculateShift().
Referenced by findRoundFrame().
void lsst::meas::algorithms::shapelet::Ellipse::removeRotation ()
References real().
void lsst::meas::algorithms::shapelet::Ellipse::setCen (const std::complex< double > & cen) inline
void lsst::meas::algorithms::shapelet::Ellipse::setGamma (const std::complex< double > & gamma) inline
void lsst::meas::algorithms::shapelet::Ellipse::setMu (double mu) inline
References getTheta().
void lsst::meas::algorithms::shapelet::Ellipse::setTheta (double theta) inline
References getMu().
void lsst::meas::algorithms::shapelet::Ellipse::unfixCen () inline
void lsst::meas::algorithms::shapelet::Ellipse::unfixGam () inline
void lsst::meas::algorithms::shapelet::Ellipse::unfixMu () inline
void lsst::meas::algorithms::shapelet::Ellipse::write (std::ostream & os) const inline
Referenced by lsst::meas::algorithms::shapelet::operator<<().
The documentation for this class was generated from the following files:
include/lsst/meas/algorithms/shapelet/Ellipse.h
src/shapelet/CrudeMeasure.cc
src/shapelet/Ellipse.cc
src/shapelet/Ellipse_meas.cc