lsst.meas.algorithms: lsst::meas::algorithms::ShapeletPsfCandidate Class Reference
lsst::meas::algorithms::ShapeletPsfCandidate Class Reference
#include <ShapeletPsfCandidate.h>
Public Types
typedef
lsst::afw::math::SpatialCellCandidate base
typedef
lsst::afw::table::SourceRecord Source
typedef boost::shared_ptr
< ShapeletPsfCandidate > Ptr
typedef boost::shared_ptr
< const ShapeletPsfCandidate > ConstPtr
Public Types inherited from lsst::afw::math::SpatialCellCandidate
enum Status
typedef boost::shared_ptr
< SpatialCellCandidate > Ptr
typedef boost::shared_ptr
< const SpatialCellCandidate > ConstPtr
Public Member Functions
ShapeletPsfCandidate (double x, double y, double size, boost::shared_ptr< Source > source)
Constructor takes position, size, and original source.
void setShapelet (Shapelet::ConstPtr shapelet)
Set the shapelet decomposition.
double getX () const
Get position.
double getY () const
double getSize () const
Get size.
boost::shared_ptr< Source > getSource () const
Get source.
Shapelet::ConstPtr getShapelet () const
Get the shapelet decomposition.
bool hasShapelet () const
Check if shapelet decomposition is set.
double getCandidateRating () const
Define "goodness" of candidate for SpatialCell.
void setBad ()
Mark the candidate as BAD.
Public Member Functions inherited from lsst::afw::math::SpatialCellCandidate
SpatialCellCandidate (float const xCenter, float const yCenter)
virtual ~SpatialCellCandidate ()
float getXCenter () const
float getYCenter () const
virtual bool instantiate ()
virtual void setCandidateRating (double)
int getId () const
Status getStatus () const
void setStatus (Status status)
virtual bool isBad () const
Additional Inherited Members
Public Attributes inherited from lsst::afw::math::SpatialCellCandidate
BAD
GOOD
UNKNOWN
Member Typedef Documentation
typedef lsst::afw::math::SpatialCellCandidate lsst::meas::algorithms::ShapeletPsfCandidate::base
typedef boost::shared_ptr<const ShapeletPsfCandidate> lsst::meas::algorithms::ShapeletPsfCandidate::ConstPtr
typedef boost::shared_ptr<ShapeletPsfCandidate> lsst::meas::algorithms::ShapeletPsfCandidate::Ptr
typedef lsst::afw::table::SourceRecord lsst::meas::algorithms::ShapeletPsfCandidate::Source
Constructor & Destructor Documentation
lsst::meas::algorithms::ShapeletPsfCandidate::ShapeletPsfCandidate (double x, double y, double size, boost::shared_ptr< Source > source) inline
Constructor takes position, size, and original source.
The object stores the position, and initial guess of the size and takes whatever other information is required from the Source data. Currently, only sky is used, but it seemed wise to have source in the constructor in case we decide to store something else too. For example, we will eventually want to extract some kind of color information.
I don't store the image, wcs, or weightImage in the candidate itself, since all candidates will have the same things for these.
Once we start doing PCA-style interpolations that use sources from different exposures, we will have to do something different. But that algorithm will require a pretty significant re-thinking of the design anyway, so no point in worrying about that yet.
(No destructor, copy constructor, or op=, since the defaults do the right thing.)
Parameters
x X position of candidate
y Y position of candidate
size Initial estimate of size
source Original source
References PTR.
Member Function Documentation
double lsst::meas::algorithms::ShapeletPsfCandidate::getCandidateRating () const inline virtual
Define "goodness" of candidate for SpatialCell.
Implements lsst::afw::math::SpatialCellCandidate.
Referenced by lsst::meas::algorithms::LoadCandidatesVisitor::processCandidate().
Shapelet::ConstPtr lsst::meas::algorithms::ShapeletPsfCandidate::getShapelet () const inline
Get the shapelet decomposition.
Referenced by lsst::meas::algorithms::LoadCandidatesVisitor::processCandidate().
double lsst::meas::algorithms::ShapeletPsfCandidate::getSize () const inline
Get size.
boost::shared_ptr< Source > lsst::meas::algorithms::ShapeletPsfCandidate::getSource () const inline
Get source.
References PTR.
double lsst::meas::algorithms::ShapeletPsfCandidate::getX () const inline
Get position.
References lsst::afw::math::SpatialCellCandidate::getXCenter().
Referenced by lsst::meas::algorithms::LoadCandidatesVisitor::processCandidate().
double lsst::meas::algorithms::ShapeletPsfCandidate::getY () const inline
References lsst::afw::math::SpatialCellCandidate::getYCenter().
Referenced by lsst::meas::algorithms::LoadCandidatesVisitor::processCandidate().
bool lsst::meas::algorithms::ShapeletPsfCandidate::hasShapelet () const inline
Check if shapelet decomposition is set.
void lsst::meas::algorithms::ShapeletPsfCandidate::setBad () inline
Mark the candidate as BAD.
SpatialCellCandidate::setStatus is a bit of a pain to use, since there doesn't seem to be any way around explicitly specifying the full namespace and class specification of BAD. So do it once here.
References lsst::afw::math::SpatialCellCandidate::BAD, and lsst::afw::math::SpatialCellCandidate::setStatus().
void lsst::meas::algorithms::ShapeletPsfCandidate::setShapelet (Shapelet::ConstPtr shapelet) inline
Set the shapelet decomposition.
The documentation for this class was generated from the following file:
include/lsst/meas/algorithms/ShapeletPsfCandidate.h