lsst.meas.algorithms: lsst::meas::algorithms::shapelet::PixelList Class Reference
lsst::meas::algorithms::shapelet::PixelList Class Reference
#include <Pixel.h>
Public Member Functions
PixelList ()
PixelList (const int n)
PixelList (const PixelList &rhs)
PixelList & operator= (const PixelList &rhs)
~PixelList ()
void usePool ()
size_t size () const
void reserve (const int n)
size_t capacity () const
void resize (const int n)
void clear ()
void push_back (const Pixel &p)
Pixel & operator[] (const int i)
const Pixel & operator[] (const int i) const
void sort (const Position &cen)
Constructor & Destructor Documentation
lsst::meas::algorithms::shapelet::PixelList::PixelList ()
lsst::meas::algorithms::shapelet::PixelList::PixelList (const int n)
lsst::meas::algorithms::shapelet::PixelList::PixelList (const PixelList & rhs)
References copy().
lsst::meas::algorithms::shapelet::PixelList::~PixelList ()
Member Function Documentation
size_t lsst::meas::algorithms::shapelet::PixelList::capacity () const
void lsst::meas::algorithms::shapelet::PixelList::clear ()
PixelList & lsst::meas::algorithms::shapelet::PixelList::operator= (const PixelList & rhs)
References copy(), resize(), and size().
Pixel & lsst::meas::algorithms::shapelet::PixelList::operator[] (const int i)
const Pixel & lsst::meas::algorithms::shapelet::PixelList::operator[] (const int i) const
void lsst::meas::algorithms::shapelet::PixelList::push_back (const Pixel & p)
void lsst::meas::algorithms::shapelet::PixelList::reserve (const int n)
void lsst::meas::algorithms::shapelet::PixelList::resize (const int n)
Referenced by lsst::meas::algorithms::shapelet::getSubPixList(), and operator=().
size_t lsst::meas::algorithms::shapelet::PixelList::size () const
Referenced by lsst::meas::algorithms::shapelet::Ellipse::crudeMeasure(), lsst::meas::algorithms::shapelet::CrudeSolver::CrudeSolver(), lsst::meas::algorithms::shapelet::getSubPixList(), operator=(), and lsst::meas::algorithms::shapelet::Ellipse::peakCentroid().
void lsst::meas::algorithms::shapelet::PixelList::sort (const Position & cen)
void lsst::meas::algorithms::shapelet::PixelList::usePool ()
References Assert.
The documentation for this class was generated from the following files:
include/lsst/meas/algorithms/shapelet/Pixel.h
src/shapelet/Pixel_omp.cc