lsst.meas.algorithms: lsst::meas::algorithms::ExposurePatch< ExposureT > Class Template Reference
lsst::meas::algorithms::ExposurePatch< ExposureT > Class Template Reference
#include <ExposurePatch.h>
Public Types
typedef unsigned char FlagT
Type for flags.
typedef boost::shared_ptr
< ExposurePatch > Ptr
typedef boost::shared_ptr
< ExposurePatch const > ConstPtr
Public Member Functions
ExposurePatch (boost::shared_ptr< ExposureT const > exp, boost::shared_ptr< afw::detection::Footprint const > foot, afw::geom::Point2D const &center)
Constructor.
ExposurePatch (boost::shared_ptr< ExposureT const > exp, afw::detection::Footprint const &standardFoot, afw::geom::Point2D const &standardCenter, afw::image::Wcs const &standardWcs)
boost::shared_ptr< ExposureT
const > const getExposure () const
Accessors.
boost::shared_ptr
< afw::detection::Footprint
const > const getFootprint () const
afw::geom::Point2D const & getCenter () const
afw::geom::AffineTransform const & fromStandard () const
afw::geom::AffineTransform const & toStandard () const
void setCenter (afw::geom::Point2D const &center)
Modifiers.
Detailed Description
template<typename ExposureT>
class lsst::meas::algorithms::ExposurePatch< ExposureT >
A convenience container for the exposure, peak and footprint that will be measured.
This is more useful than a std::pair or similar.
Member Typedef Documentation
template<typename ExposureT> typedef boost::shared_ptr< ExposurePatch const> lsst::meas::algorithms::ExposurePatch< ExposureT >::ConstPtr
template<typename ExposureT> typedef unsigned char lsst::meas::algorithms::ExposurePatch< ExposureT >::FlagT
Type for flags.
template<typename ExposureT> typedef boost::shared_ptr< ExposurePatch > lsst::meas::algorithms::ExposurePatch< ExposureT >::Ptr
Constructor & Destructor Documentation
template<typename ExposureT> lsst::meas::algorithms::ExposurePatch< ExposureT >::ExposurePatch (boost::shared_ptr< ExposureT const > exp, boost::shared_ptr< afw::detection::Footprint const > foot, afw::geom::Point2D const & center) inline
Constructor.
Parameters
exp Exposure of interest
foot Footprint on exposure
center Center of object on exposure
template<typename ExposureT> lsst::meas::algorithms::ExposurePatch< ExposureT >::ExposurePatch (boost::shared_ptr< ExposureT const > exp, afw::detection::Footprint const & standardFoot, afw::geom::Point2D const & standardCenter, afw::image::Wcs const & standardWcs) inline
Parameters
exp Exposure of interest
standardFoot Footprint on some other exposure
standardCenter Center on that other exposure
standardWcs WCS for that other exposure
References CONST_PTR, lsst::afw::image::Wcs::linearizePixelToSky(), lsst::afw::image::Wcs::linearizeSkyToPixel(), lsst::afw::image::Wcs::pixelToSky(), lsst::afw::image::Wcs::skyToPixel(), and lsst::afw::detection::Footprint::transform().
Member Function Documentation
template<typename ExposureT> afw::geom::AffineTransform const& lsst::meas::algorithms::ExposurePatch< ExposureT >::fromStandard () const inline
template<typename ExposureT> afw::geom::Point2D const& lsst::meas::algorithms::ExposurePatch< ExposureT >::getCenter () const inline
template<typename ExposureT> boost::shared_ptr< ExposureT const> const lsst::meas::algorithms::ExposurePatch< ExposureT >::getExposure () const inline
Accessors.
References CONST_PTR.
template<typename ExposureT> boost::shared_ptr< afw::detection::Footprint const> const lsst::meas::algorithms::ExposurePatch< ExposureT >::getFootprint () const inline
References CONST_PTR.
template<typename ExposureT> void lsst::meas::algorithms::ExposurePatch< ExposureT >::setCenter (afw::geom::Point2D const & center) inline
Modifiers.
template<typename ExposureT> afw::geom::AffineTransform const& lsst::meas::algorithms::ExposurePatch< ExposureT >::toStandard () const inline
The documentation for this class was generated from the following file:
include/lsst/meas/algorithms/ExposurePatch.h