lsst.meas.algorithms: lsst::meas::algorithms::shapelet::BVec Class Reference
lsst::meas::algorithms::shapelet::BVec Class Reference
#include <BVec.h>
Public Member Functions
BVec (int order, double sigma)
BVec (int order, double sigma, double *bvec)
BVec (int order, double sigma, const DVector &bvec)
BVec (const BVec &rhs)
~BVec ()
BVec & operator= (const AssignableToBVec &rhs)
BVec & operator= (const BVec &rhs)
void assignTo (BVec &bvec) const
DVector & vec ()
const DVector & vec () const
double & operator() (int i)
double operator() (int i) const
int getOrder () const
double getSigma () const
const DVector & getValues () const
size_t size () const
void setSigma (double sigma)
void setValues (const DVector &v)
template<typename V >
void setValues (const V &v)
void normalize ()
void conjugateSelf ()
Public Member Functions inherited from lsst::meas::algorithms::shapelet::AssignableToBVec
virtual ~AssignableToBVec ()
Constructor & Destructor Documentation
lsst::meas::algorithms::shapelet::BVec::BVec (int order, double sigma) inline
lsst::meas::algorithms::shapelet::BVec::BVec (int order, double sigma, double * bvec) inline
lsst::meas::algorithms::shapelet::BVec::BVec (int order, double sigma, const DVector & bvec) inline
lsst::meas::algorithms::shapelet::BVec::BVec (const BVec & rhs) inline
lsst::meas::algorithms::shapelet::BVec::~BVec () inline
Member Function Documentation
void lsst::meas::algorithms::shapelet::BVec::assignTo (BVec & bvec) const virtual
Implements lsst::meas::algorithms::shapelet::AssignableToBVec.
References setSigma(), and setValues().
Referenced by operator=().
void lsst::meas::algorithms::shapelet::BVec::conjugateSelf ()
References getOrder(), and k.
int lsst::meas::algorithms::shapelet::BVec::getOrder () const inline virtual
Implements lsst::meas::algorithms::shapelet::AssignableToBVec.
Referenced by lsst::meas::algorithms::shapelet::applyG(), lsst::meas::algorithms::shapelet::applyMu(), lsst::meas::algorithms::shapelet::applyPsf(), lsst::meas::algorithms::shapelet::applyTheta(), lsst::meas::algorithms::shapelet::applyZ(), lsst::meas::algorithms::shapelet::calculatePsfConvolve(), conjugateSelf(), lsst::meas::algorithms::ShapeletImpl::evaluateAt(), lsst::meas::algorithms::Shapelet::getOrder(), lsst::meas::algorithms::shapelet::FittedPsf::interpolate(), and lsst::meas::algorithms::shapelet::operator<<().
double lsst::meas::algorithms::shapelet::BVec::getSigma () const inline virtual
Implements lsst::meas::algorithms::shapelet::AssignableToBVec.
Referenced by lsst::meas::algorithms::shapelet::applyPsf(), lsst::meas::algorithms::shapelet::applyZ(), lsst::meas::algorithms::shapelet::calculatePsfConvolve(), lsst::meas::algorithms::ShapeletImpl::evaluateAt(), lsst::meas::algorithms::shapelet::Ellipse::findRoundFrame(), lsst::meas::algorithms::Shapelet::getSigma(), lsst::meas::algorithms::Shapelet::measureFromImage(), and lsst::meas::algorithms::shapelet::operator<<().
const DVector& lsst::meas::algorithms::shapelet::BVec::getValues () const inline
Referenced by lsst::meas::algorithms::ShapeletImpl::evaluateAt(), lsst::meas::algorithms::ShapeletImpl::getPQ(), and lsst::meas::algorithms::Shapelet::getValues().
void lsst::meas::algorithms::shapelet::BVec::normalize () inline
double& lsst::meas::algorithms::shapelet::BVec::operator() (int i) inline
double lsst::meas::algorithms::shapelet::BVec::operator() (int i) const inline
BVec & lsst::meas::algorithms::shapelet::BVec::operator= (const AssignableToBVec & rhs)
References lsst::meas::algorithms::shapelet::AssignableToBVec::assignTo().
Referenced by lsst::meas::algorithms::ShapeletImpl::operator=().
BVec & lsst::meas::algorithms::shapelet::BVec::operator= (const BVec & rhs)
References assignTo().
void lsst::meas::algorithms::shapelet::BVec::setSigma (double sigma) inline
Referenced by assignTo(), lsst::meas::algorithms::shapelet::FittedPsf::interpolate(), lsst::meas::algorithms::Shapelet::measureFromImage(), and lsst::meas::algorithms::Shapelet::setSigma().
void lsst::meas::algorithms::shapelet::BVec::setValues (const DVector & v)
References xdbg.
Referenced by assignTo().
template<typename V > void lsst::meas::algorithms::shapelet::BVec::setValues (const V & v) inline
References Assert, and size().
size_t lsst::meas::algorithms::shapelet::BVec::size () const inline
Referenced by lsst::meas::algorithms::shapelet::applyG(), lsst::meas::algorithms::shapelet::applyMu(), lsst::meas::algorithms::shapelet::applyPsf(), lsst::meas::algorithms::shapelet::applyTheta(), lsst::meas::algorithms::shapelet::applyZ(), lsst::meas::algorithms::shapelet::calculatePsfConvolve(), lsst::meas::algorithms::ShapeletImpl::evaluateAt(), lsst::meas::algorithms::shapelet::FittedPsf::interpolate(), setValues(), and lsst::meas::algorithms::Shapelet::size().
DVector& lsst::meas::algorithms::shapelet::BVec::vec () inline
Referenced by lsst::meas::algorithms::shapelet::applyG(), lsst::meas::algorithms::shapelet::applyMu(), lsst::meas::algorithms::shapelet::applyPsf(), lsst::meas::algorithms::shapelet::applyTheta(), lsst::meas::algorithms::shapelet::applyZ(), lsst::meas::algorithms::shapelet::FittedPsf::calculate(), lsst::meas::algorithms::shapelet::calculatePsfConvolve(), lsst::meas::algorithms::shapelet::FittedPsf::interpolate(), and lsst::meas::algorithms::shapelet::operator<<().
const DVector& lsst::meas::algorithms::shapelet::BVec::vec () const inline
The documentation for this class was generated from the following files:
include/lsst/meas/algorithms/shapelet/BVec.h
src/shapelet/BVec.cc