lsst.meas.algorithms: lsst::meas::algorithms::PsfAttributes Class Reference
lsst::meas::algorithms::PsfAttributes Class Reference
#include <PSF.h>
Public Types
enum Method {
ADAPTIVE_MOMENT, FIRST_MOMENT, SECOND_MOMENT, NOISE_EQUIVALENT,
BICKERTON
}
Public Member Functions
PsfAttributes (boost::shared_ptr< lsst::afw::detection::Psf const > psf, int const iX, int const iY)
Constructor for PsfAttributes.
PsfAttributes (boost::shared_ptr< lsst::afw::detection::Psf const > psf, lsst::afw::geom::Point2I const &cen)
Constructor for PsfAttributes.
double computeGaussianWidth (Method how=ADAPTIVE_MOMENT) const
Compute the 'sigma' value for an equivalent gaussian psf.
double computeEffectiveArea () const
Compute the effective area of the psf (sum(I)^2/sum(I^2))
Detailed Description
A class to contain various attributes of the Psf
most notably, a width (1-D RMS size) to be used to make a single gaussian psf for fast convolution.
Deprecated:
This class is deprecated in favour of virtual methods on Psf
An example of the new API is:
afwGeom::ellipses::Quadrupole shape = psf->computeShape();
double const smoothingSigma = shape.getDeterminantRadius();
Member Enumeration Documentation
enum lsst::meas::algorithms::PsfAttributes::Method
Enumerator:
ADAPTIVE_MOMENT
Calculate width using adaptive Gaussian weights.
FIRST_MOMENT
Calculate width using <r>
SECOND_MOMENT
Calculate width using <r^2>
NOISE_EQUIVALENT
Calculate width as sqrt(n_eff/(4 pi))
BICKERTON
Weight <r^2> by I^2 to avoid negative fluxes.
Constructor & Destructor Documentation
lsst::meas::algorithms::PsfAttributes::PsfAttributes (boost::shared_ptr< lsst::afw::detection::Psf const > psf, int const iX, int const iY)
Constructor for PsfAttributes.
Parameters
psf The psf whose attributes we want
iX the x position in the frame we want the attributes at
iY the y position in the frame we want the attributes at
References lsst::afw::detection::Psf::computeImage(), and CONST_PTR.
lsst::meas::algorithms::PsfAttributes::PsfAttributes (boost::shared_ptr< lsst::afw::detection::Psf const > psf, lsst::afw::geom::Point2I const & cen)
Constructor for PsfAttributes.
Parameters
psf The psf whose attributes we want
cen the position in the frame we want the attributes at
References CONST_PTR.
Member Function Documentation
double lsst::meas::algorithms::PsfAttributes::computeEffectiveArea () const
Compute the effective area of the psf (sum(I)^2/sum(I^2))
Referenced by computeGaussianWidth().
double lsst::meas::algorithms::PsfAttributes::computeGaussianWidth (PsfAttributes::Method how = ADAPTIVE_MOMENT) const
Compute the 'sigma' value for an equivalent gaussian psf.
References ADAPTIVE_MOMENT, lsst::meas::algorithms::MeasureSourcesBuilder::addAlgorithm(), lsst::meas::algorithms::MeasureSources::apply(), BICKERTON, lsst::meas::algorithms::MeasureSourcesBuilder::build(), computeEffectiveArea(), FIRST_MOMENT, lsst::afw::table::SourceTable::make(), makeExposure(), lsst::afw::table::SourceTable::makeMinimalSchema(), NOISE_EQUIVALENT, PTR, and SECOND_MOMENT.
The documentation for this class was generated from the following files:
include/lsst/meas/algorithms/PSF.h
src/PsfAttributes.cc