lsst.meas.algorithms: lsst::meas::algorithms::ShapeletImpl Class Reference
lsst::meas::algorithms::ShapeletImpl Class Reference
Public Types
typedef Shapelet::ShapeletVector ShapeletVector
typedef
Shapelet::ShapeletCovariance ShapeletCovariance
typedef shapelet::BVec BVec
Public Member Functions
ShapeletImpl (int order, double sigma)
ShapeletImpl (int order, double sigma, const ShapeletVector &vector)
ShapeletImpl (int order, double sigma, const ShapeletVector &vector, const ShapeletCovariance &cov)
ShapeletImpl (const BVec &rhs)
ShapeletImpl (const ShapeletImpl &rhs)
~ShapeletImpl ()
void operator= (const ShapeletImpl &rhs)
boost::shared_ptr
< ShapeletCovariance > & getCovariance ()
std::complex< double > getPQ (int p, int q)
double evaluateAt (double x, double y)
Public Member Functions inherited from lsst::meas::algorithms::shapelet::BVec
BVec (int order, double sigma)
BVec (int order, double sigma, double *bvec)
BVec (int order, double sigma, const DVector &bvec)
BVec (const BVec &rhs)
~BVec ()
BVec & operator= (const AssignableToBVec &rhs)
BVec & operator= (const BVec &rhs)
void assignTo (BVec &bvec) const
DVector & vec ()
const DVector & vec () const
double & operator() (int i)
double operator() (int i) const
int getOrder () const
double getSigma () const
const DVector & getValues () const
size_t size () const
void setSigma (double sigma)
void setValues (const DVector &v)
template<typename V >
void setValues (const V &v)
void normalize ()
void conjugateSelf ()
Public Member Functions inherited from lsst::meas::algorithms::shapelet::AssignableToBVec
virtual ~AssignableToBVec ()
Member Typedef Documentation
typedef shapelet::BVec lsst::meas::algorithms::ShapeletImpl::BVec
typedef Shapelet::ShapeletCovariance lsst::meas::algorithms::ShapeletImpl::ShapeletCovariance
typedef Shapelet::ShapeletVector lsst::meas::algorithms::ShapeletImpl::ShapeletVector
Constructor & Destructor Documentation
lsst::meas::algorithms::ShapeletImpl::ShapeletImpl (int order, double sigma) inline
lsst::meas::algorithms::ShapeletImpl::ShapeletImpl (int order, double sigma, const ShapeletVector & vector) inline
lsst::meas::algorithms::ShapeletImpl::ShapeletImpl (int order, double sigma, const ShapeletVector & vector, const ShapeletCovariance & cov) inline
lsst::meas::algorithms::ShapeletImpl::ShapeletImpl (const BVec & rhs) inline
lsst::meas::algorithms::ShapeletImpl::ShapeletImpl (const ShapeletImpl & rhs) inline
lsst::meas::algorithms::ShapeletImpl::~ShapeletImpl () inline
Member Function Documentation
double lsst::meas::algorithms::ShapeletImpl::evaluateAt (double x, double y) inline
References lsst::meas::algorithms::shapelet::BVec::getOrder(), lsst::meas::algorithms::shapelet::BVec::getSigma(), lsst::meas::algorithms::shapelet::BVec::getValues(), lsst::meas::algorithms::shapelet::makePsi(), lsst::meas::algorithms::shapelet::BVec::size(), and TMV_vview.
Referenced by lsst::meas::algorithms::Shapelet::evaluateAt().
boost::shared_ptr<ShapeletCovariance>& lsst::meas::algorithms::ShapeletImpl::getCovariance () inline
Referenced by lsst::meas::algorithms::Shapelet::getCovariance(), lsst::meas::algorithms::Shapelet::hasCovariance(), and lsst::meas::algorithms::Shapelet::measureFromImage().
std::complex<double> lsst::meas::algorithms::ShapeletImpl::getPQ (int p, int q) inline
References lsst::meas::algorithms::shapelet::BVec::getValues(), and k.
Referenced by lsst::meas::algorithms::Shapelet::getPQ().
void lsst::meas::algorithms::ShapeletImpl::operator= (const ShapeletImpl & rhs) inline
References lsst::meas::algorithms::shapelet::BVec::operator=().
The documentation for this class was generated from the following file:
src/Shapelet.cc