lsst.meas.algorithms: lsst::meas::algorithms::shapelet::Form Class Reference
lsst::meas::algorithms::shapelet::Form Class Reference
#include <Form.h>
Public Member Functions
Form ()
template<typename T >
BoundForm< T > operator() (T val) const
Form & prec (int p)
Form & sci ()
Form & fix ()
Form & gen ()
Form & width (int w)
Form & fill (char c)
Form & dec ()
Form & oct ()
Form & hex ()
Form & left ()
Form & right ()
Form & internal ()
Form & uppercase (bool b=true)
Form & showpos (bool b=true)
Form & showpoint (bool b=true)
Form & boolalpha (bool b=true)
Form & trail (int n, char ch=' ')
Friends
template<typename T >
std::ostream & operator<< (std::ostream &, const BoundForm< T > &)
void setupFloat (std::ostream &, const Form &)
void setupInt (std::ostream &, const Form &)
Constructor & Destructor Documentation
lsst::meas::algorithms::shapelet::Form::Form () inline
Member Function Documentation
Form& lsst::meas::algorithms::shapelet::Form::boolalpha (bool b = true) inline
References b.
Form& lsst::meas::algorithms::shapelet::Form::dec () inline
Form& lsst::meas::algorithms::shapelet::Form::fill (char c) inline
Form& lsst::meas::algorithms::shapelet::Form::fix () inline
Form& lsst::meas::algorithms::shapelet::Form::gen () inline
Form& lsst::meas::algorithms::shapelet::Form::hex () inline
Form& lsst::meas::algorithms::shapelet::Form::internal () inline
Form& lsst::meas::algorithms::shapelet::Form::left () inline
Form& lsst::meas::algorithms::shapelet::Form::oct () inline
template<typename T > BoundForm< T > lsst::meas::algorithms::shapelet::Form::operator() (T val) const inline
References val.
Form& lsst::meas::algorithms::shapelet::Form::prec (int p) inline
Referenced by lsst::meas::algorithms::shapelet::Histogram< T >::print().
Form& lsst::meas::algorithms::shapelet::Form::right () inline
Form& lsst::meas::algorithms::shapelet::Form::sci () inline
Referenced by lsst::meas::algorithms::shapelet::Histogram< T >::print().
Form& lsst::meas::algorithms::shapelet::Form::showpoint (bool b = true) inline
References b.
Form& lsst::meas::algorithms::shapelet::Form::showpos (bool b = true) inline
References b.
Form& lsst::meas::algorithms::shapelet::Form::trail (int n, char ch = ' ') inline
Form& lsst::meas::algorithms::shapelet::Form::uppercase (bool b = true) inline
References b.
Form& lsst::meas::algorithms::shapelet::Form::width (int w) inline
References w.
Referenced by lsst::meas::algorithms::shapelet::Histogram< T >::print().
Friends And Related Function Documentation
template<typename T > std::ostream& operator<< (std::ostream & os, const BoundForm< T > & bf) friend
void setupFloat (std::ostream & s, const Form & f) friend
void setupInt (std::ostream & s, const Form & f) friend
The documentation for this class was generated from the following file:
include/lsst/meas/algorithms/shapelet/Form.h