lsst.meas.algorithms: lsst::meas::algorithms::shapelet::NLSolver Class Reference
lsst::meas::algorithms::shapelet::NLSolver Class Reference abstract
#include <NLSolver.h>
Public Member Functions
NLSolver ()
virtual ~NLSolver ()
virtual void calculateF (const DVector &x, DVector &f) const =0
virtual void calculateJ (const DVector &x, const DVector &f, DMatrix &j) const
virtual bool solve (DVector &x, DVector &f) const
virtual void getCovariance (DMatrix &cov) const
virtual void getInverseCovariance (DMatrix &invcov) const
virtual bool testJ (const DVector &, DVector &, std::ostream *os=0, double relerr=0.) const
virtual void useHybrid ()
virtual void useDogleg ()
virtual void setFTol (double fTol)
virtual void setGTol (double gTol)
virtual void setTol (double fTol, double gTol)
virtual void setMinStep (double minStep)
virtual void setMaxIter (int maxIter)
virtual void setTau (double tau)
virtual void setDelta0 (double delta0)
virtual double getFTol ()
virtual double getGTol ()
virtual double getMinStep ()
virtual int getMaxIter ()
virtual double getTau ()
virtual double getDelta0 ()
virtual void setOutput (std::ostream &os)
virtual void useVerboseOutput ()
virtual void useExtraVerboseOutput ()
virtual void noUseVerboseOutput ()
virtual void useDirectH ()
virtual void useSVD ()
virtual void useCholesky ()
virtual void noUseDirectH ()
virtual void noUseSVD ()
virtual void noUseCholesky ()
Constructor & Destructor Documentation
lsst::meas::algorithms::shapelet::NLSolver::NLSolver ()
virtual lsst::meas::algorithms::shapelet::NLSolver::~NLSolver () inline virtual
Member Function Documentation
virtual void lsst::meas::algorithms::shapelet::NLSolver::calculateF (const DVector & x, DVector & f) const pure virtual
Implemented in lsst::meas::algorithms::shapelet::CrudeSolver, and lsst::meas::algorithms::shapelet::EllipseSolver3.
Referenced by calculateJ(), and testJ().
void lsst::meas::algorithms::shapelet::NLSolver::calculateJ (const DVector & x, const DVector & f, DMatrix & j) const virtual
Reimplemented in lsst::meas::algorithms::shapelet::CrudeSolver, and lsst::meas::algorithms::shapelet::EllipseSolver3.
References calculateF().
Referenced by lsst::meas::algorithms::shapelet::EllipseSolver3::calculateJ(), and testJ().
void lsst::meas::algorithms::shapelet::NLSolver::getCovariance (DMatrix & cov) const virtual
Reimplemented in lsst::meas::algorithms::shapelet::EllipseSolver3.
References dbg.
Referenced by lsst::meas::algorithms::shapelet::EllipseSolver3::getCovariance().
virtual double lsst::meas::algorithms::shapelet::NLSolver::getDelta0 () inline virtual
virtual double lsst::meas::algorithms::shapelet::NLSolver::getFTol () inline virtual
Referenced by lsst::meas::algorithms::shapelet::Ellipse::findRoundFrame().
virtual double lsst::meas::algorithms::shapelet::NLSolver::getGTol () inline virtual
void lsst::meas::algorithms::shapelet::NLSolver::getInverseCovariance (DMatrix & invcov) const virtual
Reimplemented in lsst::meas::algorithms::shapelet::EllipseSolver3.
Referenced by lsst::meas::algorithms::shapelet::EllipseSolver3::getInverseCovariance().
virtual int lsst::meas::algorithms::shapelet::NLSolver::getMaxIter () inline virtual
virtual double lsst::meas::algorithms::shapelet::NLSolver::getMinStep () inline virtual
virtual double lsst::meas::algorithms::shapelet::NLSolver::getTau () inline virtual
virtual void lsst::meas::algorithms::shapelet::NLSolver::noUseCholesky () inline virtual
Referenced by lsst::meas::algorithms::shapelet::Ellipse::crudeMeasure(), and lsst::meas::algorithms::shapelet::Ellipse::findRoundFrame().
virtual void lsst::meas::algorithms::shapelet::NLSolver::noUseDirectH () inline virtual
virtual void lsst::meas::algorithms::shapelet::NLSolver::noUseSVD () inline virtual
virtual void lsst::meas::algorithms::shapelet::NLSolver::noUseVerboseOutput () inline virtual
virtual void lsst::meas::algorithms::shapelet::NLSolver::setDelta0 (double delta0) inline virtual
Referenced by lsst::meas::algorithms::shapelet::Ellipse::crudeMeasure(), and lsst::meas::algorithms::shapelet::Ellipse::findRoundFrame().
virtual void lsst::meas::algorithms::shapelet::NLSolver::setFTol (double fTol) inline virtual
Referenced by lsst::meas::algorithms::shapelet::Ellipse::crudeMeasure().
virtual void lsst::meas::algorithms::shapelet::NLSolver::setGTol (double gTol) inline virtual
virtual void lsst::meas::algorithms::shapelet::NLSolver::setMaxIter (int maxIter) inline virtual
Referenced by lsst::meas::algorithms::shapelet::Ellipse::findRoundFrame().
virtual void lsst::meas::algorithms::shapelet::NLSolver::setMinStep (double minStep) inline virtual
Referenced by lsst::meas::algorithms::shapelet::Ellipse::crudeMeasure(), and lsst::meas::algorithms::shapelet::Ellipse::findRoundFrame().
virtual void lsst::meas::algorithms::shapelet::NLSolver::setOutput (std::ostream & os) inline virtual
Referenced by lsst::meas::algorithms::shapelet::Ellipse::crudeMeasure(), and lsst::meas::algorithms::shapelet::Ellipse::findRoundFrame().
virtual void lsst::meas::algorithms::shapelet::NLSolver::setTau (double tau) inline virtual
Referenced by lsst::meas::algorithms::shapelet::Ellipse::crudeMeasure().
virtual void lsst::meas::algorithms::shapelet::NLSolver::setTol (double fTol, double gTol) inline virtual
Referenced by lsst::meas::algorithms::shapelet::Ellipse::crudeMeasure(), and lsst::meas::algorithms::shapelet::Ellipse::findRoundFrame().
bool lsst::meas::algorithms::shapelet::NLSolver::solve (DVector & x, DVector & f) const virtual
Reimplemented in lsst::meas::algorithms::shapelet::EllipseSolver3.
References dbg.
Referenced by lsst::meas::algorithms::shapelet::Ellipse::crudeMeasure(), and lsst::meas::algorithms::shapelet::EllipseSolver3::solve().
bool lsst::meas::algorithms::shapelet::NLSolver::testJ (const DVector & x, DVector & f, std::ostream * os = 0, double relerr = 0.) const virtual
Reimplemented in lsst::meas::algorithms::shapelet::EllipseSolver3.
References calculateF(), calculateJ(), and TMV_maxAbsElement.
Referenced by lsst::meas::algorithms::shapelet::EllipseSolver3::testJ().
virtual void lsst::meas::algorithms::shapelet::NLSolver::useCholesky () inline virtual
virtual void lsst::meas::algorithms::shapelet::NLSolver::useDirectH () inline virtual
virtual void lsst::meas::algorithms::shapelet::NLSolver::useDogleg () inline virtual
Referenced by lsst::meas::algorithms::shapelet::Ellipse::findRoundFrame().
virtual void lsst::meas::algorithms::shapelet::NLSolver::useExtraVerboseOutput () inline virtual
virtual void lsst::meas::algorithms::shapelet::NLSolver::useHybrid () inline virtual
Referenced by lsst::meas::algorithms::shapelet::Ellipse::crudeMeasure(), and lsst::meas::algorithms::shapelet::Ellipse::findRoundFrame().
virtual void lsst::meas::algorithms::shapelet::NLSolver::useSVD () inline virtual
Referenced by lsst::meas::algorithms::shapelet::EllipseSolver3::dontZeroB11(), and lsst::meas::algorithms::shapelet::Ellipse::findRoundFrame().
virtual void lsst::meas::algorithms::shapelet::NLSolver::useVerboseOutput () inline virtual
Referenced by lsst::meas::algorithms::shapelet::Ellipse::findRoundFrame().
The documentation for this class was generated from the following files:
include/lsst/meas/algorithms/shapelet/NLSolver.h
src/shapelet/NLSolver.cc