lsst.meas.algorithms: lsst::meas::algorithms::shapelet::EllipseSolver3 Class Reference
lsst::meas::algorithms::shapelet::EllipseSolver3 Class Reference
#include <EllipseSolver.h>
Classes
struct ESImpl3
Public Member Functions
EllipseSolver3 (const BVec &b0, int order, bool fixcen=false, bool fixgam=false, bool fixmu=false)
~EllipseSolver3 ()
void calculateF (const DVector &x, DVector &f) const
void calculateJ (const DVector &x, const DVector &f, DMatrix &df) const
void useNumericJ ()
void dontZeroB11 ()
void getCovariance (DMatrix &cov) const
void getInverseCovariance (DMatrix &invcov) const
void callF (const DVector &x, DVector &f) const
bool solve (DVector &x, DVector &f) const
bool testJ (const DVector &x, DVector &f, std::ostream *os=0, double relerr=0.) const
Public Member Functions inherited from lsst::meas::algorithms::shapelet::NLSolver
NLSolver ()
virtual ~NLSolver ()
virtual void useHybrid ()
virtual void useDogleg ()
virtual void setFTol (double fTol)
virtual void setGTol (double gTol)
virtual void setTol (double fTol, double gTol)
virtual void setMinStep (double minStep)
virtual void setMaxIter (int maxIter)
virtual void setTau (double tau)
virtual void setDelta0 (double delta0)
virtual double getFTol ()
virtual double getGTol ()
virtual double getMinStep ()
virtual int getMaxIter ()
virtual double getTau ()
virtual double getDelta0 ()
virtual void setOutput (std::ostream &os)
virtual void useVerboseOutput ()
virtual void useExtraVerboseOutput ()
virtual void noUseVerboseOutput ()
virtual void useDirectH ()
virtual void useSVD ()
virtual void useCholesky ()
virtual void noUseDirectH ()
virtual void noUseSVD ()
virtual void noUseCholesky ()
Constructor & Destructor Documentation
lsst::meas::algorithms::shapelet::EllipseSolver3::EllipseSolver3 (const BVec & b0, int order, bool fixcen = false, bool fixgam = false, bool fixmu = false)
lsst::meas::algorithms::shapelet::EllipseSolver3::~EllipseSolver3 ()
Member Function Documentation
void lsst::meas::algorithms::shapelet::EllipseSolver3::calculateF (const DVector & x, DVector & f) const virtual
Implements lsst::meas::algorithms::shapelet::NLSolver.
References lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::calculateF().
Referenced by callF().
void lsst::meas::algorithms::shapelet::EllipseSolver3::calculateJ (const DVector & x, const DVector & f, DMatrix & df) const virtual
Reimplemented from lsst::meas::algorithms::shapelet::NLSolver.
References lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::calculateJ(), lsst::meas::algorithms::shapelet::NLSolver::calculateJ(), and lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::numeric_j.
void lsst::meas::algorithms::shapelet::EllipseSolver3::callF (const DVector & x, DVector & f) const
References Assert, calculateF(), EIGEN_Transpose, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::f_short, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::fixcen, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::fixg1, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::fixg2, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::fixgam, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::fixm, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::fixmu, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::fixuc, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::fixvc, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::U, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::x_short, and lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::xinit.
void lsst::meas::algorithms::shapelet::EllipseSolver3::dontZeroB11 ()
References lsst::meas::algorithms::shapelet::NLSolver::useSVD(), and lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::zerob11.
Referenced by lsst::meas::algorithms::shapelet::Ellipse::findRoundFrame().
void lsst::meas::algorithms::shapelet::EllipseSolver3::getCovariance (DMatrix & cov) const virtual
Reimplemented from lsst::meas::algorithms::shapelet::NLSolver.
References dbg, lsst::meas::algorithms::shapelet::NLSolver::getCovariance(), lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::U, and lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::x_short.
Referenced by lsst::meas::algorithms::shapelet::Ellipse::findRoundFrame().
void lsst::meas::algorithms::shapelet::EllipseSolver3::getInverseCovariance (DMatrix & invcov) const virtual
Reimplemented from lsst::meas::algorithms::shapelet::NLSolver.
References dbg, lsst::meas::algorithms::shapelet::NLSolver::getInverseCovariance(), lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::U, and lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::x_short.
bool lsst::meas::algorithms::shapelet::EllipseSolver3::solve (DVector & x, DVector & f) const virtual
Reimplemented from lsst::meas::algorithms::shapelet::NLSolver.
References Assert, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::bx, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::bxorder, lsst::meas::algorithms::shapelet::calculateGTransform(), lsst::meas::algorithms::shapelet::calculateMuTransform(), lsst::meas::algorithms::shapelet::calculateZTransform(), lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::Daug, EIGEN_Transpose, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::f_short, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::fixcen, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::fixg1, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::fixg2, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::fixgam, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::fixm, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::fixmu, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::fixuc, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::fixvc, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::Saug, lsst::meas::algorithms::shapelet::NLSolver::solve(), lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::Taug, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::U, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::x_short, xdbg, and lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::xinit.
Referenced by lsst::meas::algorithms::shapelet::Ellipse::findRoundFrame().
bool lsst::meas::algorithms::shapelet::EllipseSolver3::testJ (const DVector & x, DVector & f, std::ostream * os = 0, double relerr = 0.) const virtual
Reimplemented from lsst::meas::algorithms::shapelet::NLSolver.
References Assert, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::f_short, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::fixcen, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::fixg1, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::fixg2, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::fixgam, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::fixm, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::fixmu, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::fixuc, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::fixvc, lsst::meas::algorithms::shapelet::NLSolver::testJ(), lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::U, lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::x_short, and lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::xinit.
void lsst::meas::algorithms::shapelet::EllipseSolver3::useNumericJ ()
References lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::numeric_j.
The documentation for this class was generated from the following files:
include/lsst/meas/algorithms/shapelet/EllipseSolver.h
src/shapelet/EllipseSolver.cc