lsst.meas.algorithms: lsst::meas::algorithms::ImagePsf Class Reference
lsst::meas::algorithms::ImagePsf Class Reference
An intermediate base class for Psfs that use an image representation.
#include <ImagePsf.h>
Protected Member Functions
ImagePsf (bool isFixed=false)
virtual double doComputeApertureFlux (double radius, afw::geom::Point2D const &position, afw::image::Color const &color) const
virtual
afw::geom::ellipses::Quadrupole doComputeShape (afw::geom::Point2D const &position, afw::image::Color const &color) const
Protected Member Functions inherited from lsst::afw::detection::Psf
Psf (bool isFixed=false)
virtual std::string getPersistenceName () const
virtual std::string getPythonModule () const
virtual void write (OutputArchiveHandle &handle) const
Persistable ()
Persistable (Persistable const &other)
void operator= (Persistable const &other)
Protected Member Functions inherited from lsst::afw::table::io::Persistable
virtual void write (OutputArchiveHandle &handle) const
Persistable ()
Persistable (Persistable const &other)
void operator= (Persistable const &other)
Additional Inherited Members
Public Types inherited from lsst::afw::detection::Psf
enum ImageOwnerEnum
typedef boost::shared_ptr< Psf > Ptr
typedef boost::shared_ptr
< const Psf > ConstPtr
typedef math::Kernel::Pixel Pixel
typedef image::Image< Pixel > Image
Public Member Functions inherited from lsst::afw::detection::Psf
virtual ~Psf ()
virtual boost::shared_ptr< Psf > clone () const =0
boost::shared_ptr< Image > computeImage (geom::Point2D position=makeNullPoint(), image::Color color=image::Color(), ImageOwnerEnum owner=COPY) const
boost::shared_ptr< Image > computeKernelImage (geom::Point2D position=makeNullPoint(), image::Color color=image::Color(), ImageOwnerEnum owner=COPY) const
double computePeak (geom::Point2D position=makeNullPoint(), image::Color color=image::Color()) const
double computeApertureFlux (double radius, geom::Point2D position=makeNullPoint(), image::Color color=image::Color()) const
geom::ellipses::Quadrupole computeShape (geom::Point2D position=makeNullPoint(), image::Color color=image::Color()) const
boost::shared_ptr
< math::Kernel const > getLocalKernel (geom::Point2D position=makeNullPoint(), image::Color color=image::Color()) const
image::Color getAverageColor () const
virtual geom::Point2D getAveragePosition () const
void writeFits (std::string const &fileName, std::string const &mode="w") const
void writeFits (fits::MemFileManager &manager, std::string const &mode="w") const
void writeFits (fits::Fits &fitsfile) const
virtual bool isPersistable () const
virtual ~Persistable ()
Static Public Member Functions inherited from lsst::afw::table::io::PersistableFacade< ImagePsf >
static boost::shared_ptr
< ImagePsf > readFits (fits::Fits &fitsfile)
static boost::shared_ptr
< ImagePsf > readFits (std::string const &fileName, int hdu=0)
static boost::shared_ptr
< ImagePsf > readFits (fits::MemFileManager &manager, int hdu=0)
Static Public Member Functions inherited from lsst::afw::detection::Psf
static boost::shared_ptr< Image > recenterKernelImage (boost::shared_ptr< Image > im, geom::Point2D const &position, std::string const &warpAlgorithm="lanczos5", unsigned int warpBuffer=5)
static boost::shared_ptr< Psf > readFits (fits::Fits &fitsfile)
static boost::shared_ptr< Psf > readFits (std::string const &fileName, int hdu=0)
static boost::shared_ptr< Psf > readFits (fits::MemFileManager &manager, int hdu=0)
Public Attributes inherited from lsst::afw::detection::Psf
COPY
INTERNAL
Protected Types inherited from lsst::afw::detection::Psf
typedef io::OutputArchiveHandle OutputArchiveHandle
Detailed Description
An intermediate base class for Psfs that use an image representation.
ImagePsf exists only to provide implementations of doComputeApertureFlux and doComputeShape for its derived classes. These implementations use the SincFlux and SdssShape algorithms defined in meas_algorithms, and hence could not be included with the Psf base class in afw.
Constructor & Destructor Documentation
lsst::meas::algorithms::ImagePsf::ImagePsf (bool isFixed = false) inline explicit protected
Member Function Documentation
double lsst::meas::algorithms::ImagePsf::doComputeApertureFlux (double radius, afw::geom::Point2D const & position, afw::image::Color const & color) const protected virtual
References lsst::meas::algorithms::photometry::calculateSincApertureFlux(), lsst::afw::detection::Psf::computeKernelImage(), and lsst::afw::detection::Psf::INTERNAL.
afw::geom::ellipses::Quadrupole lsst::meas::algorithms::ImagePsf::doComputeShape (afw::geom::Point2D const & position, afw::image::Color const & color) const protected virtual
References lsst::afw::detection::Psf::computeKernelImage(), lsst::meas::algorithms::detail::getAdaptiveMoments(), lsst::meas::algorithms::detail::SdssShapeImpl::getIxx(), lsst::meas::algorithms::detail::SdssShapeImpl::getIxy(), lsst::meas::algorithms::detail::SdssShapeImpl::getIyy(), lsst::afw::detection::Psf::INTERNAL, and PTR.
The documentation for this class was generated from the following files:
include/lsst/meas/algorithms/ImagePsf.h
src/ImagePsf.cc