lsst.meas.algorithms: lsst::meas::algorithms::shapelet::Constant2D Class Reference
lsst::meas::algorithms::shapelet::Constant2D Class Reference
#include <Function2D.h>
Public Member Functions
Constant2D ()
Constant2D (const Constant2D &rhs)
Constant2D (double value)
Constant2D (std::istream &fin)
virtual ~Constant2D ()
virtual double operator() (double, double) const
virtual void write (std::ostream &fout) const
virtual std::auto_ptr< Function2D > dFdX () const
virtual std::auto_ptr< Function2D > dFdY () const
std::auto_ptr< Function2D > copy () const
virtual void addLinear (double a, double b, double c)
virtual void linearPreTransform (double, double, double, double, double, double)
virtual void operator+= (const Function2D &rhs)
virtual void setFunction (int, int, const DVector &fVect)
Public Member Functions inherited from lsst::meas::algorithms::shapelet::Function2D
Function2D ()
Function2D (int xo, int yo)
Function2D (int xo, int yo, const DMatrix &c)
Function2D (const Function2D &rhs)
virtual ~Function2D ()
virtual std::auto_ptr< Function2D > conj () const
virtual void operator*= (double scale)
double operator() (const Position &p) const
virtual void setTo (double value)
bool isNonZero () const
int getXOrder () const
int getYOrder () const
const DMatrix & getCoeffs () const
virtual void simpleFit (int order, const std::vector< Position > &pos, const std::vector< double > &v, const std::vector< bool > &shouldUse, const std::vector< double > *sigList=0, double *chisqOut=0, int *dofOut=0, DMatrix *cov=0)
virtual void outlierFit (int order, double nsig, const std::vector< Position > &pos, const std::vector< double > &v, std::vector< bool > *shouldUse, const std::vector< double > *sigList=0, double *chisqout=0, int *dofout=0, DMatrix *cov=0)
virtual void orderFit (int maxOrder, double equivProb, const std::vector< Position > &pos, const std::vector< double > &v, const std::vector< bool > &shouldUse, const std::vector< double > *sigList=0, double *chisqout=0, int *dofout=0, DMatrix *cov=0)
virtual void linearTransform (double a, double b, double c, const Function2D &f, const Function2D &g)
virtual void linearTransform (double a, double b, const Function2D &f)
Additional Inherited Members
Static Public Member Functions inherited from lsst::meas::algorithms::shapelet::Function2D
static std::auto_ptr< Function2D > read (std::istream &fin)
Protected Attributes inherited from lsst::meas::algorithms::shapelet::Function2D
int _xOrder
int _yOrder
std::auto_ptr< DMatrix > _coeffs
Constructor & Destructor Documentation
lsst::meas::algorithms::shapelet::Constant2D::Constant2D () inline
Referenced by copy(), dFdX(), and dFdY().
lsst::meas::algorithms::shapelet::Constant2D::Constant2D (const Constant2D & rhs) inline
lsst::meas::algorithms::shapelet::Constant2D::Constant2D (double value) inline
References lsst::meas::algorithms::shapelet::Function2D::setTo().
lsst::meas::algorithms::shapelet::Constant2D::Constant2D (std::istream & fin)
References lsst::meas::algorithms::shapelet::Function2D::_coeffs.
virtual lsst::meas::algorithms::shapelet::Constant2D::~Constant2D () inline virtual
Member Function Documentation
virtual void lsst::meas::algorithms::shapelet::Constant2D::addLinear (double a, double b, double c) inline virtual
Implements lsst::meas::algorithms::shapelet::Function2D.
References lsst::meas::algorithms::shapelet::Function2D::_coeffs, and Assert.
std::auto_ptr<Function2D> lsst::meas::algorithms::shapelet::Constant2D::copy () const inline virtual
Implements lsst::meas::algorithms::shapelet::Function2D.
References Constant2D().
virtual std::auto_ptr<Function2D> lsst::meas::algorithms::shapelet::Constant2D::dFdX () const inline virtual
Implements lsst::meas::algorithms::shapelet::Function2D.
References Constant2D().
virtual std::auto_ptr<Function2D> lsst::meas::algorithms::shapelet::Constant2D::dFdY () const inline virtual
Implements lsst::meas::algorithms::shapelet::Function2D.
References Constant2D().
virtual void lsst::meas::algorithms::shapelet::Constant2D::linearPreTransform (double , double , double , double , double , double) inline virtual
Implements lsst::meas::algorithms::shapelet::Function2D.
References Assert.
virtual double lsst::meas::algorithms::shapelet::Constant2D::operator() (double , double) const inline virtual
Reimplemented from lsst::meas::algorithms::shapelet::Function2D.
References lsst::meas::algorithms::shapelet::Function2D::_coeffs.
void lsst::meas::algorithms::shapelet::Constant2D::operator+= (const Function2D & rhs) virtual
Implements lsst::meas::algorithms::shapelet::Function2D.
References lsst::meas::algorithms::shapelet::Function2D::_coeffs, and Assert.
virtual void lsst::meas::algorithms::shapelet::Constant2D::setFunction (int , int , const DVector & fVect) inline virtual
Implements lsst::meas::algorithms::shapelet::Function2D.
References lsst::meas::algorithms::shapelet::Function2D::_coeffs, lsst::meas::algorithms::shapelet::Function2D::_xOrder, lsst::meas::algorithms::shapelet::Function2D::_yOrder, and Assert.
void lsst::meas::algorithms::shapelet::Constant2D::write (std::ostream & fout) const virtual
Implements lsst::meas::algorithms::shapelet::Function2D.
The documentation for this class was generated from the following files:
include/lsst/meas/algorithms/shapelet/Function2D.h
src/shapelet/Function2D.cc