lsst.meas.algorithms: lsst::meas::algorithms::ShapeletInterpolationImpl Class Reference
lsst::meas::algorithms::ShapeletInterpolationImpl Class Reference
Public Types
typedef float PixelT
typedef lsst::pex::policy::Policy Policy
typedef
lsst::afw::math::SpatialCellSet SpatialCellSet
typedef
lsst::afw::image::Exposure
< PixelT > Exposure
typedef lsst::afw::geom::PointD PointD
typedef shapelet::FittedPsf FittedPsf
Public Member Functions
ShapeletInterpolationImpl (const Policy &policy)
int getOrder () const
int getFitOrder () const
double getSigma () const
int getSize () const
int getFitSize () const
void setSigma (double sigma)
void calculate (SpatialCellSet::Ptr cellSet, const Exposure &exposure)
Shapelet::ConstPtr interpolate (double x, double y)
double interpolateSingleElement (double x, double y, int i)
Member Typedef Documentation
typedef lsst::afw::image::Exposure<PixelT> lsst::meas::algorithms::ShapeletInterpolationImpl::Exposure
typedef shapelet::FittedPsf lsst::meas::algorithms::ShapeletInterpolationImpl::FittedPsf
typedef float lsst::meas::algorithms::ShapeletInterpolationImpl::PixelT
typedef lsst::afw::geom::PointD lsst::meas::algorithms::ShapeletInterpolationImpl::PointD
typedef lsst::pex::policy::Policy lsst::meas::algorithms::ShapeletInterpolationImpl::Policy
typedef lsst::afw::math::SpatialCellSet lsst::meas::algorithms::ShapeletInterpolationImpl::SpatialCellSet
Constructor & Destructor Documentation
lsst::meas::algorithms::ShapeletInterpolationImpl::ShapeletInterpolationImpl (const Policy & policy) inline
References lsst::pex::policy::Policy::getDouble(), and lsst::pex::policy::Policy::getInt().
Member Function Documentation
void lsst::meas::algorithms::ShapeletInterpolationImpl::calculate (SpatialCellSet::Ptr cellSet, const Exposure & exposure) inline
Referenced by lsst::meas::algorithms::ShapeletInterpolation::calculate().
int lsst::meas::algorithms::ShapeletInterpolationImpl::getFitOrder () const inline
Referenced by lsst::meas::algorithms::ShapeletInterpolation::getFitOrder(), and getFitSize().
int lsst::meas::algorithms::ShapeletInterpolationImpl::getFitSize () const inline
References getFitOrder().
Referenced by lsst::meas::algorithms::ShapeletInterpolation::getFitSize().
int lsst::meas::algorithms::ShapeletInterpolationImpl::getOrder () const inline
Referenced by lsst::meas::algorithms::ShapeletInterpolation::getOrder(), getSize(), and interpolate().
double lsst::meas::algorithms::ShapeletInterpolationImpl::getSigma () const inline
Referenced by lsst::meas::algorithms::ShapeletInterpolation::getSigma(), and interpolate().
int lsst::meas::algorithms::ShapeletInterpolationImpl::getSize () const inline
References getOrder().
Referenced by lsst::meas::algorithms::ShapeletInterpolation::getSize().
Shapelet::ConstPtr lsst::meas::algorithms::ShapeletInterpolationImpl::interpolate (double x, double y) inline
References b, getOrder(), and getSigma().
Referenced by lsst::meas::algorithms::ShapeletInterpolation::interpolate().
double lsst::meas::algorithms::ShapeletInterpolationImpl::interpolateSingleElement (double x, double y, int i) inline
Referenced by lsst::meas::algorithms::ShapeletInterpolation::interpolateSingleElement().
void lsst::meas::algorithms::ShapeletInterpolationImpl::setSigma (double sigma) inline
Referenced by lsst::meas::algorithms::ShapeletInterpolation::setSigma().
The documentation for this class was generated from the following file:
src/ShapeletInterpolation.cc