lsst.meas.algorithms: lsst::meas::algorithms::CoaddPsf Class Reference
lsst::meas::algorithms::CoaddPsf Class Reference
CoaddPsf is the Psf derived to be used for non-PSF-matched Coadd images.
#include <CoaddPsf.h>
Classes
class Factory
Public Member Functions
CoaddPsf (afw::table::ExposureCatalog const &catalog, afw::image::Wcs const &coaddWcs, std::string const &weightFieldName="weight", std::string const &kernelName="lanczos3", unsigned int cache=10000)
Main constructors for CoaddPsf.
virtual boost::shared_ptr
< afw::detection::Psf > clone () const
Polymorphic deep copy. Usually unnecessary, as Psfs are immutable.
virtual afw::geom::Point2D getAveragePosition () const
Return the average of the positions of the stars that went into this Psf.
boost::shared_ptr
< afw::image::Wcs const > getCoaddWcs ()
Return the Wcs of the coadd (defines the coordinate system of the Psf).
int getComponentCount () const
Return the number of component Psfs in this CoaddPsf.
boost::shared_ptr
< afw::detection::Psf const > getPsf (int index)
Return the Psf of the component image at index.
boost::shared_ptr
< afw::image::Wcs const > getWcs (int index)
Return the Wcs of the component image at index.
double getWeight (int index)
Return the weight of the component image at index.
afw::table::RecordId getId (int index)
Return the exposure ID of the component image at index.
afw::geom::Box2I getBBox (int index)
Return the bounding box (in component image Pixel coordinates) of the component image at index.
virtual bool isPersistable () const
Return true if the CoaddPsf persistable (always true).
Protected Member Functions
boost::shared_ptr
< afw::detection::Psf::Image > doComputeKernelImage (afw::geom::Point2D const &ccdXY, afw::image::Color const &color) const
virtual std::string getPersistenceName () const
virtual std::string getPythonModule () const
virtual void write (OutputArchiveHandle &handle) const
CoaddPsf (afw::table::ExposureCatalog const &catalog, std::string const &kernelName="lanczos3", unsigned int cache=10000)
Protected Member Functions inherited from lsst::meas::algorithms::ImagePsf
ImagePsf (bool isFixed=false)
virtual double doComputeApertureFlux (double radius, afw::geom::Point2D const &position, afw::image::Color const &color) const
virtual
afw::geom::ellipses::Quadrupole doComputeShape (afw::geom::Point2D const &position, afw::image::Color const &color) const
Protected Member Functions inherited from lsst::afw::detection::Psf
Psf (bool isFixed=false)
Persistable ()
Persistable (Persistable const &other)
void operator= (Persistable const &other)
Protected Member Functions inherited from lsst::afw::table::io::Persistable
virtual void write (OutputArchiveHandle &handle) const
Persistable ()
Persistable (Persistable const &other)
void operator= (Persistable const &other)
Additional Inherited Members
Public Types inherited from lsst::afw::detection::Psf
enum ImageOwnerEnum
typedef boost::shared_ptr< Psf > Ptr
typedef boost::shared_ptr
< const Psf > ConstPtr
typedef math::Kernel::Pixel Pixel
typedef image::Image< Pixel > Image
Static Public Member Functions inherited from lsst::afw::table::io::PersistableFacade< CoaddPsf >
static boost::shared_ptr
< CoaddPsf > readFits (fits::Fits &fitsfile)
static boost::shared_ptr
< CoaddPsf > readFits (std::string const &fileName, int hdu=0)
static boost::shared_ptr
< CoaddPsf > readFits (fits::MemFileManager &manager, int hdu=0)
Static Public Member Functions inherited from lsst::afw::table::io::PersistableFacade< ImagePsf >
static boost::shared_ptr
< ImagePsf > readFits (fits::Fits &fitsfile)
static boost::shared_ptr
< ImagePsf > readFits (std::string const &fileName, int hdu=0)
static boost::shared_ptr
< ImagePsf > readFits (fits::MemFileManager &manager, int hdu=0)
Static Public Member Functions inherited from lsst::afw::detection::Psf
static boost::shared_ptr< Image > recenterKernelImage (boost::shared_ptr< Image > im, geom::Point2D const &position, std::string const &warpAlgorithm="lanczos5", unsigned int warpBuffer=5)
static boost::shared_ptr< Psf > readFits (fits::Fits &fitsfile)
static boost::shared_ptr< Psf > readFits (std::string const &fileName, int hdu=0)
static boost::shared_ptr< Psf > readFits (fits::MemFileManager &manager, int hdu=0)
Public Attributes inherited from lsst::afw::detection::Psf
COPY
INTERNAL
Protected Types inherited from lsst::afw::detection::Psf
typedef io::OutputArchiveHandle OutputArchiveHandle
Detailed Description
CoaddPsf is the Psf derived to be used for non-PSF-matched Coadd images.
It incorporates the logic of James Jee's Stackfit algorithm for estimating the Psf of coadd by coadding the images of the Psf models of each input exposure.
Constructor & Destructor Documentation
lsst::meas::algorithms::CoaddPsf::CoaddPsf (afw::table::ExposureCatalog const & catalog, afw::image::Wcs const & coaddWcs, std::string const & weightFieldName = "weight", std::string const & kernelName = "lanczos3", unsigned int cache = 10000) explicit
Main constructors for CoaddPsf.
The ExposureCatalog contains info about each visit/ccd in Coadd; this must be provided to the constructor, and cannot be changed.
Parameters
[in] catalog ExposureCatalog containing the id, bbox, wcs, psf and weight for each ccd/visit. This is usually the same catalog as the "ccds" catalog in the coadd Exposure's CoaddInputs.
[in] coaddWcs Wcs for the coadd.
[in] weightFieldName Field name that contains the weight of the exposure in the coadd; defaults to "weight".
[in] kernelName Name of warping kernel
[in] cache Warping kernel cache size
References lsst::afw::table::SchemaMapper::addMinimalSchema(), lsst::afw::image::Wcs::clone(), lsst::afw::table::ExposureTable::makeMinimalSchema(), PTR, and record.
Referenced by lsst::meas::algorithms::CoaddPsf::Factory::read().
lsst::meas::algorithms::CoaddPsf::CoaddPsf (afw::table::ExposureCatalog const & catalog, std::string const & kernelName = "lanczos3", unsigned int cache = 10000) explicit protected
Parameters
catalog Unpersisted catalog
kernelName Warping kernel name
cache Kernel cache
Member Function Documentation
boost::shared_ptr< afw::detection::Psf > lsst::meas::algorithms::CoaddPsf::clone (void) const virtual
Polymorphic deep copy. Usually unnecessary, as Psfs are immutable.
Implements lsst::afw::detection::Psf.
References PTR.
boost::shared_ptr< afw::detection::Psf::Image > lsst::meas::algorithms::CoaddPsf::doComputeKernelImage (afw::geom::Point2D const & ccdXY, afw::image::Color const & color) const protected
References lsst::meas::algorithms::addToImage(), lsst::afw::detection::Psf::computeKernelImage(), lsst::meas::algorithms::getOverallBBox(), LSST_EXCEPT, and PTR.
virtual afw::geom::Point2D lsst::meas::algorithms::CoaddPsf::getAveragePosition () const inline virtual
Return the average of the positions of the stars that went into this Psf.
For CoaddPsf, this is calculated as the weighted average of the average positions of all the component Psfs.
Reimplemented from lsst::afw::detection::Psf.
afw::geom::Box2I lsst::meas::algorithms::CoaddPsf::getBBox (int index)
Return the bounding box (in component image Pixel coordinates) of the component image at index.
References getComponentCount(), and LSST_EXCEPT.
boost::shared_ptr< afw::image::Wcs const > lsst::meas::algorithms::CoaddPsf::getCoaddWcs () inline
Return the Wcs of the coadd (defines the coordinate system of the Psf).
References PTR.
int lsst::meas::algorithms::CoaddPsf::getComponentCount () const
Return the number of component Psfs in this CoaddPsf.
getComponentCount() - get the number of component Psf's in this CoaddPsf
Referenced by getBBox(), getId(), and getWeight().
afw::table::RecordId lsst::meas::algorithms::CoaddPsf::getId (int index)
Return the exposure ID of the component image at index.
getId - get the long id of the component at position index
References getComponentCount(), and LSST_EXCEPT.
std::string lsst::meas::algorithms::CoaddPsf::getPersistenceName () const protected virtual
Reimplemented from lsst::afw::detection::Psf.
boost::shared_ptr< afw::detection::Psf const > lsst::meas::algorithms::CoaddPsf::getPsf (int index)
Return the Psf of the component image at index.
getPsf - get the Psf of the component at position index
References CONST_PTR, and LSST_EXCEPT.
std::string lsst::meas::algorithms::CoaddPsf::getPythonModule () const protected virtual
Reimplemented from lsst::afw::detection::Psf.
boost::shared_ptr< afw::image::Wcs const > lsst::meas::algorithms::CoaddPsf::getWcs (int index)
Return the Wcs of the component image at index.
getWcs - get the Wcs of the component at position index
References CONST_PTR, and LSST_EXCEPT.
double lsst::meas::algorithms::CoaddPsf::getWeight (int index)
Return the weight of the component image at index.
getWeight - get the coadd weight of the component at position index
References getComponentCount(), and LSST_EXCEPT.
virtual bool lsst::meas::algorithms::CoaddPsf::isPersistable () const inline virtual
Return true if the CoaddPsf persistable (always true).
While it's actually possible to construct a CoaddPsf that isn't persistable (because its nested Psfs and Wcss are not persistable) in artificial situations, in realistic situations it's pretty much impossible, because persistence is a necessary part of how CoaddPsfs are built. And it's simpler and much faster if we just always return true, rather than loop over the elements and check each one.
Reimplemented from lsst::afw::detection::Psf.
void lsst::meas::algorithms::CoaddPsf::write (OutputArchiveHandle & handle) const protected virtual
Reimplemented from lsst::afw::detection::Psf.
References PTR.
The documentation for this class was generated from the following files:
include/lsst/meas/algorithms/CoaddPsf.h
src/CoaddPsf.cc