lsst.meas.algorithms: lsst::meas::algorithms::shapelet::Pixel Class Reference
lsst::meas::algorithms::shapelet::Pixel Class Reference
#include <Pixel.h>
Public Member Functions
Pixel ()
Pixel (double u, double v, double flux, double inverseSigma)
Pixel (std::complex< double > z, double flux, double inverseSigma)
~Pixel ()
std::complex< double > getPos () const
double getFlux () const
double getInverseSigma () const
void setPos (const std::complex< double > &pos)
void setFlux (const double flux)
void setInverseSigma (const double inverseSigma)
Constructor & Destructor Documentation
lsst::meas::algorithms::shapelet::Pixel::Pixel () inline
lsst::meas::algorithms::shapelet::Pixel::Pixel (double u, double v, double flux, double inverseSigma) inline
lsst::meas::algorithms::shapelet::Pixel::Pixel (std::complex< double > z, double flux, double inverseSigma) inline
lsst::meas::algorithms::shapelet::Pixel::~Pixel () inline
Member Function Documentation
double lsst::meas::algorithms::shapelet::Pixel::getFlux () const inline
Referenced by lsst::meas::algorithms::shapelet::getSubPixList().
double lsst::meas::algorithms::shapelet::Pixel::getInverseSigma () const inline
std::complex<double> lsst::meas::algorithms::shapelet::Pixel::getPos () const inline
Referenced by lsst::meas::algorithms::shapelet::getSubPixList(), and lsst::meas::algorithms::shapelet::PixelListSorter::operator()().
void lsst::meas::algorithms::shapelet::Pixel::setFlux (const double flux) inline
void lsst::meas::algorithms::shapelet::Pixel::setInverseSigma (const double inverseSigma) inline
void lsst::meas::algorithms::shapelet::Pixel::setPos (const std::complex< double > & pos) inline
Referenced by lsst::meas::algorithms::shapelet::getSubPixList().
The documentation for this class was generated from the following file:
include/lsst/meas/algorithms/shapelet/Pixel.h