lsst.meas.algorithms: lsst.meas.algorithms.detection.SourceDetectionTask Class Reference
lsst.meas.algorithms.detection.SourceDetectionTask Class Reference
Public Member Functions
def __init__
def makeSourceCatalog
def detectFootprints
def thresholdImage
Static Public Member Functions
def setEdgeBits
Public Attributes
negativeFlagKey
Static Public Attributes
ConfigClass SourceDetectionConfig
Detailed Description
Detect positive and negative sources on an exposure and return a new SourceCatalog.
Constructor & Destructor Documentation
def lsst.meas.algorithms.detection.SourceDetectionTask.__init__ (self, schema = None, kwds)
Create the detection task.  Most arguments are simply passed onto pipe_base.Task.
If schema is not None, it will be used to register a 'flags.negative' flag field
that will be set for negative detections.
Member Function Documentation
def lsst.meas.algorithms.detection.SourceDetectionTask.detectFootprints (self, exposure, doSmooth = True, sigma = None, clearMask = True)
Detect footprints.
@param exposure Exposure to process; DETECTED{,_NEGATIVE} mask plane will be set in-place.
@param doSmooth if True, smooth the image before detection using a Gaussian of width sigma
@param sigma    sigma of PSF (pixels); used for smoothing and to grow detections;
    if None then measure the sigma of the PSF of the exposure
@param clearMask Clear both DETECTED and DETECTED_NEGATIVE planes before running detection
@return a lsst.pipe.base.Struct with fields:
- positive: lsst.afw.detection.FootprintSet with positive polarity footprints (may be None)
- negative: lsst.afw.detection.FootprintSet with negative polarity footprints (may be None)
- numPos: number of footprints in positive or 0 if detection polarity was negative
- numNeg: number of footprints in negative or 0 if detection polarity was positive
- background: re-estimated background.  None if reEstimateBackground==False
@raise pipe_base TaskError if sigma=None and the exposure has no PSF
References lsst::afw::math.convolve(), lsst.meas.algorithms.detection.getBackground(), lsst.meas.algorithms.detection.SourceDetectionTask.setEdgeBits(), and lsst.meas.algorithms.detection.SourceDetectionTask.thresholdImage().
Referenced by lsst.meas.algorithms.detection.SourceDetectionTask.makeSourceCatalog().
def lsst.meas.algorithms.detection.SourceDetectionTask.makeSourceCatalog (self, table, exposure, doSmooth = True, sigma = None, clearMask = True)
Run source detection and create a SourceCatalog.
To avoid dealing with sources and tables, use detectFootprints() to just get the FootprintSets.
@param table    lsst.afw.table.SourceTable object that will be used to created the SourceCatalog.
@param exposure Exposure to process; DETECTED mask plane will be set in-place.
@param doSmooth if True, smooth the image before detection using a Gaussian of width sigma
@param sigma    sigma of PSF (pixels); used for smoothing and to grow detections;
    if None then measure the sigma of the PSF of the exposure
@param clearMask Clear DETECTED{,_NEGATIVE} planes before running detection
@return a Struct with:
  sources -- an lsst.afw.table.SourceCatalog object
  fpSets --- Struct returned by detectFootprints
@raise pipe_base TaskError if sigma=None, doSmooth=True and the exposure has no PSF
References lsst.meas.algorithms.detection.SourceDetectionTask.detectFootprints(), and lsst.meas.algorithms.detection.SourceDetectionTask.negativeFlagKey.
def lsst.meas.algorithms.detection.SourceDetectionTask.setEdgeBits (maskedImage, goodBBox, edgeBitmask) static
Set the edgeBitmask bits for all of maskedImage outside goodBBox
Referenced by lsst.meas.algorithms.detection.SourceDetectionTask.detectFootprints().
def lsst.meas.algorithms.detection.SourceDetectionTask.thresholdImage (self, image, thresholdParity, maskName = "DETECTED")
Threshold the convolved image, returning a FootprintSet.
Helper function for detect().
@param image The (optionally convolved) MaskedImage to threshold
@param thresholdParity Parity of threshold
@param maskName Name of mask to set
@return FootprintSet
References lsst::afw::detection.createThreshold().
Referenced by lsst.meas.algorithms.detection.SourceDetectionTask.detectFootprints().
Member Data Documentation
lsst.meas.algorithms.detection.SourceDetectionTask.ConfigClass SourceDetectionConfig static
lsst.meas.algorithms.detection.SourceDetectionTask.negativeFlagKey
Referenced by lsst.meas.algorithms.detection.SourceDetectionTask.makeSourceCatalog().
The documentation for this class was generated from the following file:
python/lsst/meas/algorithms/detection.py