lsst.meas.algorithms: lsst::meas::algorithms::AlgorithmControl Class Reference
lsst::meas::algorithms::AlgorithmControl Class Reference abstract
Base class for measurement algorithm control objects.
#include <Algorithm.h>
Public Member Functions
LSST_CONTROL_FIELD (priority, double,"Parameter that sets the sort order for algorithms; lower numbers go first. ""Typically, priority=0 for centroids, 1 for shapes, and 2 for fluxes.")
boost::shared_ptr
< AlgorithmControl > clone () const
boost::shared_ptr< Algorithm > makeAlgorithm (afw::table::Schema &schema, boost::shared_ptr< daf::base::PropertyList > const &metadata=boost::shared_ptr< daf::base::PropertyList >(), AlgorithmMap const &others=AlgorithmMap()) const
Construct a new algorithm configured with *this.
virtual ~AlgorithmControl ()
Public Attributes
std::string name
Name of the algorithm.
Protected Member Functions
virtual boost::shared_ptr
< AlgorithmControl > _clone () const =0
virtual boost::shared_ptr
< Algorithm > _makeAlgorithm (afw::table::Schema &schema, boost::shared_ptr< daf::base::PropertyList > const &metadata) const
virtual boost::shared_ptr
< Algorithm > _makeAlgorithm (afw::table::Schema &schema, boost::shared_ptr< daf::base::PropertyList > const &metadata, AlgorithmMap const &others) const
AlgorithmControl (std::string const &name_, double priority_)
Detailed Description
Base class for measurement algorithm control objects.
This is a polymorphic class hierarchy because control objects are also factories for algorithms - but this is considered an implementation detail, and only matters to algorithm writers, who must implement the protected algorithm factory functions. The advantage of this approach is that we don't have to SWIG all the algorithm classes.
Constructor & Destructor Documentation
virtual lsst::meas::algorithms::AlgorithmControl::~AlgorithmControl () inline virtual
lsst::meas::algorithms::AlgorithmControl::AlgorithmControl (std::string const & name_, double priority_) inline explicit protected
Member Function Documentation
virtual boost::shared_ptr< AlgorithmControl > lsst::meas::algorithms::AlgorithmControl::_clone () const protected pure virtual
Referenced by lsst::meas::algorithms::CentroidControl::clone(), lsst::meas::algorithms::ShapeControl::clone(), and lsst::meas::algorithms::FluxControl::clone().
virtual boost::shared_ptr< Algorithm > lsst::meas::algorithms::AlgorithmControl::_makeAlgorithm (afw::table::Schema & schema, boost::shared_ptr< daf::base::PropertyList > const & metadata) const inline protected virtual
References LSST_EXCEPT.
Referenced by lsst::meas::algorithms::CentroidControl::makeAlgorithm(), lsst::meas::algorithms::ShapeControl::makeAlgorithm(), and lsst::meas::algorithms::FluxControl::makeAlgorithm().
virtual boost::shared_ptr< Algorithm > lsst::meas::algorithms::AlgorithmControl::_makeAlgorithm (afw::table::Schema & schema, boost::shared_ptr< daf::base::PropertyList > const & metadata, AlgorithmMap const & others) const inline protected virtual
References PTR.
boost::shared_ptr< AlgorithmControl > lsst::meas::algorithms::AlgorithmControl::clone (void) const inline
References PTR.
lsst::meas::algorithms::AlgorithmControl::LSST_CONTROL_FIELD (priority , double , "Parameter that sets the sort order for algorithms; lower numbers go first. "" Typically, priority = 0 for centroids, 1 for shapes, and 2 for fluxes.")
boost::shared_ptr< Algorithm > lsst::meas::algorithms::AlgorithmControl::makeAlgorithm (afw::table::Schema & schema, boost::shared_ptr< daf::base::PropertyList > const & metadata = boost::shared_ptr< daf::base::PropertyList >(), AlgorithmMap const & others = AlgorithmMap()) const inline
Construct a new algorithm configured with *this.
Parameters
[in,out] schema A Schema the algorithm should register its outputs with and use to obtain the keys for any input fields for other algorithms it depends on.
[in,out] metadata Flexible metadata for additional descriptive information the algorithm might want to pass onto a source table. May be null.
[in] others A map of Algorithm objects for measurement algorithms that have already been registered with the schema. Only algorithms with priority < this->priority will be present.
References PTR.
Member Data Documentation
std::string lsst::meas::algorithms::AlgorithmControl::name
Name of the algorithm.
We don't want this to be a Field in the corresponding Python Config class, because then it would be very confusing to allow it to be the different from the name in the config registry. Instead, we'll make the registry set the name on the control object when it makes it.
Referenced by lsst.meas.algorithms.algorithmRegistry.AlgorithmRegistry.Configurable::__call__().
The documentation for this class was generated from the following file:
include/lsst/meas/algorithms/Algorithm.h