lsst.meas.algorithms: lsst::meas::algorithms::detail::SdssShapeImpl Class Reference
lsst::meas::algorithms::detail::SdssShapeImpl Class Reference
#include <SdssShape.h>
Public Types
enum Flag {
UNWEIGHTED_BAD =0, UNWEIGHTED, SHIFT, MAXITER,
N_FLAGS
}
typedef Eigen::Matrix< double,
4, 4, Eigen::DontAlign > Matrix4
typedef std::bitset< N_FLAGS > FlagSet
Public Member Functions
SdssShapeImpl (double i0=NAN, double ixx=NAN, double ixy=NAN, double iyy=NAN)
SdssShapeImpl (afw::geom::Point2D const &centroid, afw::geom::ellipses::Quadrupole const &shape)
void setI0 (double i0)
double getI0 () const
double getI0Err () const
double getX () const
double getXErr () const
void setX (double const x)
double getY () const
double getYErr () const
void setY (double const y)
void setIxx (double ixx)
double getIxx () const
double getIxxErr () const
void setIxy (double ixy)
double getIxy () const
double getIxyErr () const
void setIyy (double iyy)
double getIyy () const
double getIyyErr () const
void setIxy4 (double ixy4)
double getIxy4 () const
void setFlag (Flag flag)
void resetFlag (Flag flag)
bool getFlag (Flag flag) const
void setCovar (Matrix4 covar)
const Matrix4 & getCovar () const
double getFluxScale () const
Return multiplier that transforms I0 to a total flux.
boost::shared_ptr< SdssShapeImpl > transform (lsst::afw::geom::AffineTransform const &trans) const
double getE1 () const
double getE1Err () const
double getE2 () const
double getE2Err () const
double getE1E2Err () const
double getRms () const
double getRmsErr () const
Member Typedef Documentation
typedef std::bitset<N_FLAGS> lsst::meas::algorithms::detail::SdssShapeImpl::FlagSet
typedef Eigen::Matrix<double,4,4,Eigen::DontAlign> lsst::meas::algorithms::detail::SdssShapeImpl::Matrix4
Member Enumeration Documentation
enum lsst::meas::algorithms::detail::SdssShapeImpl::Flag
Enumerator:
UNWEIGHTED_BAD
UNWEIGHTED
SHIFT
MAXITER
N_FLAGS
Constructor & Destructor Documentation
lsst::meas::algorithms::detail::SdssShapeImpl::SdssShapeImpl (double i0 = NAN, double ixx = NAN, double ixy = NAN, double iyy = NAN) inline
lsst::meas::algorithms::detail::SdssShapeImpl::SdssShapeImpl (afw::geom::Point2D const & centroid, afw::geom::ellipses::Quadrupole const & shape) inline explicit
Member Function Documentation
const Matrix4& lsst::meas::algorithms::detail::SdssShapeImpl::getCovar () const inline
double lsst::meas::algorithms::detail::SdssShapeImpl::getE1 () const
double lsst::meas::algorithms::detail::SdssShapeImpl::getE1E2Err () const
double lsst::meas::algorithms::detail::SdssShapeImpl::getE1Err () const
double lsst::meas::algorithms::detail::SdssShapeImpl::getE2 () const
double lsst::meas::algorithms::detail::SdssShapeImpl::getE2Err () const
bool lsst::meas::algorithms::detail::SdssShapeImpl::getFlag (Flag flag) const inline
Referenced by lsst::meas::algorithms::detail::getAdaptiveMoments().
double lsst::meas::algorithms::detail::SdssShapeImpl::getFluxScale () const inline
Return multiplier that transforms I0 to a total flux.
References getIxx(), getIxy(), getIyy(), and lsst::afw::geom::TWOPI.
Referenced by lsst::meas::algorithms::detail::getFixedMomentsFlux().
double lsst::meas::algorithms::detail::SdssShapeImpl::getI0 () const inline
Referenced by lsst::meas::algorithms::detail::getFixedMomentsFlux().
double lsst::meas::algorithms::detail::SdssShapeImpl::getI0Err () const inline
Referenced by lsst::meas::algorithms::detail::getFixedMomentsFlux().
double lsst::meas::algorithms::detail::SdssShapeImpl::getIxx () const inline
Referenced by lsst::meas::algorithms::ImagePsf::doComputeShape(), lsst::meas::algorithms::detail::getAdaptiveMoments(), lsst::meas::algorithms::detail::getFixedMomentsFlux(), and getFluxScale().
double lsst::meas::algorithms::detail::SdssShapeImpl::getIxxErr () const inline
double lsst::meas::algorithms::detail::SdssShapeImpl::getIxy () const inline
Referenced by lsst::meas::algorithms::ImagePsf::doComputeShape(), lsst::meas::algorithms::detail::getFixedMomentsFlux(), and getFluxScale().
double lsst::meas::algorithms::detail::SdssShapeImpl::getIxy4 () const inline
double lsst::meas::algorithms::detail::SdssShapeImpl::getIxyErr () const inline
double lsst::meas::algorithms::detail::SdssShapeImpl::getIyy () const inline
Referenced by lsst::meas::algorithms::ImagePsf::doComputeShape(), lsst::meas::algorithms::detail::getAdaptiveMoments(), lsst::meas::algorithms::detail::getFixedMomentsFlux(), and getFluxScale().
double lsst::meas::algorithms::detail::SdssShapeImpl::getIyyErr () const inline
double lsst::meas::algorithms::detail::SdssShapeImpl::getRms () const
double lsst::meas::algorithms::detail::SdssShapeImpl::getRmsErr () const
double lsst::meas::algorithms::detail::SdssShapeImpl::getX () const inline
Referenced by lsst::meas::algorithms::detail::getAdaptiveMoments().
double lsst::meas::algorithms::detail::SdssShapeImpl::getXErr () const inline
double lsst::meas::algorithms::detail::SdssShapeImpl::getY () const inline
Referenced by lsst::meas::algorithms::detail::getAdaptiveMoments().
double lsst::meas::algorithms::detail::SdssShapeImpl::getYErr () const inline
void lsst::meas::algorithms::detail::SdssShapeImpl::resetFlag (Flag flag) inline
Referenced by lsst::meas::algorithms::detail::getAdaptiveMoments().
void lsst::meas::algorithms::detail::SdssShapeImpl::setCovar (Matrix4 covar) inline
Referenced by lsst::meas::algorithms::detail::getAdaptiveMoments(), and lsst::meas::algorithms::detail::getFixedMomentsFlux().
void lsst::meas::algorithms::detail::SdssShapeImpl::setFlag (Flag flag) inline
Referenced by lsst::meas::algorithms::detail::getAdaptiveMoments().
void lsst::meas::algorithms::detail::SdssShapeImpl::setI0 (double i0) inline
Referenced by lsst::meas::algorithms::detail::getAdaptiveMoments(), and lsst::meas::algorithms::detail::getFixedMomentsFlux().
void lsst::meas::algorithms::detail::SdssShapeImpl::setIxx (double ixx) inline
Referenced by lsst::meas::algorithms::detail::getAdaptiveMoments().
void lsst::meas::algorithms::detail::SdssShapeImpl::setIxy (double ixy) inline
Referenced by lsst::meas::algorithms::detail::getAdaptiveMoments().
void lsst::meas::algorithms::detail::SdssShapeImpl::setIxy4 (double ixy4) inline
Referenced by lsst::meas::algorithms::detail::getAdaptiveMoments().
void lsst::meas::algorithms::detail::SdssShapeImpl::setIyy (double iyy) inline
Referenced by lsst::meas::algorithms::detail::getAdaptiveMoments().
void lsst::meas::algorithms::detail::SdssShapeImpl::setX (double const x) inline
Referenced by lsst::meas::algorithms::detail::getAdaptiveMoments().
void lsst::meas::algorithms::detail::SdssShapeImpl::setY (double const y) inline
Referenced by lsst::meas::algorithms::detail::getAdaptiveMoments().
boost::shared_ptr< SdssShapeImpl > lsst::meas::algorithms::detail::SdssShapeImpl::transform (lsst::afw::geom::AffineTransform const & trans) const inline
References copy(), PTR, and lsst::afw::geom::ellipses::Quadrupole::setIxx().
The documentation for this class was generated from the following file:
include/lsst/meas/algorithms/detail/SdssShape.h