lsst.meas.algorithms: lsst::meas::algorithms::shapelet::FittedPsf Class Reference
lsst::meas::algorithms::shapelet::FittedPsf Class Reference
#include <FittedPsf.h>
Public Member Functions
FittedPsf (const ConfigFile &params)
int getPsfOrder () const
int getPsfSize () const
int getFitOrder () const
int getFitSize () const
int getNpca () const
double getSigma () const
void setSigma (double sigma)
double getXMin () const
double getXMax () const
double getYMin () const
double getYMax () const
const Bounds & getBounds () const
void calculate (const std::vector< Position > &pos, const std::vector< BVec > &psf, const std::vector< double > &nu, std::vector< long > &flags)
void interpolate (Position pos, BVec &b) const
double interpolateSingleElement (Position pos, int i) const
FittedPsfAtXY operator() (Position pos) const
BVec getMean () const
Friends
class FittedPsfAtXY
Constructor & Destructor Documentation
lsst::meas::algorithms::shapelet::FittedPsf::FittedPsf (const ConfigFile & params)
Member Function Documentation
void lsst::meas::algorithms::shapelet::FittedPsf::calculate (const std::vector< Position > & pos, const std::vector< BVec > & psf, const std::vector< double > & nu, std::vector< long > & flags)
References Assert, dbg, EIGEN_asDiag, EIGEN_Transpose, getSigma(), lsst::meas::algorithms::shapelet::ConfigFile::keyExists(), lsst::meas::algorithms::shapelet::ConfigFile::read(), TMV_colRange, TMV_normSq, TMV_vview, lsst::meas::algorithms::shapelet::BVec::vec(), and xdbg.
const Bounds& lsst::meas::algorithms::shapelet::FittedPsf::getBounds () const inline
int lsst::meas::algorithms::shapelet::FittedPsf::getFitOrder () const inline
int lsst::meas::algorithms::shapelet::FittedPsf::getFitSize () const inline
BVec lsst::meas::algorithms::shapelet::FittedPsf::getMean () const
int lsst::meas::algorithms::shapelet::FittedPsf::getNpca () const inline
int lsst::meas::algorithms::shapelet::FittedPsf::getPsfOrder () const inline
Referenced by lsst::meas::algorithms::shapelet::FittedPsfAtXY::getOrder().
int lsst::meas::algorithms::shapelet::FittedPsf::getPsfSize () const inline
double lsst::meas::algorithms::shapelet::FittedPsf::getSigma () const inline
Referenced by calculate(), and lsst::meas::algorithms::shapelet::FittedPsfAtXY::getSigma().
double lsst::meas::algorithms::shapelet::FittedPsf::getXMax () const inline
References lsst::meas::algorithms::shapelet::Bounds::getXMax().
double lsst::meas::algorithms::shapelet::FittedPsf::getXMin () const inline
References lsst::meas::algorithms::shapelet::Bounds::getXMin().
double lsst::meas::algorithms::shapelet::FittedPsf::getYMax () const inline
References lsst::meas::algorithms::shapelet::Bounds::getYMax().
double lsst::meas::algorithms::shapelet::FittedPsf::getYMin () const inline
References lsst::meas::algorithms::shapelet::Bounds::getYMin().
void lsst::meas::algorithms::shapelet::FittedPsf::interpolate (Position pos, BVec & b) const inline
References Assert, lsst::meas::algorithms::shapelet::BVec::getOrder(), lsst::meas::algorithms::shapelet::BVec::setSigma(), lsst::meas::algorithms::shapelet::BVec::size(), TMV_vview, and lsst::meas::algorithms::shapelet::BVec::vec().
Referenced by lsst::meas::algorithms::shapelet::FittedPsfAtXY::assignTo().
double lsst::meas::algorithms::shapelet::FittedPsf::interpolateSingleElement (Position pos, int i) const
References EIGEN_ToScalar, and EIGEN_Transpose.
FittedPsfAtXY lsst::meas::algorithms::shapelet::FittedPsf::operator() (Position pos) const inline
References FittedPsfAtXY.
void lsst::meas::algorithms::shapelet::FittedPsf::setSigma (double sigma) inline
Friends And Related Function Documentation
friend class FittedPsfAtXY friend
Referenced by operator()().
The documentation for this class was generated from the following files:
include/lsst/meas/algorithms/shapelet/FittedPsf.h
src/shapelet/FittedPsf.cc