lsst.meas.algorithms: lsst::meas::algorithms::shapelet::FittedPsfAtXY Class Reference
lsst::meas::algorithms::shapelet::FittedPsfAtXY Class Reference
#include <FittedPsf.h>
Public Member Functions
FittedPsfAtXY (const FittedPsf &psf, Position pos)
size_t size () const
int getOrder () const
double getSigma () const
void assignTo (BVec &b) const
Public Member Functions inherited from lsst::meas::algorithms::shapelet::AssignableToBVec
virtual ~AssignableToBVec ()
Constructor & Destructor Documentation
lsst::meas::algorithms::shapelet::FittedPsfAtXY::FittedPsfAtXY (const FittedPsf & psf, Position pos) inline
Member Function Documentation
void lsst::meas::algorithms::shapelet::FittedPsfAtXY::assignTo (BVec & b) const inline virtual
Implements lsst::meas::algorithms::shapelet::AssignableToBVec.
References lsst::meas::algorithms::shapelet::FittedPsf::interpolate().
int lsst::meas::algorithms::shapelet::FittedPsfAtXY::getOrder () const inline virtual
Implements lsst::meas::algorithms::shapelet::AssignableToBVec.
References lsst::meas::algorithms::shapelet::FittedPsf::getPsfOrder().
double lsst::meas::algorithms::shapelet::FittedPsfAtXY::getSigma () const inline virtual
Implements lsst::meas::algorithms::shapelet::AssignableToBVec.
References lsst::meas::algorithms::shapelet::FittedPsf::getSigma().
size_t lsst::meas::algorithms::shapelet::FittedPsfAtXY::size () const inline
The documentation for this class was generated from the following file:
include/lsst/meas/algorithms/shapelet/FittedPsf.h