lsst.meas.algorithms: lsst::meas::algorithms::Shapelet Class Reference
lsst::meas::algorithms::Shapelet Class Reference
#include <Shapelet.h>
Public Types
typedef float PixelT
This class includes the basic functionality for shapelets.
typedef boost::shared_ptr
< Shapelet > Ptr
typedef boost::shared_ptr
< const Shapelet > ConstPtr
typedef Eigen::VectorXd ShapeletVector
typedef Eigen::MatrixXd ShapeletCovariance
typedef
lsst::afw::table::SourceRecord Source
typedef
lsst::afw::image::Exposure
< PixelT > Exposure
typedef lsst::afw::geom::PointD PointD
typedef lsst::afw::image::MaskPixel MaskPixel
Public Member Functions
Shapelet (int order, double sigma)
Basic constructor requires order and sigma.
Shapelet (int order, double sigma, const ShapeletVector &vector)
A constructor from a vector of values.
Shapelet (int order, double sigma, const ShapeletVector &vector, const ShapeletCovariance &cov)
A constructor from a vector of values, with covariance.
~Shapelet ()
Destructor needs to delete pImpl.
Shapelet (const Shapelet &rhs)
Copy constructor does a deep copy.
Shapelet & operator= (const Shapelet &rhs)
op= does a deep copy
int getOrder () const
get the order of the shapelet
double getSigma () const
get the scale size of the shapelet
int size () const
the size of the shapelet vector
const ShapeletVector & getValues () const
get the values as a vector.
bool hasCovariance () const
does the shapelet have a covariance matrix stored?
boost::shared_ptr< const
ShapeletCovariance > getCovariance () const
get the covariance matrix
void setSigma (double sigma)
set a new value of sigma
std::complex< double > getPQ (int p, int q)
Get a complex b_pq value.
double evaluateAt (const PointD &pos)
Evaluate f(x,y)
double evaluateAt (double x, double y)
bool measureFromImage (const Source &source, const PointD &pos, bool isCentroidFixed, bool isSigmaFixed, double aperture, const Exposure &exposure, const MaskPixel okmask=0)
measure shapelet decomposition of an image
Shapelet (const shapelet::BVec &bvec)
A constructor that is only used by various Shapelet implementations.
const shapelet::BVec & viewAsBVec () const
View the shapelet as a BVec.
shapelet::BVec & viewAsBVec ()
Member Typedef Documentation
typedef boost::shared_ptr<const Shapelet> lsst::meas::algorithms::Shapelet::ConstPtr
typedef lsst::afw::image::Exposure<PixelT> lsst::meas::algorithms::Shapelet::Exposure
typedef lsst::afw::image::MaskPixel lsst::meas::algorithms::Shapelet::MaskPixel
typedef float lsst::meas::algorithms::Shapelet::PixelT
This class includes the basic functionality for shapelets.
There are a few definitions of shapelets out there. This class implements the shapelets defined in Bernstein & Jarvis (2002) (where they are called the Gauss-Laguerre basis functions). These are similar to the "polar shapelets" of Massey & Refregier.
Shapelets are a complete basis set that can be used to describe any image. However, they are most useful for describing things that are intrinsically similar to a 2-d Gaussian. Since the PSF (for ground-based telescopes) is dominated by a Gaussian component, this makes them a good choice for describing the PSF.
For specificity, the basis functions we use are:
For p >= q: psi_pq(x,y,sigma) = (pi p! q!)^-1/2 z^m exp(-r^2/2) K_pq(r^2) where z = (x + Iy)/sigma m = p-q r = |z|^2 K_pq(r^2) = (-)^q q! L_q^(m) (r^2) L_q^(m)(x) are Laguerre polynomials
For any particular value of sigma, these define a complete set of basis functions.
The image is thus decomposed as:
f(x,y) = Sum_pq b_pq psi_pq(x,y)
As with any basis set, the decomposition is only exact if an infinite number of basis functions are used. We truncate the expansion at p+q <= order for some (specified) order.
typedef lsst::afw::geom::PointD lsst::meas::algorithms::Shapelet::PointD
typedef boost::shared_ptr<Shapelet> lsst::meas::algorithms::Shapelet::Ptr
typedef Eigen::MatrixXd lsst::meas::algorithms::Shapelet::ShapeletCovariance
typedef Eigen::VectorXd lsst::meas::algorithms::Shapelet::ShapeletVector
typedef lsst::afw::table::SourceRecord lsst::meas::algorithms::Shapelet::Source
Constructor & Destructor Documentation
lsst::meas::algorithms::Shapelet::Shapelet (int order, double sigma)
Basic constructor requires order and sigma.
order defines how many shapelet coefficients to measure. e.g. order = 4 includes: b00, b10, b20, b11, b30, b21, b40, b31, b22 (bii are real, the others are complex.)
sigma is the scale size of Gaussian factor in the shapelet decomposition, measured in arcsec.
Parameters
order the maximum value of p+q to measure.
sigma the scale size of the shapelet decomposition (arcsec).
lsst::meas::algorithms::Shapelet::Shapelet (int order, double sigma, const ShapeletVector & vector)
A constructor from a vector of values.
The input vector should have (order+1)*(order+2)/2 elements.
Caveat: The input vector is real, not complex. See the comment for getValues for the expected order of values.
Parameters
order the maximum value of p+q to measure.
sigma the scale size of the shapelet decomposition (arcsec).
vector the shapelet vector
lsst::meas::algorithms::Shapelet::Shapelet (int order, double sigma, const ShapeletVector & vector, const ShapeletCovariance & cov)
A constructor from a vector of values, with covariance.
The input vector should have (order+1)*(order+2)/2 elements. The covariance matrix is of the input vector of values. So it should be square, symmetric, and have the same size in each dimension as the input vector.
Caveat: The input vector is real, not complex. See the comment for getValues for the expected order of values.
Parameters
order the maximum value of p+q to measure.
sigma the scale size of the shapelet decomposition (arcsec).
vector the shapelet vector
cov the covariance matrix
lsst::meas::algorithms::Shapelet::~Shapelet ()
Destructor needs to delete pImpl.
lsst::meas::algorithms::Shapelet::Shapelet (const Shapelet & rhs)
Copy constructor does a deep copy.
lsst::meas::algorithms::Shapelet::Shapelet (const shapelet::BVec & bvec)
A constructor that is only used by various Shapelet implementations.
This is used by ShapeletInterpolation for example. It is more convenient to leave this public, but you can't actually use it, since BVec isn't defined publicly.
Member Function Documentation
double lsst::meas::algorithms::Shapelet::evaluateAt (const PointD & pos)
Evaluate f(x,y)
Evaluate the intensity as a function of chip position (x,y)
This is the approximation to the true f(x,y) defined by the decomposition Sum_pq b_pq psi_pq(x,y,sigma).
Referenced by evaluateAt(), and lsst::meas::algorithms::ShapeletKernelFunction::operator()().
double lsst::meas::algorithms::Shapelet::evaluateAt (double x, double y)
References lsst::meas::algorithms::ShapeletImpl::evaluateAt(), and evaluateAt().
boost::shared_ptr< const Shapelet::ShapeletCovariance > lsst::meas::algorithms::Shapelet::getCovariance () const
get the covariance matrix
References lsst::meas::algorithms::ShapeletImpl::getCovariance().
int lsst::meas::algorithms::Shapelet::getOrder () const
get the order of the shapelet
References lsst::meas::algorithms::shapelet::BVec::getOrder().
Referenced by measureFromImage().
std::complex< double > lsst::meas::algorithms::Shapelet::getPQ (int p, int q)
Get a complex b_pq value.
Get the coefficient b_pq for the shapelet decomposition.
References lsst::meas::algorithms::ShapeletImpl::getPQ().
double lsst::meas::algorithms::Shapelet::getSigma () const
get the scale size of the shapelet
References lsst::meas::algorithms::shapelet::BVec::getSigma().
const Shapelet::ShapeletVector & lsst::meas::algorithms::Shapelet::getValues () const
get the values as a vector.
The order of values are: b00 real(b10) imag(b10) real(b20) imag(b20) b11 real(b30) imag(b30) real(b21) imag(b21) real(b40) imag(b40) real(b31) imag(b31) b22 etc.
where bpq corresponds to the coefficients $b_{pq}$ as defined in Bernstein and Jarvis (2002).
References lsst::meas::algorithms::shapelet::BVec::getValues().
bool lsst::meas::algorithms::Shapelet::hasCovariance () const
does the shapelet have a covariance matrix stored?
References lsst::meas::algorithms::ShapeletImpl::getCovariance().
bool lsst::meas::algorithms::Shapelet::measureFromImage (const Source & source, const PointD & pos, bool isCentroidFixed, bool isSigmaFixed, double aperture, const Exposure & exposure, const MaskPixel okmask = 0)
measure shapelet decomposition of an image
The initial estimate of the centroid is taken from the source. The initial estimate of sigma is the value given by this->getSigma().
The normal operation would be to allow both values to shift to find the best values for the image. However, there are reasons to keep each fixed.
First, if we have very accurate positions given in the source object, and we want the PSF to include the centroid shift that is present in the seeing, then this would be a good reason to keep it fixed.
Second, interpolation of the PSF is more straightforward if all the stars are measured with the saem sigma. So the normal practice is to let sigma float for each star, then find the mean of all the stars in an image, and finally remeasure each star with this constant value of sigma.
So, there are two boolean parameters that govern what should be kept fixed during the calculation.
isCentroidFixed says whether to keep the centoid fixed. If it is false, then the centoid is allowed to vary until b10 = 0 (our definition of being centroided).
isSigmaFixed says whether to keep the sigma fixed. If it is false, then sigma is allowed to vary until b11 = 0 (which corresponds to when the measured shapelet components have the maximum signal-to-noise).
The measurement is done using a circular aperture, whose radius is given by the paremeter aperture. This aperture (given in arcsec) defines a circle in sky coordinates, not chip coordinates.
The return value is true if the measurement is successful, and falso if not.
Parameters
source The source of which to measure the decomposition.
pos The position of the object
isCentroidFixed Is sigma fixed? or should it be allowed to vary?
isSigmaFixed Is sigma fixed? or should it be allowed to vary?
aperture The aperture size in arcsec for the measurement.
exposure The exposure on which to measure the decompoisition.
okmask The mask values that are ok to use
References Assert, dbg, lsst::meas::algorithms::ShapeletImpl::getCovariance(), getOrder(), lsst::meas::algorithms::shapelet::BVec::getSigma(), and lsst::meas::algorithms::shapelet::BVec::setSigma().
Shapelet & lsst::meas::algorithms::Shapelet::operator= (const Shapelet & rhs)
op= does a deep copy
void lsst::meas::algorithms::Shapelet::setSigma (double sigma)
set a new value of sigma
References lsst::meas::algorithms::shapelet::BVec::setSigma().
int lsst::meas::algorithms::Shapelet::size () const
the size of the shapelet vector
References lsst::meas::algorithms::shapelet::BVec::size().
const shapelet::BVec & lsst::meas::algorithms::Shapelet::viewAsBVec () const
View the shapelet as a BVec.
This is also only used by various Shapelet implementations, but it is convenient to leave it public rather than define a bunch of friend classes.
shapelet::BVec & lsst::meas::algorithms::Shapelet::viewAsBVec ()
The documentation for this class was generated from the following files:
include/lsst/meas/algorithms/Shapelet.h
src/Shapelet.cc