lsst.meas.algorithms: lsst::meas::algorithms::shapelet::Bounds Class Reference
lsst::meas::algorithms::shapelet::Bounds Class Reference
#include <Bounds.h>
Public Member Functions
Bounds (double x1, double x2, double y1, double y2)
Bounds (const Position &pos)
Bounds ()
~Bounds ()
void setXMin (double x)
void setXMax (double x)
void setYMin (double y)
void setYMax (double y)
double getXMin () const
double getXMax () const
double getYMin () const
double getYMax () const
bool isDefined () const
Position getCenter () const
void operator+= (const Position &pos)
void operator+= (const Bounds &rec)
bool operator== (const Bounds &rhs) const
void snap (double d)
void addBorder (double d)
void addXBorder (double d)
void addYBorder (double d)
Bounds operator& (const Bounds &rhs) const
bool includes (const Position &pos) const
bool includes (double x, double y) const
bool includes (const Bounds &b2) const
bool intersects (const Bounds &b2) const
double getArea () const
std::vector< Bounds > quarter () const
std::vector< Bounds > divide (int nx, int ny) const
void write (std::ostream &fout) const
void read (std::istream &fin)
Position get00 () const
Position get01 () const
Position get10 () const
Position get11 () const
bool isWide () const
bool isTall () const
Constructor & Destructor Documentation
lsst::meas::algorithms::shapelet::Bounds::Bounds (double x1, double x2, double y1, double y2) inline
lsst::meas::algorithms::shapelet::Bounds::Bounds (const Position & pos) inline
lsst::meas::algorithms::shapelet::Bounds::Bounds () inline
Referenced by operator&().
lsst::meas::algorithms::shapelet::Bounds::~Bounds () inline
Member Function Documentation
void lsst::meas::algorithms::shapelet::Bounds::addBorder (double d)
void lsst::meas::algorithms::shapelet::Bounds::addXBorder (double d)
void lsst::meas::algorithms::shapelet::Bounds::addYBorder (double d)
std::vector< Bounds > lsst::meas::algorithms::shapelet::Bounds::divide (int nx, int ny) const
Referenced by lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::findStars(), and quarter().
Position lsst::meas::algorithms::shapelet::Bounds::get00 () const inline
Position lsst::meas::algorithms::shapelet::Bounds::get01 () const inline
Position lsst::meas::algorithms::shapelet::Bounds::get10 () const inline
Position lsst::meas::algorithms::shapelet::Bounds::get11 () const inline
double lsst::meas::algorithms::shapelet::Bounds::getArea () const
Position lsst::meas::algorithms::shapelet::Bounds::getCenter () const
double lsst::meas::algorithms::shapelet::Bounds::getXMax () const inline
Referenced by lsst::meas::algorithms::shapelet::FittedPsf::getXMax(), lsst::meas::algorithms::shapelet::Legendre2D::getXMax(), and operator+=().
double lsst::meas::algorithms::shapelet::Bounds::getXMin () const inline
Referenced by lsst::meas::algorithms::shapelet::FittedPsf::getXMin(), lsst::meas::algorithms::shapelet::Legendre2D::getXMin(), and operator+=().
double lsst::meas::algorithms::shapelet::Bounds::getYMax () const inline
Referenced by lsst::meas::algorithms::shapelet::FittedPsf::getYMax(), lsst::meas::algorithms::shapelet::Legendre2D::getYMax(), and operator+=().
double lsst::meas::algorithms::shapelet::Bounds::getYMin () const inline
Referenced by lsst::meas::algorithms::shapelet::FittedPsf::getYMin(), lsst::meas::algorithms::shapelet::Legendre2D::getYMin(), and operator+=().
bool lsst::meas::algorithms::shapelet::Bounds::includes (const Position & pos) const
References lsst::meas::algorithms::shapelet::Position::getX(), and lsst::meas::algorithms::shapelet::Position::getY().
Referenced by includes().
bool lsst::meas::algorithms::shapelet::Bounds::includes (double x, double y) const
References includes().
bool lsst::meas::algorithms::shapelet::Bounds::includes (const Bounds & b2) const
References isDefined().
bool lsst::meas::algorithms::shapelet::Bounds::intersects (const Bounds & b2) const
bool lsst::meas::algorithms::shapelet::Bounds::isDefined () const inline
Referenced by includes(), and operator+=().
bool lsst::meas::algorithms::shapelet::Bounds::isTall () const inline
bool lsst::meas::algorithms::shapelet::Bounds::isWide () const inline
Bounds lsst::meas::algorithms::shapelet::Bounds::operator& (const Bounds & rhs) const
References Bounds().
void lsst::meas::algorithms::shapelet::Bounds::operator+= (const Position & pos)
References lsst::meas::algorithms::shapelet::Position::getX(), and lsst::meas::algorithms::shapelet::Position::getY().
void lsst::meas::algorithms::shapelet::Bounds::operator+= (const Bounds & rec)
References getXMax(), getXMin(), getYMax(), getYMin(), and isDefined().
bool lsst::meas::algorithms::shapelet::Bounds::operator== (const Bounds & rhs) const
std::vector< Bounds > lsst::meas::algorithms::shapelet::Bounds::quarter () const
References divide().
void lsst::meas::algorithms::shapelet::Bounds::read (std::istream & fin)
Referenced by lsst::meas::algorithms::shapelet::operator>>().
void lsst::meas::algorithms::shapelet::Bounds::setXMax (double x) inline
void lsst::meas::algorithms::shapelet::Bounds::setXMin (double x) inline
void lsst::meas::algorithms::shapelet::Bounds::setYMax (double y) inline
void lsst::meas::algorithms::shapelet::Bounds::setYMin (double y) inline
void lsst::meas::algorithms::shapelet::Bounds::snap (double d)
void lsst::meas::algorithms::shapelet::Bounds::write (std::ostream & fout) const
Referenced by lsst::meas::algorithms::shapelet::operator<<().
The documentation for this class was generated from the following files:
include/lsst/meas/algorithms/shapelet/Bounds.h
src/shapelet/Bounds.cc