lsst.meas.algorithms: lsst::meas::algorithms::shapelet::Function2D Class Reference
lsst::meas::algorithms::shapelet::Function2D Class Reference abstract
#include <Function2D.h>
Public Member Functions
Function2D ()
Function2D (int xo, int yo)
Function2D (int xo, int yo, const DMatrix &c)
Function2D (const Function2D &rhs)
virtual ~Function2D ()
virtual void write (std::ostream &fout) const =0
virtual std::auto_ptr< Function2D > copy () const =0
virtual void addLinear (double a, double b, double c)=0
virtual void linearPreTransform (double a, double b, double c, double d, double e, double f)=0
virtual std::auto_ptr< Function2D > dFdX () const =0
virtual std::auto_ptr< Function2D > dFdY () const =0
virtual std::auto_ptr< Function2D > conj () const
virtual void operator*= (double scale)
virtual double operator() (double x, double y) const
double operator() (const Position &p) const
virtual void setTo (double value)
bool isNonZero () const
int getXOrder () const
int getYOrder () const
const DMatrix & getCoeffs () const
virtual void simpleFit (int order, const std::vector< Position > &pos, const std::vector< double > &v, const std::vector< bool > &shouldUse, const std::vector< double > *sigList=0, double *chisqOut=0, int *dofOut=0, DMatrix *cov=0)
virtual void outlierFit (int order, double nsig, const std::vector< Position > &pos, const std::vector< double > &v, std::vector< bool > *shouldUse, const std::vector< double > *sigList=0, double *chisqout=0, int *dofout=0, DMatrix *cov=0)
virtual void orderFit (int maxOrder, double equivProb, const std::vector< Position > &pos, const std::vector< double > &v, const std::vector< bool > &shouldUse, const std::vector< double > *sigList=0, double *chisqout=0, int *dofout=0, DMatrix *cov=0)
virtual void linearTransform (double a, double b, double c, const Function2D &f, const Function2D &g)
virtual void linearTransform (double a, double b, const Function2D &f)
virtual void operator+= (const Function2D &rhs)=0
virtual void setFunction (int _xOrder, int _yOrder, const DVector &fVect)=0
Static Public Member Functions
static std::auto_ptr< Function2D > read (std::istream &fin)
Protected Member Functions
virtual DVector definePX (int order, double x) const =0
virtual DVector definePY (int order, double y) const =0
Protected Attributes
int _xOrder
int _yOrder
std::auto_ptr< DMatrix > _coeffs
Constructor & Destructor Documentation
lsst::meas::algorithms::shapelet::Function2D::Function2D () inline
lsst::meas::algorithms::shapelet::Function2D::Function2D (int xo, int yo) inline
References _coeffs.
lsst::meas::algorithms::shapelet::Function2D::Function2D (int xo, int yo, const DMatrix & c) inline
lsst::meas::algorithms::shapelet::Function2D::Function2D (const Function2D & rhs) inline
virtual lsst::meas::algorithms::shapelet::Function2D::~Function2D () inline virtual
Member Function Documentation
virtual void lsst::meas::algorithms::shapelet::Function2D::addLinear (double a, double b, double c) pure virtual
Implemented in lsst::meas::algorithms::shapelet::Polynomial2D, lsst::meas::algorithms::shapelet::Constant2D, and lsst::meas::algorithms::shapelet::Legendre2D.
std::auto_ptr< Function2D > lsst::meas::algorithms::shapelet::Function2D::conj () const virtual
References copy(), and TMV_conjugateSelf.
virtual std::auto_ptr<Function2D> lsst::meas::algorithms::shapelet::Function2D::copy () const pure virtual
Implemented in lsst::meas::algorithms::shapelet::Polynomial2D, lsst::meas::algorithms::shapelet::Constant2D, and lsst::meas::algorithms::shapelet::Legendre2D.
Referenced by conj().
virtual DVector lsst::meas::algorithms::shapelet::Function2D::definePX (int order, double x) const protected pure virtual
Referenced by operator()().
virtual DVector lsst::meas::algorithms::shapelet::Function2D::definePY (int order, double y) const protected pure virtual
Referenced by operator()().
virtual std::auto_ptr<Function2D> lsst::meas::algorithms::shapelet::Function2D::dFdX () const pure virtual
Implemented in lsst::meas::algorithms::shapelet::Polynomial2D, lsst::meas::algorithms::shapelet::Constant2D, and lsst::meas::algorithms::shapelet::Legendre2D.
virtual std::auto_ptr<Function2D> lsst::meas::algorithms::shapelet::Function2D::dFdY () const pure virtual
Implemented in lsst::meas::algorithms::shapelet::Polynomial2D, lsst::meas::algorithms::shapelet::Constant2D, and lsst::meas::algorithms::shapelet::Legendre2D.
const DMatrix& lsst::meas::algorithms::shapelet::Function2D::getCoeffs () const inline
References _coeffs.
Referenced by linearTransform().
int lsst::meas::algorithms::shapelet::Function2D::getXOrder () const inline
References _xOrder.
Referenced by linearTransform(), and lsst::meas::algorithms::shapelet::Polynomial2D::makeProductOf().
int lsst::meas::algorithms::shapelet::Function2D::getYOrder () const inline
References _yOrder.
Referenced by linearTransform(), and lsst::meas::algorithms::shapelet::Polynomial2D::makeProductOf().
bool lsst::meas::algorithms::shapelet::Function2D::isNonZero () const inline
References _coeffs, _xOrder, and _yOrder.
virtual void lsst::meas::algorithms::shapelet::Function2D::linearPreTransform (double a, double b, double c, double d, double e, double f) pure virtual
Implemented in lsst::meas::algorithms::shapelet::Polynomial2D, lsst::meas::algorithms::shapelet::Constant2D, and lsst::meas::algorithms::shapelet::Legendre2D.
void lsst::meas::algorithms::shapelet::Function2D::linearTransform (double a, double b, double c, const Function2D & f, const Function2D & g) virtual
References _coeffs, _xOrder, _yOrder, Assert, getCoeffs(), getXOrder(), and getYOrder().
virtual void lsst::meas::algorithms::shapelet::Function2D::linearTransform (double a, double b, const Function2D & f) inline virtual
References linearTransform().
Referenced by linearTransform().
double lsst::meas::algorithms::shapelet::Function2D::operator() (double x, double y) const virtual
Reimplemented in lsst::meas::algorithms::shapelet::Constant2D.
References _coeffs, _xOrder, _yOrder, definePX(), definePY(), EIGEN_ToScalar, and EIGEN_Transpose.
double lsst::meas::algorithms::shapelet::Function2D::operator() (const Position & p) const inline
References lsst::meas::algorithms::shapelet::Position::getX(), lsst::meas::algorithms::shapelet::Position::getY(), and operator()().
Referenced by operator()().
virtual void lsst::meas::algorithms::shapelet::Function2D::operator*= (double scale) inline virtual
References _coeffs.
virtual void lsst::meas::algorithms::shapelet::Function2D::operator+= (const Function2D & rhs) pure virtual
Implemented in lsst::meas::algorithms::shapelet::Polynomial2D, lsst::meas::algorithms::shapelet::Constant2D, and lsst::meas::algorithms::shapelet::Legendre2D.
void lsst::meas::algorithms::shapelet::Function2D::orderFit (int maxOrder, double equivProb, const std::vector< Position > & pos, const std::vector< double > & v, const std::vector< bool > & shouldUse, const std::vector< double > * sigList = 0, double * chisqout = 0, int * dofout = 0, DMatrix * cov = 0) virtual
References Assert, lsst::meas::algorithms::shapelet::Equivalent(), lsst::meas::algorithms::shapelet::fitSize(), setFunction(), and xdbg.
void lsst::meas::algorithms::shapelet::Function2D::outlierFit (int order, double nsig, const std::vector< Position > & pos, const std::vector< double > & v, std::vector< bool > * shouldUse, const std::vector< double > * sigList = 0, double * chisqout = 0, int * dofout = 0, DMatrix * cov = 0) virtual
References lsst::meas::algorithms::shapelet::absSq(), lsst::meas::algorithms::shapelet::fitSize(), setFunction(), and xdbg.
Referenced by lsst::meas::algorithms::shapelet::SizeMagnitudeStarSelectorAlgo::fitStellarSizes().
std::auto_ptr< Function2D > lsst::meas::algorithms::shapelet::Function2D::read (std::istream & fin) static
Referenced by lsst::meas::algorithms::shapelet::operator>>().
virtual void lsst::meas::algorithms::shapelet::Function2D::setFunction (int _xOrder, int _yOrder, const DVector & fVect) pure virtual
Implemented in lsst::meas::algorithms::shapelet::Polynomial2D, lsst::meas::algorithms::shapelet::Constant2D, and lsst::meas::algorithms::shapelet::Legendre2D.
Referenced by orderFit(), outlierFit(), and simpleFit().
virtual void lsst::meas::algorithms::shapelet::Function2D::setTo (double value) inline virtual
References _coeffs, _xOrder, and _yOrder.
Referenced by lsst::meas::algorithms::shapelet::Constant2D::Constant2D().
void lsst::meas::algorithms::shapelet::Function2D::simpleFit (int order, const std::vector< Position > & pos, const std::vector< double > & v, const std::vector< bool > & shouldUse, const std::vector< double > * sigList = 0, double * chisqOut = 0, int * dofOut = 0, DMatrix * cov = 0) virtual
References lsst::meas::algorithms::shapelet::fitSize(), and setFunction().
virtual void lsst::meas::algorithms::shapelet::Function2D::write (std::ostream & fout) const pure virtual
Implemented in lsst::meas::algorithms::shapelet::Polynomial2D, lsst::meas::algorithms::shapelet::Constant2D, and lsst::meas::algorithms::shapelet::Legendre2D.
Referenced by lsst::meas::algorithms::shapelet::operator<<().
Member Data Documentation
std::auto_ptr<DMatrix> lsst::meas::algorithms::shapelet::Function2D::_coeffs protected
Referenced by lsst::meas::algorithms::shapelet::Constant2D::addLinear(), lsst::meas::algorithms::shapelet::Constant2D::Constant2D(), lsst::meas::algorithms::shapelet::Legendre2D::dFdX(), lsst::meas::algorithms::shapelet::Polynomial2D::dFdX(), lsst::meas::algorithms::shapelet::Legendre2D::dFdY(), lsst::meas::algorithms::shapelet::Polynomial2D::dFdY(), Function2D(), getCoeffs(), isNonZero(), lsst::meas::algorithms::shapelet::Legendre2D::Legendre2D(), lsst::meas::algorithms::shapelet::Polynomial2D::linearPreTransform(), linearTransform(), lsst::meas::algorithms::shapelet::Polynomial2D::makeProductOf(), operator()(), lsst::meas::algorithms::shapelet::Constant2D::operator()(), operator*=(), lsst::meas::algorithms::shapelet::Legendre2D::operator+=(), lsst::meas::algorithms::shapelet::Constant2D::operator+=(), lsst::meas::algorithms::shapelet::Polynomial2D::operator+=(), lsst::meas::algorithms::shapelet::Polynomial2D::Polynomial2D(), lsst::meas::algorithms::shapelet::Legendre2D::setFunction(), lsst::meas::algorithms::shapelet::Constant2D::setFunction(), lsst::meas::algorithms::shapelet::Polynomial2D::setFunction(), setTo(), and lsst::meas::algorithms::shapelet::Polynomial2D::write().
int lsst::meas::algorithms::shapelet::Function2D::_xOrder protected
Referenced by lsst::meas::algorithms::shapelet::Legendre2D::dFdX(), lsst::meas::algorithms::shapelet::Polynomial2D::dFdX(), lsst::meas::algorithms::shapelet::Legendre2D::dFdY(), lsst::meas::algorithms::shapelet::Polynomial2D::dFdY(), getXOrder(), isNonZero(), lsst::meas::algorithms::shapelet::Legendre2D::Legendre2D(), lsst::meas::algorithms::shapelet::Polynomial2D::linearPreTransform(), linearTransform(), lsst::meas::algorithms::shapelet::Polynomial2D::makeProductOf(), operator()(), lsst::meas::algorithms::shapelet::Legendre2D::operator+=(), lsst::meas::algorithms::shapelet::Polynomial2D::operator+=(), lsst::meas::algorithms::shapelet::Polynomial2D::Polynomial2D(), lsst::meas::algorithms::shapelet::Legendre2D::setFunction(), lsst::meas::algorithms::shapelet::Constant2D::setFunction(), lsst::meas::algorithms::shapelet::Polynomial2D::setFunction(), setTo(), lsst::meas::algorithms::shapelet::Legendre2D::write(), and lsst::meas::algorithms::shapelet::Polynomial2D::write().
int lsst::meas::algorithms::shapelet::Function2D::_yOrder protected
Referenced by lsst::meas::algorithms::shapelet::Legendre2D::dFdX(), lsst::meas::algorithms::shapelet::Polynomial2D::dFdX(), lsst::meas::algorithms::shapelet::Legendre2D::dFdY(), lsst::meas::algorithms::shapelet::Polynomial2D::dFdY(), getYOrder(), isNonZero(), lsst::meas::algorithms::shapelet::Legendre2D::Legendre2D(), lsst::meas::algorithms::shapelet::Polynomial2D::linearPreTransform(), linearTransform(), lsst::meas::algorithms::shapelet::Polynomial2D::makeProductOf(), operator()(), lsst::meas::algorithms::shapelet::Legendre2D::operator+=(), lsst::meas::algorithms::shapelet::Polynomial2D::operator+=(), lsst::meas::algorithms::shapelet::Polynomial2D::Polynomial2D(), lsst::meas::algorithms::shapelet::Legendre2D::setFunction(), lsst::meas::algorithms::shapelet::Constant2D::setFunction(), lsst::meas::algorithms::shapelet::Polynomial2D::setFunction(), setTo(), lsst::meas::algorithms::shapelet::Legendre2D::write(), and lsst::meas::algorithms::shapelet::Polynomial2D::write().
The documentation for this class was generated from the following files:
include/lsst/meas/algorithms/shapelet/Function2D.h
src/shapelet/Function2D.cc