lsst.meas.algorithms: lsst::meas::algorithms::LoadCandidatesVisitor Class Reference
lsst::meas::algorithms::LoadCandidatesVisitor Class Reference
Public Types
typedef shapelet::Position Position
typedef shapelet::BVec BVec
typedef
lsst::afw::math::SpatialCellCandidate SpatialCellCandidate
Public Member Functions
LoadCandidatesVisitor (std::vector< ShapeletPsfCandidate * > &cand, std::vector< Position > &pos, std::vector< BVec > &psf, std::vector< double > &nu, std::vector< long > &flags)
void reset ()
void processCandidate (SpatialCellCandidate *cand)
Public Member Functions inherited from lsst::afw::math::CandidateVisitor
CandidateVisitor ()
virtual ~CandidateVisitor ()
Public Attributes
std::vector
< ShapeletPsfCandidate * > & _cand
std::vector< Position > & _pos
std::vector< BVec > & _psf
std::vector< double > & _nu
std::vector< long > & _flags
Member Typedef Documentation
typedef shapelet::BVec lsst::meas::algorithms::LoadCandidatesVisitor::BVec
typedef shapelet::Position lsst::meas::algorithms::LoadCandidatesVisitor::Position
typedef lsst::afw::math::SpatialCellCandidate lsst::meas::algorithms::LoadCandidatesVisitor::SpatialCellCandidate
Constructor & Destructor Documentation
lsst::meas::algorithms::LoadCandidatesVisitor::LoadCandidatesVisitor (std::vector< ShapeletPsfCandidate * > & cand, std::vector< Position > & pos, std::vector< BVec > & psf, std::vector< double > & nu, std::vector< long > & flags) inline
Member Function Documentation
void lsst::meas::algorithms::LoadCandidatesVisitor::processCandidate (SpatialCellCandidate * cand) inline virtual
Reimplemented from lsst::afw::math::CandidateVisitor.
References _cand, _flags, _nu, _pos, _psf, Assert, lsst::meas::algorithms::ShapeletPsfCandidate::getCandidateRating(), lsst::meas::algorithms::ShapeletPsfCandidate::getShapelet(), lsst::meas::algorithms::ShapeletPsfCandidate::getX(), and lsst::meas::algorithms::ShapeletPsfCandidate::getY().
void lsst::meas::algorithms::LoadCandidatesVisitor::reset () inline virtual
Reimplemented from lsst::afw::math::CandidateVisitor.
Member Data Documentation
std::vector<ShapeletPsfCandidate*>& lsst::meas::algorithms::LoadCandidatesVisitor::_cand
Referenced by processCandidate().
std::vector<long>& lsst::meas::algorithms::LoadCandidatesVisitor::_flags
Referenced by processCandidate().
std::vector<double>& lsst::meas::algorithms::LoadCandidatesVisitor::_nu
Referenced by processCandidate().
std::vector<Position>& lsst::meas::algorithms::LoadCandidatesVisitor::_pos
Referenced by processCandidate().
std::vector<BVec>& lsst::meas::algorithms::LoadCandidatesVisitor::_psf
Referenced by processCandidate().
The documentation for this class was generated from the following file:
src/ShapeletInterpolation.cc