lsst.meas.algorithms: lsst::meas::algorithms::shapelet::Polynomial2D Class Reference
lsst::meas::algorithms::shapelet::Polynomial2D Class Reference
#include <Function2D.h>
Public Member Functions
Polynomial2D (double scale=1.)
Polynomial2D (const Polynomial2D &rhs)
Polynomial2D (const DMatrix &a, double scale=1.)
Polynomial2D (std::istream &fin)
Polynomial2D (int xo, int yo, double scale=1.)
virtual ~Polynomial2D ()
virtual void write (std::ostream &fout) const
virtual std::auto_ptr< Function2D > dFdX () const
virtual std::auto_ptr< Function2D > dFdY () const
std::auto_ptr< Function2D > copy () const
virtual void addLinear (double a, double b, double c)
virtual void linearPreTransform (double a, double b, double c, double d, double e, double f)
virtual void operator+= (const Function2D &rhs)
void makeProductOf (const Polynomial2D &f, const Polynomial2D &g)
virtual void setFunction (int xOrder, int yOrder, const DVector &fVect)
Public Member Functions inherited from lsst::meas::algorithms::shapelet::Function2D
Function2D ()
Function2D (int xo, int yo)
Function2D (int xo, int yo, const DMatrix &c)
Function2D (const Function2D &rhs)
virtual ~Function2D ()
virtual std::auto_ptr< Function2D > conj () const
virtual void operator*= (double scale)
virtual double operator() (double x, double y) const
double operator() (const Position &p) const
virtual void setTo (double value)
bool isNonZero () const
int getXOrder () const
int getYOrder () const
const DMatrix & getCoeffs () const
virtual void simpleFit (int order, const std::vector< Position > &pos, const std::vector< double > &v, const std::vector< bool > &shouldUse, const std::vector< double > *sigList=0, double *chisqOut=0, int *dofOut=0, DMatrix *cov=0)
virtual void outlierFit (int order, double nsig, const std::vector< Position > &pos, const std::vector< double > &v, std::vector< bool > *shouldUse, const std::vector< double > *sigList=0, double *chisqout=0, int *dofout=0, DMatrix *cov=0)
virtual void orderFit (int maxOrder, double equivProb, const std::vector< Position > &pos, const std::vector< double > &v, const std::vector< bool > &shouldUse, const std::vector< double > *sigList=0, double *chisqout=0, int *dofout=0, DMatrix *cov=0)
virtual void linearTransform (double a, double b, double c, const Function2D &f, const Function2D &g)
virtual void linearTransform (double a, double b, const Function2D &f)
Additional Inherited Members
Static Public Member Functions inherited from lsst::meas::algorithms::shapelet::Function2D
static std::auto_ptr< Function2D > read (std::istream &fin)
Protected Attributes inherited from lsst::meas::algorithms::shapelet::Function2D
int _xOrder
int _yOrder
std::auto_ptr< DMatrix > _coeffs
Constructor & Destructor Documentation
lsst::meas::algorithms::shapelet::Polynomial2D::Polynomial2D (double scale = 1.) inline
Referenced by copy(), dFdX(), and dFdY().
lsst::meas::algorithms::shapelet::Polynomial2D::Polynomial2D (const Polynomial2D & rhs) inline
lsst::meas::algorithms::shapelet::Polynomial2D::Polynomial2D (const DMatrix & a, double scale = 1.) inline
lsst::meas::algorithms::shapelet::Polynomial2D::Polynomial2D (std::istream & fin)
References lsst::meas::algorithms::shapelet::Function2D::_coeffs, lsst::meas::algorithms::shapelet::Function2D::_xOrder, and lsst::meas::algorithms::shapelet::Function2D::_yOrder.
lsst::meas::algorithms::shapelet::Polynomial2D::Polynomial2D (int xo, int yo, double scale = 1.) inline
virtual lsst::meas::algorithms::shapelet::Polynomial2D::~Polynomial2D () inline virtual
Member Function Documentation
void lsst::meas::algorithms::shapelet::Polynomial2D::addLinear (double a, double b, double c) virtual
Implements lsst::meas::algorithms::shapelet::Function2D.
std::auto_ptr<Function2D> lsst::meas::algorithms::shapelet::Polynomial2D::copy () const inline virtual
Implements lsst::meas::algorithms::shapelet::Function2D.
References Polynomial2D().
std::auto_ptr< Function2D > lsst::meas::algorithms::shapelet::Polynomial2D::dFdX () const virtual
Implements lsst::meas::algorithms::shapelet::Function2D.
References lsst::meas::algorithms::shapelet::Function2D::_coeffs, lsst::meas::algorithms::shapelet::Function2D::_xOrder, lsst::meas::algorithms::shapelet::Function2D::_yOrder, Assert, and Polynomial2D().
std::auto_ptr< Function2D > lsst::meas::algorithms::shapelet::Polynomial2D::dFdY () const virtual
Implements lsst::meas::algorithms::shapelet::Function2D.
References lsst::meas::algorithms::shapelet::Function2D::_coeffs, lsst::meas::algorithms::shapelet::Function2D::_xOrder, lsst::meas::algorithms::shapelet::Function2D::_yOrder, Assert, and Polynomial2D().
void lsst::meas::algorithms::shapelet::Polynomial2D::linearPreTransform (double a, double b, double c, double d, double e, double f) virtual
Implements lsst::meas::algorithms::shapelet::Function2D.
References lsst::meas::algorithms::shapelet::Function2D::_coeffs, lsst::meas::algorithms::shapelet::Function2D::_xOrder, lsst::meas::algorithms::shapelet::Function2D::_yOrder, b, lsst::meas::algorithms::shapelet::binom(), and k.
void lsst::meas::algorithms::shapelet::Polynomial2D::makeProductOf (const Polynomial2D & f, const Polynomial2D & g)
References lsst::meas::algorithms::shapelet::Function2D::_coeffs, lsst::meas::algorithms::shapelet::Function2D::_xOrder, lsst::meas::algorithms::shapelet::Function2D::_yOrder, Assert, lsst::meas::algorithms::shapelet::Function2D::getXOrder(), and lsst::meas::algorithms::shapelet::Function2D::getYOrder().
void lsst::meas::algorithms::shapelet::Polynomial2D::operator+= (const Function2D & rhs) virtual
Implements lsst::meas::algorithms::shapelet::Function2D.
References lsst::meas::algorithms::shapelet::Function2D::_coeffs, lsst::meas::algorithms::shapelet::Function2D::_xOrder, lsst::meas::algorithms::shapelet::Function2D::_yOrder, and Assert.
void lsst::meas::algorithms::shapelet::Polynomial2D::setFunction (int xOrder, int yOrder, const DVector & fVect) virtual
Implements lsst::meas::algorithms::shapelet::Function2D.
References lsst::meas::algorithms::shapelet::Function2D::_coeffs, lsst::meas::algorithms::shapelet::Function2D::_xOrder, lsst::meas::algorithms::shapelet::Function2D::_yOrder, Assert, and k.
void lsst::meas::algorithms::shapelet::Polynomial2D::write (std::ostream & fout) const virtual
Implements lsst::meas::algorithms::shapelet::Function2D.
References lsst::meas::algorithms::shapelet::Function2D::_coeffs, lsst::meas::algorithms::shapelet::Function2D::_xOrder, and lsst::meas::algorithms::shapelet::Function2D::_yOrder.
The documentation for this class was generated from the following files:
include/lsst/meas/algorithms/shapelet/Function2D.h
src/shapelet/Function2D.cc