lsst.meas.algorithms: lsst::meas::algorithms::PsfCandidate< PixelT > Class Template Reference
lsst::meas::algorithms::PsfCandidate< PixelT > Class Template Reference
Class stored in SpatialCells for spatial Psf fitting.
#include <PsfCandidate.h>
Public Types
typedef boost::shared_ptr
< PsfCandidate< PixelT > > Ptr
typedef boost::shared_ptr
< const PsfCandidate< PixelT > > ConstPtr
typedef std::vector< Ptr > PtrList
typedef
lsst::afw::image::MaskedImage
< PixelT > MaskedImageT
Public Types inherited from lsst::afw::math::SpatialCellMaskedImageCandidate< PixelT >
enum Status
typedef boost::shared_ptr
< SpatialCellMaskedImageCandidate > Ptr
typedef boost::shared_ptr
< SpatialCellCandidate > Ptr
typedef boost::shared_ptr
< const
SpatialCellMaskedImageCandidate > ConstPtr
typedef boost::shared_ptr
< const SpatialCellCandidate > ConstPtr
Public Types inherited from lsst::afw::math::SpatialCellCandidate
enum Status
typedef boost::shared_ptr
< SpatialCellCandidate > Ptr
typedef boost::shared_ptr
< const SpatialCellCandidate > ConstPtr
Public Member Functions
PsfCandidate (boost::shared_ptr< afw::table::SourceRecord > const &source, boost::shared_ptr< afw::image::Exposure< PixelT > const > parentExposure)
PsfCandidate (boost::shared_ptr< afw::table::SourceRecord > const &source, boost::shared_ptr< afw::image::Exposure< PixelT > const > parentExposure, double xCenter, double yCenter)
virtual ~PsfCandidate ()
Destructor.
double getCandidateRating () const
boost::shared_ptr
< afw::table::SourceRecord > getSource () const
Return the original Source.
double getAmplitude () const
Return the best-fit amplitude.
void setAmplitude (double amplitude)
Set the best-fit amplitude.
double getVar () const
Return the variance in use when fitting this object.
void setVar (double var)
Set the variance to use when fitting this object.
boost::shared_ptr
< afw::image::MaskedImage
< PixelT > const > getMaskedImage () const
boost::shared_ptr
< afw::image::MaskedImage
< PixelT > const > getMaskedImage (int width, int height) const
boost::shared_ptr
< afw::image::MaskedImage
< PixelT > > getOffsetImage (std::string const algorithm, unsigned int buffer) const
Return an offset version of the image of the source. The returned image has been offset to put the centre of the object in the centre of a pixel.
Public Member Functions inherited from lsst::afw::math::SpatialCellMaskedImageCandidate< PixelT >
SpatialCellMaskedImageCandidate (float const xCenter, float const yCenter)
virtual ~SpatialCellMaskedImageCandidate ()
double getChi2 () const
void setChi2 (double chi2)
SpatialCellCandidate (float const xCenter, float const yCenter)
virtual ~SpatialCellCandidate ()
float getXCenter () const
float getYCenter () const
virtual bool instantiate ()
virtual void setCandidateRating (double)
int getId () const
Status getStatus () const
void setStatus (Status status)
virtual bool isBad () const
Public Member Functions inherited from lsst::afw::math::SpatialCellCandidate
SpatialCellCandidate (float const xCenter, float const yCenter)
float getXCenter () const
float getYCenter () const
int getId () const
Status getStatus () const
void setStatus (Status status)
Static Public Member Functions
static int getBorderWidth ()
Return the number of pixels being ignored around the candidate image's edge.
static void setBorderWidth (int border)
Set the number of pixels to ignore around the candidate image's edge.
Static Public Member Functions inherited from lsst::afw::math::SpatialCellMaskedImageCandidate< PixelT >
static void setWidth (int width)
static int getWidth ()
static void setHeight (int height)
static int getHeight ()
Additional Inherited Members
Public Attributes inherited from lsst::afw::math::SpatialCellMaskedImageCandidate< PixelT >
BAD
GOOD
UNKNOWN
Protected Attributes inherited from lsst::afw::math::SpatialCellMaskedImageCandidate< PixelT >
boost::shared_ptr
< lsst::afw::image::MaskedImage
< PixelT >
lsst::afw::image::MaskPixel,
lsst::afw::image::VariancePixel > _image
Detailed Description
template<typename PixelT>
class lsst::meas::algorithms::PsfCandidate< PixelT >
Class stored in SpatialCells for spatial Psf fitting.
PsfCandidate is a detection that may turn out to be a PSF. We'll assign them to sets of SpatialCells; these sets will then be used to fit a spatial model to the PSF.
Member Typedef Documentation
template<typename PixelT> typedef boost::shared_ptr<const PsfCandidate<PixelT> > lsst::meas::algorithms::PsfCandidate< PixelT >::ConstPtr
template<typename PixelT> typedef lsst::afw::image::MaskedImage<PixelT> lsst::meas::algorithms::PsfCandidate< PixelT >::MaskedImageT
template<typename PixelT> typedef boost::shared_ptr<PsfCandidate<PixelT> > lsst::meas::algorithms::PsfCandidate< PixelT >::Ptr
template<typename PixelT> typedef std::vector<Ptr > lsst::meas::algorithms::PsfCandidate< PixelT >::PtrList
Constructor & Destructor Documentation
template<typename PixelT> lsst::meas::algorithms::PsfCandidate< PixelT >::PsfCandidate (boost::shared_ptr< afw::table::SourceRecord > const & source, boost::shared_ptr< afw::image::Exposure< PixelT > const > parentExposure) inline
Construct a PsfCandidate from a specified source and image.
The x/yCenter is set to source.getX/YAstrom()
Parameters
source The detected Source
parentExposure The image wherein lie the Sources
References CONST_PTR, and PTR.
template<typename PixelT> lsst::meas::algorithms::PsfCandidate< PixelT >::PsfCandidate (boost::shared_ptr< afw::table::SourceRecord > const & source, boost::shared_ptr< afw::image::Exposure< PixelT > const > parentExposure, double xCenter, double yCenter) inline
Construct a PsfCandidate from a specified source, image and xyCenter.
Parameters
source The detected Source
parentExposure The image wherein lie the Sources
xCenter the desired x center
yCenter the desired y center
References CONST_PTR, and PTR.
template<typename PixelT> virtual lsst::meas::algorithms::PsfCandidate< PixelT >::~PsfCandidate () inline virtual
Destructor.
Member Function Documentation
template<typename PixelT> double lsst::meas::algorithms::PsfCandidate< PixelT >::getAmplitude () const inline
Return the best-fit amplitude.
template<typename PixelT> static int lsst::meas::algorithms::PsfCandidate< PixelT >::getBorderWidth () inline static
Return the number of pixels being ignored around the candidate image's edge.
template<typename PixelT> double lsst::meas::algorithms::PsfCandidate< PixelT >::getCandidateRating () const inline virtual
Return Cell rating
Note
Required method for use by SpatialCell
Implements lsst::afw::math::SpatialCellMaskedImageCandidate< PixelT >.
template<typename PixelT > boost::shared_ptr< afwImage::MaskedImage< PixelT > const > lsst::meas::algorithms::PsfCandidate< PixelT >::getMaskedImage () const virtual
Return the image at the position of the Source, without any sub-pixel shifts to put the centre of the object in the centre of a pixel (for that, use getOffsetImage())
Implements lsst::afw::math::SpatialCellMaskedImageCandidate< PixelT >.
References CONST_PTR.
Referenced by lsst.meas.algorithms.replaceWithNoise.NoiseGenerator::getHeavyFootprint().
template<typename PixelT > boost::shared_ptr< afwImage::MaskedImage< PixelT > const > lsst::meas::algorithms::PsfCandidate< PixelT >::getMaskedImage (int width, int height) const
Return the image at the position of the Source, without any sub-pixel shifts to put the centre of the object in the centre of a pixel (for that, use getOffsetImage())
Referenced by lsst.meas.algorithms.replaceWithNoise.NoiseGenerator::getHeavyFootprint().
template<typename PixelT > boost::shared_ptr< afwImage::MaskedImage< PixelT > > lsst::meas::algorithms::PsfCandidate< PixelT >::getOffsetImage (std::string const algorithm, unsigned int buffer) const
Return an offset version of the image of the source. The returned image has been offset to put the centre of the object in the centre of a pixel.
References PTR.
Referenced by lsst::meas::algorithms::evalChi2Visitor< PixelT >::processCandidate().
template<typename PixelT> boost::shared_ptr< afw::table::SourceRecord > lsst::meas::algorithms::PsfCandidate< PixelT >::getSource () const inline
Return the original Source.
References PTR.
Referenced by lsst::meas::algorithms::evalChi2Visitor< PixelT >::processCandidate().
template<typename PixelT> double lsst::meas::algorithms::PsfCandidate< PixelT >::getVar () const inline
Return the variance in use when fitting this object.
template<typename PixelT> void lsst::meas::algorithms::PsfCandidate< PixelT >::setAmplitude (double amplitude) inline
Set the best-fit amplitude.
Referenced by lsst::meas::algorithms::evalChi2Visitor< PixelT >::processCandidate().
template<typename PixelT> static void lsst::meas::algorithms::PsfCandidate< PixelT >::setBorderWidth (int border) inline static
Set the number of pixels to ignore around the candidate image's edge.
template<typename PixelT> void lsst::meas::algorithms::PsfCandidate< PixelT >::setVar (double var) inline
Set the variance to use when fitting this object.
The documentation for this class was generated from the following files:
include/lsst/meas/algorithms/PsfCandidate.h
src/PsfCandidate.cc