lsst.meas.algorithms: lsst::meas::algorithms::shapelet::Legendre2D Class Reference
lsst::meas::algorithms::shapelet::Legendre2D Class Reference
#include <Legendre2D.h>
Public Member Functions
Legendre2D ()
Legendre2D (double xMin, double xMax, double yMin, double yMax)
Legendre2D (const Bounds &b)
Legendre2D (const Legendre2D &rhs)
Legendre2D (const Bounds &b, const DMatrix &a)
Legendre2D (int xo, int yo, const Bounds &b)
Legendre2D (std::istream &fin)
virtual ~Legendre2D ()
virtual void write (std::ostream &fout) const
virtual std::auto_ptr< Function2D > dFdX () const
virtual std::auto_ptr< Function2D > dFdY () const
virtual std::auto_ptr< Function2D > copy () const
virtual void addLinear (double a, double b, double c)
virtual void linearPreTransform (double a, double b, double c, double d, double e, double f)
virtual void operator+= (const Function2D &rhs)
double getXMin () const
double getXMax () const
double getYMin () const
double getYMax () const
const Bounds & getBounds () const
virtual void setFunction (int xorder, int yorder, const DVector &fvect)
Public Member Functions inherited from lsst::meas::algorithms::shapelet::Function2D
Function2D ()
Function2D (int xo, int yo)
Function2D (int xo, int yo, const DMatrix &c)
Function2D (const Function2D &rhs)
virtual ~Function2D ()
virtual std::auto_ptr< Function2D > conj () const
virtual void operator*= (double scale)
virtual double operator() (double x, double y) const
double operator() (const Position &p) const
virtual void setTo (double value)
bool isNonZero () const
int getXOrder () const
int getYOrder () const
const DMatrix & getCoeffs () const
virtual void simpleFit (int order, const std::vector< Position > &pos, const std::vector< double > &v, const std::vector< bool > &shouldUse, const std::vector< double > *sigList=0, double *chisqOut=0, int *dofOut=0, DMatrix *cov=0)
virtual void outlierFit (int order, double nsig, const std::vector< Position > &pos, const std::vector< double > &v, std::vector< bool > *shouldUse, const std::vector< double > *sigList=0, double *chisqout=0, int *dofout=0, DMatrix *cov=0)
virtual void orderFit (int maxOrder, double equivProb, const std::vector< Position > &pos, const std::vector< double > &v, const std::vector< bool > &shouldUse, const std::vector< double > *sigList=0, double *chisqout=0, int *dofout=0, DMatrix *cov=0)
virtual void linearTransform (double a, double b, double c, const Function2D &f, const Function2D &g)
virtual void linearTransform (double a, double b, const Function2D &f)
Additional Inherited Members
Static Public Member Functions inherited from lsst::meas::algorithms::shapelet::Function2D
static std::auto_ptr< Function2D > read (std::istream &fin)
Protected Attributes inherited from lsst::meas::algorithms::shapelet::Function2D
int _xOrder
int _yOrder
std::auto_ptr< DMatrix > _coeffs
Constructor & Destructor Documentation
lsst::meas::algorithms::shapelet::Legendre2D::Legendre2D () inline
Referenced by copy(), dFdX(), and dFdY().
lsst::meas::algorithms::shapelet::Legendre2D::Legendre2D (double xMin, double xMax, double yMin, double yMax) inline
lsst::meas::algorithms::shapelet::Legendre2D::Legendre2D (const Bounds & b) inline
lsst::meas::algorithms::shapelet::Legendre2D::Legendre2D (const Legendre2D & rhs) inline
lsst::meas::algorithms::shapelet::Legendre2D::Legendre2D (const Bounds & b, const DMatrix & a) inline
lsst::meas::algorithms::shapelet::Legendre2D::Legendre2D (int xo, int yo, const Bounds & b) inline
lsst::meas::algorithms::shapelet::Legendre2D::Legendre2D (std::istream & fin)
References lsst::meas::algorithms::shapelet::Function2D::_coeffs, lsst::meas::algorithms::shapelet::Function2D::_xOrder, and lsst::meas::algorithms::shapelet::Function2D::_yOrder.
virtual lsst::meas::algorithms::shapelet::Legendre2D::~Legendre2D () inline virtual
Member Function Documentation
void lsst::meas::algorithms::shapelet::Legendre2D::addLinear (double a, double b, double c) virtual
Implements lsst::meas::algorithms::shapelet::Function2D.
References getXMax(), getXMin(), getYMax(), and getYMin().
virtual std::auto_ptr<Function2D> lsst::meas::algorithms::shapelet::Legendre2D::copy () const inline virtual
Implements lsst::meas::algorithms::shapelet::Function2D.
References Legendre2D().
std::auto_ptr< Function2D > lsst::meas::algorithms::shapelet::Legendre2D::dFdX () const virtual
Implements lsst::meas::algorithms::shapelet::Function2D.
References lsst::meas::algorithms::shapelet::Function2D::_coeffs, lsst::meas::algorithms::shapelet::Function2D::_xOrder, lsst::meas::algorithms::shapelet::Function2D::_yOrder, getXMax(), getXMin(), k, and Legendre2D().
std::auto_ptr< Function2D > lsst::meas::algorithms::shapelet::Legendre2D::dFdY () const virtual
Implements lsst::meas::algorithms::shapelet::Function2D.
References lsst::meas::algorithms::shapelet::Function2D::_coeffs, lsst::meas::algorithms::shapelet::Function2D::_xOrder, lsst::meas::algorithms::shapelet::Function2D::_yOrder, getYMax(), getYMin(), k, and Legendre2D().
const Bounds& lsst::meas::algorithms::shapelet::Legendre2D::getBounds () const inline
Referenced by operator+=().
double lsst::meas::algorithms::shapelet::Legendre2D::getXMax () const inline
References lsst::meas::algorithms::shapelet::Bounds::getXMax().
Referenced by addLinear(), and dFdX().
double lsst::meas::algorithms::shapelet::Legendre2D::getXMin () const inline
References lsst::meas::algorithms::shapelet::Bounds::getXMin().
Referenced by addLinear(), and dFdX().
double lsst::meas::algorithms::shapelet::Legendre2D::getYMax () const inline
References lsst::meas::algorithms::shapelet::Bounds::getYMax().
Referenced by addLinear(), and dFdY().
double lsst::meas::algorithms::shapelet::Legendre2D::getYMin () const inline
References lsst::meas::algorithms::shapelet::Bounds::getYMin().
Referenced by addLinear(), and dFdY().
void lsst::meas::algorithms::shapelet::Legendre2D::linearPreTransform (double a, double b, double c, double d, double e, double f) virtual
Implements lsst::meas::algorithms::shapelet::Function2D.
References Assert.
void lsst::meas::algorithms::shapelet::Legendre2D::operator+= (const Function2D & rhs) virtual
Implements lsst::meas::algorithms::shapelet::Function2D.
References lsst::meas::algorithms::shapelet::Function2D::_coeffs, lsst::meas::algorithms::shapelet::Function2D::_xOrder, lsst::meas::algorithms::shapelet::Function2D::_yOrder, Assert, and getBounds().
void lsst::meas::algorithms::shapelet::Legendre2D::setFunction (int xorder, int yorder, const DVector & fvect) virtual
Implements lsst::meas::algorithms::shapelet::Function2D.
References lsst::meas::algorithms::shapelet::Function2D::_coeffs, lsst::meas::algorithms::shapelet::Function2D::_xOrder, lsst::meas::algorithms::shapelet::Function2D::_yOrder, Assert, and k.
void lsst::meas::algorithms::shapelet::Legendre2D::write (std::ostream & fout) const virtual
Implements lsst::meas::algorithms::shapelet::Function2D.
References lsst::meas::algorithms::shapelet::Function2D::_xOrder, and lsst::meas::algorithms::shapelet::Function2D::_yOrder.
The documentation for this class was generated from the following files:
include/lsst/meas/algorithms/shapelet/Legendre2D.h
src/shapelet/Legendre2D.cc