lsst.meas.algorithms: lsst::meas::algorithms::LocalShapeletKernel Class Reference
lsst::meas::algorithms::LocalShapeletKernel Class Reference
#include <ShapeletKernel.h>
Public Types
typedef boost::shared_ptr
< LocalShapeletKernel > Ptr
typedef boost::shared_ptr
< const LocalShapeletKernel > ConstPtr
typedef
lsst::afw::math::AnalyticKernel base
typedef lsst::afw::geom::Point2D Point
typedef lsst::afw::geom::Extent2I Extent
typedef
lsst::afw::image::Image
< double > Image
typedef lsst::afw::image::Wcs Wcs
Public Types inherited from lsst::afw::math::AnalyticKernel
typedef boost::shared_ptr
< AnalyticKernel > Ptr
typedef boost::shared_ptr
< AnalyticKernel const > ConstPtr
typedef
lsst::afw::math::Function2
< Pixel > KernelFunction
typedef boost::shared_ptr
< lsst::afw::math::Function2
< Pixel > > KernelFunctionPtr
typedef double Pixel
typedef boost::shared_ptr< Kernel > Ptr
typedef boost::shared_ptr
< Kernel const > ConstPtr
typedef boost::shared_ptr
< lsst::afw::math::Function2
< double > > SpatialFunctionPtr
typedef
lsst::afw::math::Function2
< double > SpatialFunction
typedef
lsst::afw::math::NullFunction2
< double > NullSpatialFunction
typedef generic_kernel_tag kernel_fill_factor
Public Types inherited from lsst::afw::math::Kernel
typedef double Pixel
typedef boost::shared_ptr< Kernel > Ptr
typedef boost::shared_ptr
< Kernel const > ConstPtr
typedef boost::shared_ptr
< lsst::afw::math::Function2
< double > > SpatialFunctionPtr
typedef
lsst::afw::math::Function2
< double > SpatialFunction
typedef
lsst::afw::math::NullFunction2
< double > NullSpatialFunction
typedef generic_kernel_tag kernel_fill_factor
Public Types inherited from lsst::daf::base::Citizen
typedef unsigned long memId
typedef memId(* memNewCallback)(const memId cid)
typedef memId(* memCallback)(const Citizen *ptr)
Public Types inherited from lsst::daf::base::Persistable
typedef boost::shared_ptr
< Persistable > Ptr
Public Member Functions
LocalShapeletKernel (Shapelet::ConstPtr shapelet, const Wcs::ConstPtr &wcsPtr, const Extent &size)
Constructor from a Shapelet.
LocalShapeletKernel (Shapelet::ConstPtr shapelet, const Wcs::ConstPtr &wcsPtr)
double computeImage (Image &image, bool doNormalize, double x=0.0, double y=0.0) const
Make an image of the kernel.
Public Member Functions inherited from lsst::afw::math::AnalyticKernel
AnalyticKernel ()
AnalyticKernel (int width, int height, KernelFunction const &kernelFunction, Kernel::SpatialFunction const &spatialFunction=NullSpatialFunction())
AnalyticKernel (int width, int height, KernelFunction const &kernelFunction, std::vector< Kernel::SpatialFunctionPtr > const &spatialFunctionList)
virtual ~AnalyticKernel ()
virtual boost::shared_ptr< Kernel > clone () const
double computeImage (lsst::afw::image::Image< Pixel > &image, bool doNormalize, double x=0.0, double y=0.0) const
virtual std::vector< double > getKernelParameters () const
virtual KernelFunctionPtr getKernelFunction () const
virtual std::string toString (std::string const &prefix="") const
virtual bool isPersistable () const
Kernel ()
Kernel (int width, int height, unsigned int nKernelParams, SpatialFunction const &spatialFunction=NullSpatialFunction())
Kernel (int width, int height, const std::vector< SpatialFunctionPtr > spatialFunctionList)
virtual ~Kernel ()
double computeImage (lsst::afw::image::Image< Pixel > &image, bool doNormalize, double x=0.0, double y=0.0) const
geom::Extent2I const getDimensions () const
void setDimensions (geom::Extent2I dims)
void setWidth (int width)
void setHeight (int height)
int getWidth () const
int getHeight () const
lsst::afw::geom::Point2I getCtr () const
int getCtrX () const
int getCtrY () const
lsst::afw::geom::Box2I getBBox () const
unsigned int getNKernelParameters () const
int getNSpatialParameters () const
SpatialFunctionPtr getSpatialFunction (unsigned int index) const
std::vector< SpatialFunctionPtr > getSpatialFunctionList () const
virtual double getKernelParameter (unsigned int i) const
lsst::afw::geom::Box2I growBBox (lsst::afw::geom::Box2I const &bbox) const
lsst::afw::geom::Box2I shrinkBBox (lsst::afw::geom::Box2I const &bbox) const
void setCtr (lsst::afw::geom::Point2I ctr)
void setCtrX (int ctrX)
void setCtrY (int ctrY)
std::vector< std::vector
< double > > getSpatialParameters () const
bool isSpatiallyVarying () const
void setKernelParameters (std::vector< double > const &params)
void setKernelParameters (std::pair< double, double > const &params)
void setSpatialParameters (const std::vector< std::vector< double > > params)
void computeKernelParametersFromSpatialModel (std::vector< double > &kernelParams, double x, double y) const
virtual void computeCache (int const)
virtual int getCacheSize () const
void writeFits (std::string const &fileName, std::string const &mode="w") const
void writeFits (fits::MemFileManager &manager, std::string const &mode="w") const
void writeFits (fits::Fits &fitsfile) const
virtual ~Persistable ()
Public Member Functions inherited from lsst::afw::math::Kernel
Kernel ()
Kernel (int width, int height, unsigned int nKernelParams, SpatialFunction const &spatialFunction=NullSpatialFunction())
Kernel (int width, int height, const std::vector< SpatialFunctionPtr > spatialFunctionList)
double computeImage (lsst::afw::image::Image< Pixel > &image, bool doNormalize, double x=0.0, double y=0.0) const
geom::Extent2I const getDimensions () const
void setDimensions (geom::Extent2I dims)
void setWidth (int width)
void setHeight (int height)
int getWidth () const
int getHeight () const
lsst::afw::geom::Point2I getCtr () const
int getCtrX () const
int getCtrY () const
lsst::afw::geom::Box2I getBBox () const
unsigned int getNKernelParameters () const
int getNSpatialParameters () const
SpatialFunctionPtr getSpatialFunction (unsigned int index) const
std::vector< SpatialFunctionPtr > getSpatialFunctionList () const
lsst::afw::geom::Box2I growBBox (lsst::afw::geom::Box2I const &bbox) const
lsst::afw::geom::Box2I shrinkBBox (lsst::afw::geom::Box2I const &bbox) const
void setCtr (lsst::afw::geom::Point2I ctr)
void setCtrX (int ctrX)
void setCtrY (int ctrY)
std::vector< std::vector
< double > > getSpatialParameters () const
bool isSpatiallyVarying () const
void setKernelParameters (std::vector< double > const &params)
void setKernelParameters (std::pair< double, double > const &params)
void setSpatialParameters (const std::vector< std::vector< double > > params)
void computeKernelParametersFromSpatialModel (std::vector< double > &kernelParams, double x, double y) const
void writeFits (std::string const &fileName, std::string const &mode="w") const
void writeFits (fits::MemFileManager &manager, std::string const &mode="w") const
void writeFits (fits::Fits &fitsfile) const
Public Member Functions inherited from lsst::daf::base::Citizen
Citizen (const std::type_info &)
Citizen (Citizen const &)
~Citizen ()
Citizen & operator= (Citizen const &)
std::string repr () const
void markPersistent (void)
memId getId () const
Public Member Functions inherited from lsst::daf::base::Persistable
Persistable (void)
void serialize (Archive &, unsigned int const)
Additional Inherited Members
Static Public Member Functions inherited from lsst::afw::math::AnalyticKernel
static boost::shared_ptr
< AnalyticKernel > readFits (fits::Fits &fitsfile)
static boost::shared_ptr
< AnalyticKernel > readFits (std::string const &fileName, int hdu=0)
static boost::shared_ptr
< AnalyticKernel > readFits (fits::MemFileManager &manager, int hdu=0)
static boost::shared_ptr< Kernel > readFits (fits::Fits &fitsfile)
static boost::shared_ptr< Kernel > readFits (std::string const &fileName, int hdu=0)
static boost::shared_ptr< Kernel > readFits (fits::MemFileManager &manager, int hdu=0)
Public Attributes inherited from lsst::daf::base::Citizen
magicSentinel
Protected Types inherited from lsst::afw::math::AnalyticKernel
typedef io::OutputArchiveHandle OutputArchiveHandle
Protected Member Functions inherited from lsst::afw::math::AnalyticKernel
virtual double doComputeImage (lsst::afw::image::Image< Pixel > &image, bool doNormalize) const
virtual std::string getPersistenceName () const
virtual void write (OutputArchiveHandle &handle) const
virtual void setKernelParameter (unsigned int ind, double value) const
void serialize (Archive &ar, unsigned int const version)
virtual std::string getPythonModule () const
void setKernelParametersFromSpatialModel (double x, double y) const
Persistable ()
Persistable (Persistable const &other)
void operator= (Persistable const &other)
Protected Attributes inherited from lsst::afw::math::AnalyticKernel
KernelFunctionPtr _kernelFunctionPtr
std::vector< SpatialFunctionPtr > _spatialFunctionList
Member Typedef Documentation
typedef lsst::afw::math::AnalyticKernel lsst::meas::algorithms::LocalShapeletKernel::base
typedef boost::shared_ptr<const LocalShapeletKernel> lsst::meas::algorithms::LocalShapeletKernel::ConstPtr
typedef lsst::afw::geom::Extent2I lsst::meas::algorithms::LocalShapeletKernel::Extent
typedef lsst::afw::image::Image<double> lsst::meas::algorithms::LocalShapeletKernel::Image
typedef lsst::afw::geom::Point2D lsst::meas::algorithms::LocalShapeletKernel::Point
typedef boost::shared_ptr<LocalShapeletKernel> lsst::meas::algorithms::LocalShapeletKernel::Ptr
typedef lsst::afw::image::Wcs lsst::meas::algorithms::LocalShapeletKernel::Wcs
Constructor & Destructor Documentation
lsst::meas::algorithms::LocalShapeletKernel::LocalShapeletKernel (Shapelet::ConstPtr shapelet, const Wcs::ConstPtr & wcsPtr, const Extent & size)
Constructor from a Shapelet.
If the size is omitted, then the width and height are automatically calculated from the scale size of the shapelet, going out to 5 sigma.
Default destructor, copy constructor and op= do the right thing. The copy and op= are shallow copies.
The Wcs information is needed because the natural reference frame for describing (and especially interpolating) the Psf is usually in world coordinates rather than chip coordinates. So the dimensional units in the shapelet function are arcsec. This is converted to pixels when constructing an image.
Parameters
shapelet A shapelet function that defines the kernel
wcsPtr The Wcs information for the image
size width/height of Kernel image
lsst::meas::algorithms::LocalShapeletKernel::LocalShapeletKernel (Shapelet::ConstPtr shapelet, const Wcs::ConstPtr & wcsPtr)
Parameters
shapelet A shapelet function that defines the kernel
wcsPtr The Wcs information for the image
Member Function Documentation
double lsst::meas::algorithms::LocalShapeletKernel::computeImage (Image & image, bool doNormalize, double x = 0.0, double y = 0.0) const
Make an image of the kernel.
computeImage can be done more efficiently than the AnalyticKernel version from KernelFunction.
x and y are only present for compatibility with the Kernel version. They are not used for anything.
Parameters
image image whose pixels are to be set (output)
doNormalize normalize the image (so sum is 1)?
x ignored
y ignored
References Assert, lsst::afw::math::AnalyticKernel::getCtrX(), lsst::afw::math::AnalyticKernel::getCtrY(), lsst::afw::math::AnalyticKernel::getHeight(), lsst::afw::math::AnalyticKernel::getWidth(), k, lsst::meas::algorithms::shapelet::makePsi(), sum, and TMV_vview.
The documentation for this class was generated from the following files:
include/lsst/meas/algorithms/ShapeletKernel.h
src/ShapeletKernel.cc