lsst.meas.algorithms: lsst::meas::algorithms::MeasureSources Class Reference
lsst::meas::algorithms::MeasureSources Class Reference
#include <Measure.h>
Public Types
typedef MeasureSourcesBuilder Builder
typedef std::list
< boost::shared_ptr< Algorithm
const > > AlgorithmList
Public Member Functions
AlgorithmList const & getAlgorithms () const
Return the list of algorithms.
template<typename PixelT >
void apply (afw::table::SourceRecord &source, afw::image::Exposure< PixelT > const &exposure, afw::geom::Point2D const &center, bool refineCenter=true) const
Apply the registered algorithms to the given source.
template<typename PixelT >
void apply (afw::table::SourceRecord &source, afw::image::Exposure< PixelT > const &exposure) const
Apply the registered algorithms to the given source.
template<typename PixelT >
void applyWithCoord (afw::table::SourceRecord &source, afw::image::Exposure< PixelT > const &exposure) const
Apply the registered algorithms to the given source.
template<typename PixelT >
void applyWithPixel (afw::table::SourceRecord &source, afw::image::Exposure< PixelT > const &exposure) const
Apply the registered algorithms to the given source.
template<typename PixelT >
void apply (afw::table::SourceRecord &source, afw::image::Exposure< PixelT > const &exposure, afw::table::SourceRecord const &reference, boost::shared_ptr< afw::image::Wcs const > referenceWcs=boost::shared_ptr< afw::image::Wcs const >()) const
Apply the registered algorithms to the given source.
Friends
class MeasureSourcesBuilder
Member Typedef Documentation
typedef std::list<boost::shared_ptr< Algorithm const> > lsst::meas::algorithms::MeasureSources::AlgorithmList
typedef MeasureSourcesBuilder lsst::meas::algorithms::MeasureSources::Builder
Member Function Documentation
template<typename PixelT > void lsst::meas::algorithms::MeasureSources::apply (afw::table::SourceRecord & source, afw::image::Exposure< PixelT > const & exposure, afw::geom::Point2D const & center, bool refineCenter = true) const
Apply the registered algorithms to the given source.
This overload passes a user-defined center to the algorithms. If refineCenter is true and setCentroider has been called, that algorithm will be used to refine the centroid.
If the centroider fails (by setting its flag or returning NaNs), the original center will be used for subsequent measurements and 'flags.badcentroid' will be set.
Referenced by applyWithCoord(), applyWithPixel(), and lsst::meas::algorithms::PsfAttributes::computeGaussianWidth().
template<typename PixelT > void lsst::meas::algorithms::MeasureSources::apply (afw::table::SourceRecord & source, afw::image::Exposure< PixelT > const & exposure) const
Apply the registered algorithms to the given source.
This overload uses the peak position as the center for the algorithms; if setCentroider has been called, that algorithm will refine the centroid.
If the centroider fails (by setting its flag or returning NaNs), the peak will be used for subsequent measurements and 'flags.badcentroid' will be set.
template<typename PixelT > void lsst::meas::algorithms::MeasureSources::apply (afw::table::SourceRecord & source, afw::image::Exposure< PixelT > const & exposure, afw::table::SourceRecord const & reference, boost::shared_ptr< afw::image::Wcs const > referenceWcs = boost::shared_ptr< afw::image::Wcs const >()) const
Apply the registered algorithms to the given source.
This overload uses a reference Source to provide the center and footprint. This is intended for forced photometry (measuring a Source on one image based on its detection in another).
template<typename PixelT > void lsst::meas::algorithms::MeasureSources::applyWithCoord (afw::table::SourceRecord & source, afw::image::Exposure< PixelT > const & exposure) const inline
Apply the registered algorithms to the given source.
This version of apply() uses the sky coordinates as the center for the algorithms; no refinement of the centroid is made.
References apply(), lsst::afw::table::SourceRecord::getCoord(), and lsst::afw::image::Exposure< ImageT, MaskT, VarianceT >::getWcs().
template<typename PixelT > void lsst::meas::algorithms::MeasureSources::applyWithPixel (afw::table::SourceRecord & source, afw::image::Exposure< PixelT > const & exposure) const inline
Apply the registered algorithms to the given source.
This version of apply() uses a previous centroid as the center for the algorithms; no refinement of the centroid is made.
References apply(), lsst::afw::table::SourceRecord::getX(), and lsst::afw::table::SourceRecord::getY().
AlgorithmList const& lsst::meas::algorithms::MeasureSources::getAlgorithms () const inline
Return the list of algorithms.
The order is the same as the order the algorithms will be executed. The special centroider, if present, will always be the first item in this list.
Friends And Related Function Documentation
friend class MeasureSourcesBuilder friend
The documentation for this class was generated from the following file:
include/lsst/meas/algorithms/Measure.h