lsst.meas.algorithms: lsst.meas.algorithms.measurement.SourceMeasurementTask Class Reference
lsst.meas.algorithms.measurement.SourceMeasurementTask Class Reference
Public Member Functions
def __init__
def preMeasureHook
def postMeasureHook
def preSingleMeasureHook
def postSingleMeasureHook
def postSingleMeasurementDisplay
def measure
Public Attributes
measurer
deblendAsPsfKey
Static Public Attributes
ConfigClass SourceMeasurementConfig
run measure
Detailed Description
Measure the properties of sources on a single exposure.
This task has no return value; it only modifies the SourceCatalog in-place.
Constructor & Destructor Documentation
def lsst.meas.algorithms.measurement.SourceMeasurementTask.__init__ (self, schema, algMetadata = None, kwds)
Create the task, adding necessary fields to the given schema.
@param[in,out] schema        Schema object for measurement fields; will be modified in-place.
@param[in,out] algMetadata   Passed to MeasureSources object to be filled with initialization
                     metadata by algorithms (e.g. radii for aperture photometry).
@param         **kwds        Passed to Task.__init__.
Member Function Documentation
def lsst.meas.algorithms.measurement.SourceMeasurementTask.measure (self, exposure, sources, noiseImage = None, noiseMeanVar = None, references = None, refWcs = None)
Measure sources on an exposure, with no aperture correction.
@param[in]     exposure Exposure to process
@param[in,out] sources  SourceCatalog containing sources detected on this exposure.
@param[in]     noiseImage If 'config.doReplaceWithNoise = True', you can pass in
       an Image containing noise.  This overrides the "config.noiseSource" setting.
@param[in]     noiseMeanVar: if 'config.doReplaceWithNoise = True', you can specify
       the mean and variance of the Gaussian noise that will be added, by passing
       a tuple of (mean, variance) floats.  This overrides the "config.noiseSource"
       setting (but is overridden by noiseImage).
@param[in]     references SourceCatalog containing reference sources detected on reference exposure.
@param[in]     refWcs     Wcs for the reference exposure.
@return None
References lsst::pipe::base::task::Task.makeSubtask(), lsst.meas.algorithms.measurement.SourceMeasurementTask.postMeasureHook(), lsst.meas.algorithms.measurement.SourceMeasurementTask.postSingleMeasureHook(), lsst.meas.algorithms.measurement.SourceMeasurementTask.preMeasureHook(), and lsst.meas.algorithms.measurement.SourceMeasurementTask.preSingleMeasureHook().
def lsst.meas.algorithms.measurement.SourceMeasurementTask.postMeasureHook (self, exposure, sources)
A hook, for debugging purposes, that is called at the end of the
measure() method.
Referenced by lsst.meas.algorithms.measurement.SourceMeasurementTask.measure().
def lsst.meas.algorithms.measurement.SourceMeasurementTask.postSingleMeasureHook (self, exposure, sources, i)
A hook, for debugging purposes, that is called immediately after
the measurement algorithms.
References lsst.meas.algorithms.measurement.SourceMeasurementTask.postSingleMeasurementDisplay().
Referenced by lsst.meas.algorithms.measurement.SourceMeasurementTask.measure().
def lsst.meas.algorithms.measurement.SourceMeasurementTask.postSingleMeasurementDisplay (self, exposure, source)
References lsst.meas.algorithms.measurement.SourceMeasurementTask.deblendAsPsfKey.
Referenced by lsst.meas.algorithms.measurement.SourceMeasurementTask.postSingleMeasureHook().
def lsst.meas.algorithms.measurement.SourceMeasurementTask.preMeasureHook (self, exposure, sources)
A hook, for debugging purposes, that is called at the start of the
measure() method.
Referenced by lsst.meas.algorithms.measurement.SourceMeasurementTask.measure().
def lsst.meas.algorithms.measurement.SourceMeasurementTask.preSingleMeasureHook (self, exposure, sources, i)
A hook, for debugging purposes, that is called immediately before
the measurement algorithms for each source.
Note that this will also be called with i=-1 just before entering the
loop over measuring sources.
Referenced by lsst.meas.algorithms.measurement.SourceMeasurementTask.measure().
Member Data Documentation
lsst.meas.algorithms.measurement.SourceMeasurementTask.ConfigClass SourceMeasurementConfig static
lsst.meas.algorithms.measurement.SourceMeasurementTask.deblendAsPsfKey
Referenced by lsst.meas.algorithms.measurement.SourceMeasurementTask.postSingleMeasurementDisplay().
lsst.meas.algorithms.measurement.SourceMeasurementTask.measurer
lsst.meas.algorithms.measurement.SourceMeasurementTask.run measure static
The documentation for this class was generated from the following file:
python/lsst/meas/algorithms/measurement.py