lsst.meas.algorithms: lsst::meas::algorithms::detail Namespace Reference
lsst::meas::algorithms::detail Namespace Reference
Classes
class SdssShapeImpl
class FftShifter
Functions
template<typename ImageT >
bool getAdaptiveMoments (ImageT const &mimage, double bkgd, double xcen, double ycen, double shiftmax, detail::SdssShapeImpl *shape, int maxIter=SDSS_SHAPE_MAX_ITER, float tol1=SDSS_SHAPE_TOL1, float tol2=SDSS_SHAPE_TOL2)
template<typename ImageT >
std::pair< double, double > getFixedMomentsFlux (ImageT const &image,double bkgd,double xcen,double ycen,detail::SdssShapeImpl const &shape_)
Return the flux of an object, using the aperture described by the SdssShape object.
template<typename PixelT >
lsst::afw::image::Image
< PixelT >::Ptr calcImageRealSpace (double const rad1, double const rad2, double const taper=0.1)
template<typename PixelT >
lsst::afw::image::Image
< PixelT >::Ptr calcImageKSpaceReal (double const rad1, double const rad2)
template<typename PixelT >
lsst::afw::image::Image
< PixelT >::Ptr calcImageKSpaceCplx (double const rad1, double const rad2, double const posAng, double const ell)
std::pair< double, double > rotate (double x, double y, double angle)
Variables
int const SDSS_SHAPE_MAX_ITER = 100
float const SDSS_SHAPE_TOL1 = 1.0e-5
float const SDSS_SHAPE_TOL2 = 1.0e-4
Function Documentation
template<typename PixelT > template lsst::afw::image::Image< double >::Ptr lsst::meas::algorithms::detail::calcImageKSpaceCplx< double > (double const rad1, double const rad2, double const posAng, double const ell)
todo
try sub pixel shift if it doesn't break even symmetry
put values directly in an Image
precompute the plan
References lsst::afw::image::Image< PixelT >::getHeight(), k, rotate(), lsst::afw::image::Image< PixelT >::row_begin(), lsst::afw::image::Image< PixelT >::row_end(), lsst::afw::image::Image< PixelT >::setXY0(), and lsst::meas::algorithms::detail::FftShifter::shift().
template<typename PixelT > template lsst::afw::image::Image< double >::Ptr lsst::meas::algorithms::detail::calcImageKSpaceReal< double > (double const rad1, double const rad2)
References lsst::afw::image::Image< PixelT >::getHeight(), k, lsst::afw::image::Image< PixelT >::row_begin(), lsst::afw::image::Image< PixelT >::row_end(), lsst::afw::image::Image< PixelT >::setXY0(), and lsst::meas::algorithms::detail::FftShifter::shift().
template<typename PixelT > template lsst::afw::image::Image< double >::Ptr lsst::meas::algorithms::detail::calcImageRealSpace< double > (double const rad1, double const rad2, double const taper = 0.1)
References lsst::afw::image::Image< PixelT >::getHeight(), lsst::afw::image::Image< PixelT >::row_begin(), lsst::afw::image::Image< PixelT >::row_end(), lsst::afw::image::Image< PixelT >::setXY0(), sum, and lsst::afw::image::Image< PixelT >::writeFits().
template<typename ImageT > bool lsst::meas::algorithms::detail::getAdaptiveMoments (ImageT const & mimage, double bkgd, double xcen, double ycen, double shiftmax, detail::SdssShapeImpl * shape, int maxIter = SDSS_SHAPE_MAX_ITER, float tol1 = SDSS_SHAPE_TOL1, float tol2 = SDSS_SHAPE_TOL2)
Calculate adaptive moments from an image
The moments are measured iteratively with a Gaussian window with width equal to the second moments from the previous iteration.
Workhorse for adaptive moments
Parameters
mimage the data to process
bkgd background level
xcen x-centre of object
ycen y-centre of object
shiftmax max allowed centroid shift
shape a place to store desired data
maxIter Maximum number of iterations
tol1 Convergence tolerance for e1,e2
tol2 Convergence tolerance for FWHM
References lsst::meas::algorithms::detail::SdssShapeImpl::getFlag(), lsst::meas::algorithms::detail::SdssShapeImpl::getIxx(), lsst::meas::algorithms::detail::SdssShapeImpl::getIyy(), lsst::meas::algorithms::detail::SdssShapeImpl::getX(), lsst::meas::algorithms::detail::SdssShapeImpl::getY(), lsst::utils::isnan(), lsst::meas::algorithms::detail::SdssShapeImpl::MAXITER, lsst::afw::image::positionToIndex(), lsst::meas::algorithms::detail::SdssShapeImpl::resetFlag(), lsst::meas::algorithms::detail::SdssShapeImpl::setCovar(), lsst::meas::algorithms::detail::SdssShapeImpl::setFlag(), lsst::meas::algorithms::detail::SdssShapeImpl::setI0(), lsst::meas::algorithms::detail::SdssShapeImpl::setIxx(), lsst::meas::algorithms::detail::SdssShapeImpl::setIxy(), lsst::meas::algorithms::detail::SdssShapeImpl::setIxy4(), lsst::meas::algorithms::detail::SdssShapeImpl::setIyy(), lsst::meas::algorithms::detail::SdssShapeImpl::setX(), lsst::meas::algorithms::detail::SdssShapeImpl::setY(), lsst::meas::algorithms::detail::SdssShapeImpl::SHIFT, sum, lsst::meas::algorithms::detail::SdssShapeImpl::UNWEIGHTED, and lsst::meas::algorithms::detail::SdssShapeImpl::UNWEIGHTED_BAD.
Referenced by lsst::meas::algorithms::ImagePsf::doComputeShape().
template<typename ImageT > std::pair< double, double > lsst::meas::algorithms::detail::getFixedMomentsFlux (ImageT const & image, double bkgd, double xcen, double ycen, detail::SdssShapeImpl const & shape_)
Return the flux of an object, using the aperture described by the SdssShape object.
The SdssShape algorithm calculates an elliptical Gaussian fit to an object, so the "aperture" is an elliptical Gaussian
Returns
A std::pair of the flux and its error
Parameters
image the data to process
bkgd background level
xcen x-centre of object
ycen y-centre of object
shape_ The SdssShape of the object
References lsst::meas::algorithms::detail::SdssShapeImpl::getFluxScale(), lsst::meas::algorithms::detail::SdssShapeImpl::getI0(), lsst::meas::algorithms::detail::SdssShapeImpl::getI0Err(), lsst::meas::algorithms::detail::SdssShapeImpl::getIxx(), lsst::meas::algorithms::detail::SdssShapeImpl::getIxy(), lsst::meas::algorithms::detail::SdssShapeImpl::getIyy(), lsst::meas::algorithms::detail::SdssShapeImpl::setCovar(), and lsst::meas::algorithms::detail::SdssShapeImpl::setI0().
std::pair<double, double> lsst::meas::algorithms::detail::rotate (double x, double y, double angle)
Referenced by calcImageKSpaceCplx().
Variable Documentation
int const lsst::meas::algorithms::detail::SDSS_SHAPE_MAX_ITER = 100
float const lsst::meas::algorithms::detail::SDSS_SHAPE_TOL1 = 1.0e-5
float const lsst::meas::algorithms::detail::SDSS_SHAPE_TOL2 = 1.0e-4