lsst.meas.algorithms: lsst::meas::algorithms::photometry Namespace Reference
lsst::meas::algorithms::photometry Namespace Reference
Classes
struct fuzzyCompare
class SincCoeffs
Functions
template<typename MaskedImageT >
std::pair< double, double > calculateSincApertureFlux (MaskedImageT const &mimage, afw::geom::ellipses::Ellipse const &ellipse, double const innerFactor=0.0)
Function Documentation
template<typename MaskedImageT > std::pair< double, double > lsst::meas::algorithms::photometry::calculateSincApertureFlux (MaskedImageT const & mimage, afw::geom::ellipses::Ellipse const & ellipse, double const innerFactor = 0.0)
Calculate the flux in an elliptical annulus
The outer boundary is defined by an ellipse, while the inner boundary is a scaled version of the outer ellipse.
Workhorse routine to calculate elliptical aperture fluxes
Parameters
mimage Image to measure
ellipse Outer aperture
innerFactor Scale to apply to ellipse for inner boundary
References lsst::afw::geom::Box2I::clip(), CONST_PTR, lsst::meas::algorithms::photometry::SincCoeffs< PixelT >::get(), lsst::afw::geom::ellipses::Ellipse::getCenter(), lsst::afw::geom::ellipses::Ellipse::getCore(), and lsst::afw::geom::Point< T, N >::shift().
Referenced by lsst::meas::algorithms::ImagePsf::doComputeApertureFlux().