lsst.meas.algorithms: lsst.meas.algorithms.detection Namespace Reference
lsst.meas.algorithms.detection Namespace Reference
Classes
class BackgroundConfig
class SourceDetectionConfig
class SourceDetectionTask
Functions
def addExposures
def getBackground
def estimateBackground
Variables
tuple __all__
Function Documentation
def lsst.meas.algorithms.detection.addExposures (exposureList)
Add a set of exposures together.
Assumes that all exposures in set have the same dimensions
def lsst.meas.algorithms.detection.estimateBackground (exposure, backgroundConfig, subtract = True, stats = True, statsKeys = None)
Estimate exposure's background using parameters in backgroundConfig.
If subtract is true, make a copy of the exposure and subtract the background.
If `stats` is True, measure the mean and variance of the background and
add them to the background-subtracted exposure's metadata with keys
"BGMEAN" and "BGVAR", or the keys given in `statsKeys` (2-tuple of strings).
Return background, backgroundSubtractedExposure
References lsst.meas.algorithms.detection.getBackground(), and lsst::afw::math.makeStatistics().
Referenced by lsst.meas.algorithms.detection.getBackground().
def lsst.meas.algorithms.detection.getBackground (image, backgroundConfig, nx = 0, ny = 0, algorithm = None)
Make a new Exposure which is exposure - background
References lsst.meas.algorithms.detection.estimateBackground(), and lsst::afw::math.makeBackground().
Referenced by lsst.meas.algorithms.detection.SourceDetectionTask.detectFootprints(), and lsst.meas.algorithms.detection.estimateBackground().
Variable Documentation
tuple lsst.meas.algorithms.detection.__all__
Initial value:
 ("SourceDetectionConfig", "SourceDetectionTask", "getBackground",
            "estimateBackground", "BackgroundConfig", "addExposures")