lsst.meas.algorithms: lsst::meas::algorithms::shapelet Namespace Reference
lsst::meas::algorithms::shapelet Namespace Reference
Classes
class Position
class Bounds
class AssignableToBVec
class BVec
class ConvertibleString
class ConfigFile
class Ellipse
class EllipseSolver3
class FittedPsf
class FittedPsfAtXY
class Form
struct BoundForm
struct RangeException
class Function2D
class Constant2D
class Polynomial2D
class Histogram
class Legendre2D
class NLSolver
struct FileNotFoundException
struct ParameterException
struct ReadException
struct WriteException
struct ProcessingException
class Pixel
class PixelList
class PotentialStar
class SizeMagnitudeStarSelectorException
class SizeMagnitudeStarSelectorAlgo
class CrudeSolver
struct PixelListSorter
Typedefs
typedef Eigen::VectorXd DVector
typedef Eigen::Block< DVector,
Eigen::Dynamic, 1 > DVectorView
typedef const DVectorView DConstVectorView
typedef Eigen::MatrixXd DMatrix
typedef Eigen::Block< DMatrix > DMatrixView
typedef const DMatrixView DConstMatrixView
typedef Eigen::Matrix< double, 2, 2 > DSmallMatrix22
typedef Eigen::RowVectorXd DRowVector
typedef Eigen::MatrixXd DBandMatrix
typedef Eigen::VectorXcd CDVector
typedef Eigen::Block< CDVector,
Eigen::Dynamic, 1 > CDVectorView
typedef const CDVectorView CDConstVectorView
typedef Eigen::MatrixXcd CDMatrix
typedef Eigen::Block< CDMatrix > CDMatrixView
typedef const CDMatrixView CDConstMatrixView
typedef Eigen::VectorXf FVector
typedef Eigen::Block< FVector,
Eigen::Dynamic, 1 > FVectorView
typedef const FVectorView FConstVectorView
typedef Eigen::MatrixXf FMatrix
typedef Eigen::Block< FMatrix > FMatrixView
typedef const FMatrixView FConstMatrixView
typedef Eigen::Matrix< float, 2, 2 > FSmallMatrix22
typedef Eigen::VectorXcf CFVector
typedef Eigen::Block< CFVector,
Eigen::Dynamic, 1 > CFVectorView
typedef const CFVectorView CFConstVectorView
typedef Eigen::MatrixXcf CFMatrix
typedef Eigen::Block< CFMatrix > CFMatrixView
typedef const CFMatrixView CFConstMatrixView
typedef DVector DDiagMatrix
typedef DMatrix DSymMatrix
Enumerations
enum ExitCode {
SUCCESS = 0, FAILURE, FAILURE_FILE_NOT_FOUND, FAILURE_PARAMETER_ERROR,
FAILURE_READ_ERROR, FAILURE_WRITE_ERROR, FAILURE_PROCESSING_ERROR
}
Functions
double fact (int i)
double sqrtfact (int i)
double binom (int i, int j)
double sqrtn (int i)
std::complex< double > operator- (const std::complex< double > &z1, const Position &p2)
std::complex< double > operator/ (const Position &p1, double x)
std::ostream & operator<< (std::ostream &os, const Position &pos)
std::istream & operator>> (std::istream &os, Position &pos)
std::ostream & operator<< (std::ostream &fout, const Bounds &b)
std::istream & operator>> (std::istream &fin, Bounds &b)
std::ostream & operator<< (std::ostream &os, const BVec &b)
void calculateZTransform (std::complex< double > z, int order1, int order2, DMatrix &T)
void calculateZTransform (std::complex< double > z, int order, DMatrix &T)
void augmentZTransformCols (std::complex< double > z, int order, DMatrix &T)
void applyZ (std::complex< double > z, BVec &b)
void calculateMuTransform (double mu, int order1, int order2, DMatrix &D)
void calculateMuTransform (double mu, int order, DMatrix &D)
void augmentMuTransformRows (double mu, int order, DMatrix &D)
void augmentMuTransformCols (double mu, int order, DMatrix &D)
void applyMu (double mu, BVec &b)
void calculateThetaTransform (double theta, int order1, int order2, DBandMatrix &R)
void calculateThetaTransform (double theta, int order, DBandMatrix &R)
void applyTheta (double theta, BVec &b)
void calculateGTransform (std::complex< double > g, int order1, int order2, DMatrix &S)
void calculateGTransform (std::complex< double > g, int order, DMatrix &S)
void augmentGTransformCols (std::complex< double > g, int order, DMatrix &S)
void applyG (std::complex< double > g, BVec &b)
void calculatePsfConvolve (const BVec &bpsf, int order1, int order2, double sigma, DMatrix &C)
void calculatePsfConvolve (const BVec &bpsf, int order, double sigma, DMatrix &C)
void applyPsf (const BVec &bpsf, BVec &b)
std::ostream & operator<< (std::ostream &os, const ConfigFile &cf)
std::istream & operator>> (std::istream &is, ConfigFile &cf)
std::ostream & operator<< (std::ostream &os, const Ellipse &s)
std::complex< double > addShears (const std::complex< double > g1, const std::complex< double > g2)
void CalculateShift (std::complex< double > c1, std::complex< double > g1, std::complex< double > m1, std::complex< double > c2, std::complex< double > g2, std::complex< double > m2, std::complex< double > &c3, std::complex< double > &g3, std::complex< double > &m3)
void setupFloat (std::ostream &s, const Form &f)
void setupInt (std::ostream &s, const Form &f)
void setup (std::ostream &os, const BoundForm< double > &bf)
void setup (std::ostream &os, const BoundForm< long double > &bf)
void setup (std::ostream &os, const BoundForm< float > &bf)
void setup (std::ostream &os, const BoundForm< std::complex< double > > &bf)
void setup (std::ostream &os, const BoundForm< std::complex< long double > > &bf)
void setup (std::ostream &os, const BoundForm< std::complex< float > > &bf)
void setup (std::ostream &os, const BoundForm< int > &bf)
void setup (std::ostream &os, const BoundForm< short > &bf)
void setup (std::ostream &os, const BoundForm< long > &bf)
void setup (std::ostream &os, const BoundForm< unsigned int > &bf)
void setup (std::ostream &os, const BoundForm< unsigned short > &bf)
void setup (std::ostream &os, const BoundForm< unsigned long > &bf)
template<typename T >
void setup (std::ostream &os, const BoundForm< T > &bf)
template<typename T >
std::ostream & operator<< (std::ostream &os, const BoundForm< T > &bf)
std::ostream & operator<< (std::ostream &fout, const Function2D &f)
std::istream & operator>> (std::istream &fin, std::auto_ptr< Function2D > &f)
void PrintFlags (const std::vector< long > &flags, std::ostream &os)
const char * Text (const ExitCode &code)
int Status (ExitCode code, const ConfigFile &params)
void getSubPixList (PixelList &pix, const PixelList &allPix, std::complex< double > cen_offset, std::complex< double > shear, double aperture, long &flag)
void getSubPixList (PixelList &pix, const PixelList &allPix, std::complex< double > cen_offset, double aperture, long &flag)
void getSubPixList (PixelList &pix, const PixelList &allPix, double aperture, long &flag)
void makePsi (DMatrix &psi, CDVectorView z, int order, const DVector *coeff=0)
void makePsi (DVector &psi, std::complex< double > z, int order)
void augmentPsi (DMatrix &psi, CDVectorView z, int order)
void setupGx (DMatrix &Gx, int order1, int order2)
void setupGy (DMatrix &Gy, int order1, int order2)
void setupGg1 (DMatrix &Gg1, int order1, int order2)
void setupGg2 (DMatrix &Gg2, int order1, int order2)
void setupGmu (DMatrix &Gmu, int order1, int order2)
void setupGth (DMatrix &Gth, int order1, int order2)
int fitSize (const int xOrder, const int yOrder)
double absSq (const double &x)
double betai (double a, double b, double x)
bool Equivalent (double chisq1, double chisq2, int n1, int n2, double equivProb)
double betacf (double a, double b, double x)
double gammln (double x)
Typedef Documentation
typedef const CDMatrixView lsst::meas::algorithms::shapelet::CDConstMatrixView
typedef const CDVectorView lsst::meas::algorithms::shapelet::CDConstVectorView
typedef Eigen::MatrixXcd lsst::meas::algorithms::shapelet::CDMatrix
typedef Eigen::Block<CDMatrix> lsst::meas::algorithms::shapelet::CDMatrixView
typedef Eigen::VectorXcd lsst::meas::algorithms::shapelet::CDVector
typedef Eigen::Block<CDVector,Eigen::Dynamic,1> lsst::meas::algorithms::shapelet::CDVectorView
typedef const CFMatrixView lsst::meas::algorithms::shapelet::CFConstMatrixView
typedef const CFVectorView lsst::meas::algorithms::shapelet::CFConstVectorView
typedef Eigen::MatrixXcf lsst::meas::algorithms::shapelet::CFMatrix
typedef Eigen::Block<CFMatrix> lsst::meas::algorithms::shapelet::CFMatrixView
typedef Eigen::VectorXcf lsst::meas::algorithms::shapelet::CFVector
typedef Eigen::Block<CFVector,Eigen::Dynamic,1> lsst::meas::algorithms::shapelet::CFVectorView
typedef Eigen::MatrixXd lsst::meas::algorithms::shapelet::DBandMatrix
typedef const DMatrixView lsst::meas::algorithms::shapelet::DConstMatrixView
typedef const DVectorView lsst::meas::algorithms::shapelet::DConstVectorView
typedef DVector lsst::meas::algorithms::shapelet::DDiagMatrix
typedef Eigen::MatrixXd lsst::meas::algorithms::shapelet::DMatrix
typedef Eigen::Block<DMatrix> lsst::meas::algorithms::shapelet::DMatrixView
typedef Eigen::RowVectorXd lsst::meas::algorithms::shapelet::DRowVector
typedef Eigen::Matrix<double,2,2> lsst::meas::algorithms::shapelet::DSmallMatrix22
typedef DMatrix lsst::meas::algorithms::shapelet::DSymMatrix
typedef Eigen::VectorXd lsst::meas::algorithms::shapelet::DVector
typedef Eigen::Block<DVector,Eigen::Dynamic,1> lsst::meas::algorithms::shapelet::DVectorView
typedef const FMatrixView lsst::meas::algorithms::shapelet::FConstMatrixView
typedef const FVectorView lsst::meas::algorithms::shapelet::FConstVectorView
typedef Eigen::MatrixXf lsst::meas::algorithms::shapelet::FMatrix
typedef Eigen::Block<FMatrix> lsst::meas::algorithms::shapelet::FMatrixView
typedef Eigen::Matrix<float,2,2> lsst::meas::algorithms::shapelet::FSmallMatrix22
typedef Eigen::VectorXf lsst::meas::algorithms::shapelet::FVector
typedef Eigen::Block<FVector,Eigen::Dynamic,1> lsst::meas::algorithms::shapelet::FVectorView
Enumeration Type Documentation
enum lsst::meas::algorithms::shapelet::ExitCode
Enumerator:
SUCCESS
FAILURE
FAILURE_FILE_NOT_FOUND
FAILURE_PARAMETER_ERROR
FAILURE_READ_ERROR
FAILURE_WRITE_ERROR
FAILURE_PROCESSING_ERROR
Function Documentation
double lsst::meas::algorithms::shapelet::absSq (const double & x) inline
Referenced by lsst::meas::algorithms::shapelet::Function2D::outlierFit().
std::complex<double> lsst::meas::algorithms::shapelet::addShears (const std::complex< double > g1, const std::complex< double > g2)
void lsst::meas::algorithms::shapelet::applyG (std::complex< double > g, BVec & b)
References calculateGTransform(), lsst::meas::algorithms::shapelet::BVec::getOrder(), lsst::meas::algorithms::shapelet::BVec::size(), and lsst::meas::algorithms::shapelet::BVec::vec().
void lsst::meas::algorithms::shapelet::applyMu (double mu, BVec & b)
References calculateMuTransform(), lsst::meas::algorithms::shapelet::BVec::getOrder(), lsst::meas::algorithms::shapelet::BVec::size(), and lsst::meas::algorithms::shapelet::BVec::vec().
void lsst::meas::algorithms::shapelet::applyPsf (const BVec & bpsf, BVec & b)
References calculatePsfConvolve(), lsst::meas::algorithms::shapelet::BVec::getOrder(), lsst::meas::algorithms::shapelet::BVec::getSigma(), lsst::meas::algorithms::shapelet::BVec::size(), and lsst::meas::algorithms::shapelet::BVec::vec().
void lsst::meas::algorithms::shapelet::applyTheta (double theta, BVec & b)
References calculateThetaTransform(), lsst::meas::algorithms::shapelet::BVec::getOrder(), lsst::meas::algorithms::shapelet::BVec::size(), and lsst::meas::algorithms::shapelet::BVec::vec().
void lsst::meas::algorithms::shapelet::applyZ (std::complex< double > z, BVec & b)
References calculateZTransform(), lsst::meas::algorithms::shapelet::BVec::getOrder(), lsst::meas::algorithms::shapelet::BVec::getSigma(), lsst::meas::algorithms::shapelet::BVec::size(), and lsst::meas::algorithms::shapelet::BVec::vec().
void lsst::meas::algorithms::shapelet::augmentGTransformCols (std::complex< double > g, int order, DMatrix & S)
References Assert, sqrtn(), and TMV_ptr.
Referenced by lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::doJ3().
void lsst::meas::algorithms::shapelet::augmentMuTransformCols (double mu, int order, DMatrix & D)
References Assert, sqrtn(), and TMV_ptr.
Referenced by lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::doJ2(), and lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::doJ3().
void lsst::meas::algorithms::shapelet::augmentMuTransformRows (double mu, int order, DMatrix & D)
References Assert, sqrtn(), and TMV_ptr.
void lsst::meas::algorithms::shapelet::augmentPsi (DMatrix & psi, CDVectorView z, int order)
References Assert, k, TMV_colRange, TMV_cptr, and TMV_ptr.
void lsst::meas::algorithms::shapelet::augmentZTransformCols (std::complex< double > z, int order, DMatrix & T)
References Assert, sqrtn(), TMV_ptr, and TMV_stepj.
Referenced by lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::doJ1(), lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::doJ2(), and lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::doJ3().
double lsst::meas::algorithms::shapelet::betacf (double a, double b, double x) inline
References b, EPS, FPMIN, and MAXIT.
Referenced by betai().
double lsst::meas::algorithms::shapelet::betai (double a, double b, double x) inline
References b, betacf(), and gammln().
Referenced by Equivalent().
double lsst::meas::algorithms::shapelet::binom (int i, int j)
Referenced by lsst::meas::algorithms::shapelet::Polynomial2D::linearPreTransform().
void lsst::meas::algorithms::shapelet::calculateGTransform (std::complex< double > g, int order1, int order2, DMatrix & S)
References Assert, sqrtn(), and TMV_ptr.
Referenced by applyG(), calculateGTransform(), lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::doF3(), lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::doJ3(), and lsst::meas::algorithms::shapelet::EllipseSolver3::solve().
void lsst::meas::algorithms::shapelet::calculateGTransform (std::complex< double > g, int order, DMatrix & S) inline
References calculateGTransform().
void lsst::meas::algorithms::shapelet::calculateMuTransform (double mu, int order1, int order2, DMatrix & D)
References Assert, sqrtn(), and TMV_ptr.
Referenced by applyMu(), calculateMuTransform(), lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::doF2(), lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::doF3(), lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::doJ3(), and lsst::meas::algorithms::shapelet::EllipseSolver3::solve().
void lsst::meas::algorithms::shapelet::calculateMuTransform (double mu, int order, DMatrix & D) inline
References calculateMuTransform().
void lsst::meas::algorithms::shapelet::calculatePsfConvolve (const BVec & bpsf, int order1, int order2, double sigma, DMatrix & C)
References Assert, lsst::meas::algorithms::shapelet::BVec::getOrder(), lsst::meas::algorithms::shapelet::BVec::getSigma(), lsst::meas::algorithms::shapelet::BVec::size(), sqrtn(), TMV_cptr, TMV_ptr, lsst::meas::algorithms::shapelet::BVec::vec(), and w.
Referenced by applyPsf(), and calculatePsfConvolve().
void lsst::meas::algorithms::shapelet::calculatePsfConvolve (const BVec & bpsf, int order, double sigma, DMatrix & C) inline
References calculatePsfConvolve().
void lsst::meas::algorithms::shapelet::CalculateShift (std::complex< double > c1, std::complex< double > g1, std::complex< double > m1, std::complex< double > c2, std::complex< double > g2, std::complex< double > m2, std::complex< double > & c3, std::complex< double > & g3, std::complex< double > & m3)
References dbg, norm(), and X.
Referenced by lsst::meas::algorithms::shapelet::Ellipse::postShiftBy(), and lsst::meas::algorithms::shapelet::Ellipse::preShiftBy().
void lsst::meas::algorithms::shapelet::calculateThetaTransform (double theta, int order1, int order2, DBandMatrix & R)
References Assert, and real().
Referenced by applyTheta(), and calculateThetaTransform().
void lsst::meas::algorithms::shapelet::calculateThetaTransform (double theta, int order, DBandMatrix & R) inline
References calculateThetaTransform().
void lsst::meas::algorithms::shapelet::calculateZTransform (std::complex< double > z, int order1, int order2, DMatrix & T)
References Assert, sqrtn(), TMV_ptr, and TMV_stepj.
Referenced by applyZ(), calculateZTransform(), lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::doF1(), lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::doF2(), lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::doF3(), lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::doJ3(), and lsst::meas::algorithms::shapelet::EllipseSolver3::solve().
void lsst::meas::algorithms::shapelet::calculateZTransform (std::complex< double > z, int order, DMatrix & T) inline
References calculateZTransform().
bool lsst::meas::algorithms::shapelet::Equivalent (double chisq1, double chisq2, int n1, int n2, double equivProb) inline
References Assert, and betai().
Referenced by lsst::meas::algorithms::shapelet::Function2D::orderFit().
double lsst::meas::algorithms::shapelet::fact (int i)
Referenced by lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::doJ3().
int lsst::meas::algorithms::shapelet::fitSize (const int xOrder, const int yOrder) inline
Referenced by lsst::meas::algorithms::shapelet::Function2D::orderFit(), lsst::meas::algorithms::shapelet::Function2D::outlierFit(), and lsst::meas::algorithms::shapelet::Function2D::simpleFit().
double lsst::meas::algorithms::shapelet::gammln (double x) inline
Referenced by betai().
void lsst::meas::algorithms::shapelet::getSubPixList (PixelList & pix, const PixelList & allPix, std::complex< double > cen_offset, std::complex< double > shear, double aperture, long & flag)
References Assert, lsst::meas::algorithms::shapelet::Pixel::getFlux(), lsst::meas::algorithms::shapelet::Pixel::getPos(), norm(), real(), lsst::meas::algorithms::shapelet::PixelList::resize(), lsst::meas::algorithms::shapelet::Pixel::setPos(), lsst::meas::algorithms::shapelet::PixelList::size(), and xdbg.
Referenced by getSubPixList().
void lsst::meas::algorithms::shapelet::getSubPixList (PixelList & pix, const PixelList & allPix, std::complex< double > cen_offset, double aperture, long & flag) inline
References getSubPixList().
void lsst::meas::algorithms::shapelet::getSubPixList (PixelList & pix, const PixelList & allPix, double aperture, long & flag) inline
References getSubPixList().
void lsst::meas::algorithms::shapelet::makePsi (DMatrix & psi, CDVectorView z, int order, const DVector * coeff = 0)
References Assert, k, TMV_colRange, TMV_cptr, and TMV_ptr.
Referenced by lsst::meas::algorithms::LocalShapeletKernel::computeImage(), and lsst::meas::algorithms::ShapeletImpl::evaluateAt().
void lsst::meas::algorithms::shapelet::makePsi (DVector & psi, std::complex< double > z, int order)
std::complex<double> lsst::meas::algorithms::shapelet::operator- (const std::complex< double > & z1, const Position & p2) inline
std::complex<double> lsst::meas::algorithms::shapelet::operator/ (const Position & p1, double x) inline
std::ostream& lsst::meas::algorithms::shapelet::operator<< (std::ostream & os, const Position & pos) inline
References lsst::meas::algorithms::shapelet::Position::write().
std::ostream& lsst::meas::algorithms::shapelet::operator<< (std::ostream & os, const BVec & b) inline
References lsst::meas::algorithms::shapelet::BVec::getOrder(), lsst::meas::algorithms::shapelet::BVec::getSigma(), and lsst::meas::algorithms::shapelet::BVec::vec().
std::ostream& lsst::meas::algorithms::shapelet::operator<< (std::ostream & fout, const Function2D & f) inline
References lsst::meas::algorithms::shapelet::Function2D::write().
template<typename T > std::ostream& lsst::meas::algorithms::shapelet::operator<< (std::ostream & os, const BoundForm< T > & bf) inline
References setup().
std::ostream& lsst::meas::algorithms::shapelet::operator<< (std::ostream & fout, const Bounds & b) inline
References lsst::meas::algorithms::shapelet::Bounds::write().
std::ostream& lsst::meas::algorithms::shapelet::operator<< (std::ostream & os, const Ellipse & s) inline
References lsst::meas::algorithms::shapelet::Ellipse::write().
std::ostream& lsst::meas::algorithms::shapelet::operator<< (std::ostream & os, const ConfigFile & cf) inline
References lsst::meas::algorithms::shapelet::ConfigFile::write().
std::istream& lsst::meas::algorithms::shapelet::operator>> (std::istream & os, Position & pos) inline
References lsst::meas::algorithms::shapelet::Position::read().
std::istream& lsst::meas::algorithms::shapelet::operator>> (std::istream & fin, std::auto_ptr< Function2D > & f) inline
References lsst::meas::algorithms::shapelet::Function2D::read().
std::istream& lsst::meas::algorithms::shapelet::operator>> (std::istream & fin, Bounds & b) inline
References lsst::meas::algorithms::shapelet::Bounds::read().
std::istream& lsst::meas::algorithms::shapelet::operator>> (std::istream & is, ConfigFile & cf) inline
References lsst::meas::algorithms::shapelet::ConfigFile::read().
void lsst::meas::algorithms::shapelet::PrintFlags (const std::vector< long > & flags, std::ostream & os)
void lsst::meas::algorithms::shapelet::setup (std::ostream & os, const BoundForm< double > & bf) inline
References lsst::meas::algorithms::shapelet::BoundForm< T >::f, and setupFloat().
Referenced by operator<<().
void lsst::meas::algorithms::shapelet::setup (std::ostream & os, const BoundForm< long double > & bf) inline
References lsst::meas::algorithms::shapelet::BoundForm< T >::f, and setupFloat().
void lsst::meas::algorithms::shapelet::setup (std::ostream & os, const BoundForm< float > & bf) inline
References lsst::meas::algorithms::shapelet::BoundForm< T >::f, and setupFloat().
void lsst::meas::algorithms::shapelet::setup (std::ostream & os, const BoundForm< std::complex< double > > & bf) inline
References setupFloat().
void lsst::meas::algorithms::shapelet::setup (std::ostream & os, const BoundForm< std::complex< long double > > & bf) inline
References setupFloat().
void lsst::meas::algorithms::shapelet::setup (std::ostream & os, const BoundForm< std::complex< float > > & bf) inline
References setupFloat().
void lsst::meas::algorithms::shapelet::setup (std::ostream & os, const BoundForm< int > & bf) inline
References lsst::meas::algorithms::shapelet::BoundForm< T >::f, and setupInt().
void lsst::meas::algorithms::shapelet::setup (std::ostream & os, const BoundForm< short > & bf) inline
References lsst::meas::algorithms::shapelet::BoundForm< T >::f, and setupInt().
void lsst::meas::algorithms::shapelet::setup (std::ostream & os, const BoundForm< long > & bf) inline
References lsst::meas::algorithms::shapelet::BoundForm< T >::f, and setupInt().
void lsst::meas::algorithms::shapelet::setup (std::ostream & os, const BoundForm< unsigned int > & bf) inline
References lsst::meas::algorithms::shapelet::BoundForm< T >::f, and setupInt().
void lsst::meas::algorithms::shapelet::setup (std::ostream & os, const BoundForm< unsigned short > & bf) inline
References lsst::meas::algorithms::shapelet::BoundForm< T >::f, and setupInt().
void lsst::meas::algorithms::shapelet::setup (std::ostream & os, const BoundForm< unsigned long > & bf) inline
References lsst::meas::algorithms::shapelet::BoundForm< T >::f, and setupInt().
template<typename T > void lsst::meas::algorithms::shapelet::setup (std::ostream & os, const BoundForm< T > & bf) inline
References lsst::meas::algorithms::shapelet::BoundForm< T >::f, and setupFloat().
void lsst::meas::algorithms::shapelet::setupFloat (std::ostream & s, const Form & f) inline
Referenced by setup().
void lsst::meas::algorithms::shapelet::setupGg1 (DMatrix & Gg1, int order1, int order2)
References Assert, and k.
Referenced by lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::doJ3(), and lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::ESImpl3().
void lsst::meas::algorithms::shapelet::setupGg2 (DMatrix & Gg2, int order1, int order2)
References Assert, and k.
Referenced by lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::doJ3(), and lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::ESImpl3().
void lsst::meas::algorithms::shapelet::setupGmu (DMatrix & Gmu, int order1, int order2)
References Assert, and k.
Referenced by lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::doJ3(), and lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::ESImpl3().
void lsst::meas::algorithms::shapelet::setupGth (DMatrix & Gth, int order1, int order2)
References Assert, and k.
Referenced by lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::doJ3(), and lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::ESImpl3().
void lsst::meas::algorithms::shapelet::setupGx (DMatrix & Gx, int order1, int order2)
References Assert, and k.
Referenced by lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::doJ3(), and lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::ESImpl3().
void lsst::meas::algorithms::shapelet::setupGy (DMatrix & Gy, int order1, int order2)
References Assert, and k.
Referenced by lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::doJ3(), and lsst::meas::algorithms::shapelet::EllipseSolver3::ESImpl3::ESImpl3().
void lsst::meas::algorithms::shapelet::setupInt (std::ostream & s, const Form & f) inline
Referenced by setup().
double lsst::meas::algorithms::shapelet::sqrtfact (int i)
double lsst::meas::algorithms::shapelet::sqrtn (int i)
Referenced by augmentGTransformCols(), augmentMuTransformCols(), augmentMuTransformRows(), augmentZTransformCols(), calculateGTransform(), calculateMuTransform(), calculatePsfConvolve(), and calculateZTransform().
int lsst::meas::algorithms::shapelet::Status (ExitCode code, const ConfigFile & params)
References FAILURE, FAILURE_FILE_NOT_FOUND, FAILURE_PARAMETER_ERROR, FAILURE_PROCESSING_ERROR, FAILURE_READ_ERROR, FAILURE_WRITE_ERROR, lsst::meas::algorithms::shapelet::ConfigFile::read(), and SUCCESS.
const char * lsst::meas::algorithms::shapelet::Text (const ExitCode & code)
References FAILURE, FAILURE_FILE_NOT_FOUND, FAILURE_PARAMETER_ERROR, FAILURE_PROCESSING_ERROR, FAILURE_READ_ERROR, FAILURE_WRITE_ERROR, and SUCCESS.