lsst.meas.algorithms: lsst.meas.algorithms.utils Namespace Reference
lsst.meas.algorithms.utils Namespace Reference
Functions
def splitId
def showSourceSet
def showPsfSpatialCells
def showPsfCandidates
def makeSubplots
def plotPsfSpatialModel
def showPsf
def showPsfMosaic
def showPsfResiduals
def saveSpatialCellSet
Variables
keptPlots False
plt None
Function Documentation
def lsst.meas.algorithms.utils.makeSubplots (fig, nx = 2, ny = 2, Nx = 1, Ny = 1, plottingArea = (0.1, 0.1, pxgutter = 0.05, pygutter = 0.05, xgutter = 0.04, ygutter = 0.04, headroom = 0.0, panelBorderWeight = 0, panelColor = 'black')
Return a generator of a set of subplots, a set of Nx*Ny panels of nx*ny plots.  Each panel is fully
filled by row (starting in the bottom left) before the next panel is started.  If panelBorderWidth is
greater than zero a border is drawn around each panel, adjusted to enclose the axis labels.
E.g.
subplots = makeSubplots(fig, 2, 2, Nx=1, Ny=1, panelColor='k')
ax = subplots.next(); ax.text(0.3, 0.5, '[0, 0] (0,0)')
ax = subplots.next(); ax.text(0.3, 0.5, '[0, 0] (1,0)')
ax = subplots.next(); ax.text(0.3, 0.5, '[0, 0] (0,1)')
ax = subplots.next(); ax.text(0.3, 0.5, '[0, 0] (1,1)')
fig.show()
@param fig    The matplotlib figure to draw
@param nx     The number of plots in each row of each panel
@param ny     The number of plots in each column of each panel
@param Nx     The number of panels in each row of the figure
@param Ny     The number of panels in each column of the figure
@param plottingArea  (x0, y0, x1, y1) for the part of the figure containing all the panels
@param pxgutter Spacing between columns of panels in units of (x1 - x0)
@param pygutter Spacing between rows of panels in units of (y1 - y0)
@param xgutter  Spacing between columns of plots within a panel in units of (x1 - x0)
@param ygutter  Spacing between rows of plots within a panel in units of (y1 - y0)
@param headroom Extra spacing above each plot for e.g. a title
@param panelBorderWeight Width of border drawn around panels
@param panelColor Colour of border around panels
References lsst.meas.algorithms.utils.plotPsfSpatialModel().
Referenced by lsst.meas.algorithms.utils.plotPsfSpatialModel().
def lsst.meas.algorithms.utils.plotPsfSpatialModel (exposure, psf, psfCellSet, showBadCandidates = True, numSample = 128, matchKernelAmplitudes = False, keepPlots = True)
Plot the PSF spatial model.
References lsst.meas.algorithms.utils.makeSubplots().
Referenced by lsst.meas.algorithms.utils.makeSubplots().
def lsst.meas.algorithms.utils.saveSpatialCellSet (psfCellSet, fileName = "foo.fits", frame = None)
Write the contents of a SpatialCellSet to a many-MEF fits file
References lsst::afw::math.offsetImage(), and lsst::afw::image.positionToIndex().
def lsst.meas.algorithms.utils.showPsf (psf, eigenValues = None, XY = None, normalize = True, frame = None)
Display a PSF's eigen images
If normalize is True, set the largest absolute value of each eigenimage to 1.0 (n.b. sum == 0.0 for i > 0)
References lsst.meas.algorithms.utils.showPsfMosaic().
def lsst.meas.algorithms.utils.showPsfCandidates (exposure, psfCellSet, psf = None, frame = None, normalize = True, showBadCandidates = True, variance = None, chi = None)
Display the PSF candidates.
If psf is provided include PSF model and residuals;  if normalize is true normalize the PSFs (and residuals)
If chi is True, generate a plot of residuals/sqrt(variance), i.e. chi
References lsst::afw::math.makeStatistics(), lsst::afw::math.randomGaussianImage(), and lsst.meas.algorithms.utils.splitId().
Referenced by lsst.meas.algorithms.utils.showPsfSpatialCells().
def lsst.meas.algorithms.utils.showPsfMosaic (exposure, psf = None, nx = 7, ny = None, showCenter = True, showEllipticity = False, showFwhm = False, stampSize = 0, frame = None, title = None)
Show a mosaic of Psf images.  exposure may be an Exposure (optionally with PSF), or a tuple (width, height)
If stampSize is > 0, the psf images will be trimmed to stampSize*stampSize
References lsst::afw::image.makeExposure(), and lsst::afw::image.makeMaskedImage().
Referenced by lsst.meas.algorithms.utils.showPsf().
def lsst.meas.algorithms.utils.showPsfResiduals (exposure, sourceSet, magType = "psf", scale = 10, frame = None, showAmps = False)
def lsst.meas.algorithms.utils.showPsfSpatialCells (exposure, psfCellSet, nMaxPerCell = -1, showChi2 = False, showMoments = False, symb = None, ctype = None, ctypeUnused = None, ctypeBad = None, size = 2, frame = None)
Show the SpatialCells.  If symb is something that ds9.dot understands (e.g. "o"), the top nMaxPerCell candidates will be indicated with that symbol, using ctype and size
References lsst.meas.algorithms.utils.showPsfCandidates(), and lsst.meas.algorithms.utils.splitId().
Referenced by lsst.meas.algorithms.utils.showSourceSet().
def lsst.meas.algorithms.utils.showSourceSet (sSet, xy0 = (0, 0, frame = 0, ctype = ds9.GREEN, symb = "+", size = 2)
Draw the (XAstrom, YAstrom) positions of a set of Sources.  Image has the given XY0
References lsst.meas.algorithms.utils.showPsfSpatialCells(), and lsst.meas.algorithms.utils.splitId().
def lsst.meas.algorithms.utils.splitId (oid, asDict = True)
Referenced by lsst.meas.algorithms.utils.showPsfCandidates(), lsst.meas.algorithms.utils.showPsfSpatialCells(), and lsst.meas.algorithms.utils.showSourceSet().
Variable Documentation
lsst.meas.algorithms.utils.keptPlots False
lsst.meas.algorithms.utils.plt None