lsst.meas.algorithms: lsst::meas::algorithms Namespace Reference
lsst::meas::algorithms Namespace Reference
Namespaces
namespace algorithmRegistry
namespace deblend
namespace defects
namespace detail
namespace detection
namespace findCosmicRaysConfig
namespace interp
namespace measurement
namespace measureSourceUtils
namespace objectSizeStarSelector
namespace pcaPsfDeterminer
namespace photometry
namespace psfDeterminerRegistry
namespace psfSelectionFromMatchList
namespace replaceWithNoise
namespace secondMomentStarSelector
namespace shapelet
namespace sizeMagnitudeStarSelectorFactory
namespace starSelectorRegistry
namespace testUtils
namespace utils
namespace version
Classes
class Algorithm
Base class for source measurement algorithms.
class AlgorithmControl
Base class for measurement algorithm control objects.
class ApertureFlux
A class that knows how to calculate fluxes as a simple sum over a Footprint.
class CentroidAlgorithm
Intermediate base class for algorithms that compute a centroid.
class CentroidControl
class GaussianCentroidControl
C++ control object for Gaussian centroid.
class NaiveCentroidControl
C++ control object for naive centroid.
class SdssCentroidControl
C++ control object for SDSS centroid.
class ClassificationControl
Control/factory for the algorithm that does star/galaxy classification.
class CoaddPsf
CoaddPsf is the Psf derived to be used for non-PSF-matched Coadd images.
class CorrectFluxesControl
A control object for a pluggable algorithm that scales fluxes to a common system.
class DoubleGaussianPsf
Represent a Psf as a circularly symmetrical double Gaussian.
class ExposurePatch
class FluxAlgorithm
Intermediate base class for algorithms that compute a flux.
class FluxControl
class ApertureFluxControl
C++ control object for aperture flux.
class EllipticalApertureFluxControl
C++ control object for elliptical aperture fluxes.
class PeakLikelihoodFluxControl
C++ control object for peak likelihood flux.
class NaiveFluxControl
C++ control object for naive flux.
class PsfFluxControl
C++ control object for PSF flux.
class SincFluxControl
C++ control object for sinc aperture flux.
class GaussianFluxControl
C++ control object for Gaussian flux.
class PsfImagePca
class ImagePsf
An intermediate base class for Psfs that use an image representation.
class Defect
Encapsulate information about a bad portion of a detector.
class KernelPsf
A Psf defined by a Kernel.
struct KernelPsfPersistenceHelper
A read-only singleton struct containing the schema and key used in persistence for KernelPsf.
class KernelPsfFactory
A PersistableFactory for KernelPsf and its subclasses.
class MeasureSources
class MeasureSourcesBuilder
class PcaPsf
Represent a PSF as a linear combination of PCA (== Karhunen-Loeve) basis functions.
class PixelFlagControl
Control/factory for the algorithm that sets source bits from pixel mask bits.
class PsfAttributes
class PsfCandidate
Class stored in SpatialCells for spatial Psf fitting.
class RecordCentroidControl
Control/factory for an algorithm that records the centroid used in the measurement.
class ScaledFlux
An abstract base class for flux algorithms that need to be scaled to a common system.
class SdssShapeControl
C++ control object for SDSS shape.
class ShapeAlgorithm
Intermediate base class for algorithms that compute a shape.
class ShapeControl
class Shapelet
class ShapeletInterpolation
class LocalShapeletKernel
class ShapeletKernel
class ShapeletPsfCandidate
class SingleGaussianPsf
Represent a PSF as a circularly symmetrical double Gaussian.
class SizeMagnitudeStarSelector
class SkyCoordControl
Control/factory for an algorithm that sets ra/dec from x/y.
class WarpedPsf
A Psf class that maps an arbitrary Psf through a coordinate transformation.
class FootprintFlux
class FootprintWeightFlux
struct getSum2
class EllipticalApertureFlux
A class that knows how to calculate fluxes as a simple sum over a Footprint.
class SincFlux
A class that knows how to calculate fluxes using the SINC photometry algorithm /.
class ShapeletImpl
class LoadCandidatesVisitor
class ShapeletInterpolationImpl
class ShapeletKernelFunction
class ShapeletSpatialFunction
class SizeMagnitudeStarSelectorImpl
class evalChi2Visitor
A class to pass around to all our PsfCandidates to evaluate the PSF fit's X^2.
class MinimizeChi2
Typedefs
typedef std::map< std::string,
boost::shared_ptr< Algorithm
const > > AlgorithmMap
typedef std::vector
< Defect::Ptr >
::const_iterator DefectCIter
Functions
template<typename MaskedImageT >
std::vector< boost::shared_ptr
< lsst::afw::detection::Footprint > > findCosmicRays (MaskedImageT &mimage,detection::Psf const &psf,double const bkgd,lsst::pex::policy::Policy const &policy,bool const keep)
Find cosmic rays in an Image, and mask and remove them.
template<typename ExposureT >
boost::shared_ptr
< ExposurePatch< ExposureT > > makeExposurePatch (boost::shared_ptr< ExposureT const > exp, boost::shared_ptr< afw::detection::Footprint const > foot, afw::geom::Point2D const &center)
Factory function for ExposurePatch.
template<typename ExposureT >
boost::shared_ptr
< ExposurePatch< ExposureT > > makeExposurePatch (boost::shared_ptr< ExposureT const > exp, afw::detection::Footprint const &standardFoot, afw::geom::Point2D const &standardCenter, afw::image::Wcs const &standardWcs)
template<typename MaskedImageT >
void interpolateOverDefects (MaskedImageT &mimage,lsst::afw::detection::Psf const &,std::vector< Defect::Ptr > &_badList,double fallbackValue)
Process a set of known bad pixels in an image.
template<typename PixelT >
boost::shared_ptr
< PsfCandidate< PixelT > > makePsfCandidate (boost::shared_ptr< afw::table::SourceRecord > const &source, boost::shared_ptr< afw::image::Exposure< PixelT > > image)
Eigen::Matrix2d getJacobian (const lsst::afw::image::Wcs &wcs, const lsst::afw::geom::PointD &pos)
a helper function to deal with the fact that Wcs doesn't directly return a Jacobian.
template<typename PixelT >
std::pair
< lsst::afw::math::LinearCombinationKernel::Ptr,
std::vector< double > > createKernelFromPsfCandidates (lsst::afw::math::SpatialCellSet const &psfCells, lsst::afw::geom::Extent2I const &dims, lsst::afw::geom::Point2I const &xy0, int const nEigenComponents, int const spatialOrder, int const ksize, int const nStarPerCell=-1, bool const constantWeight=true, int const border=3)
template<typename PixelT >
int countPsfCandidates (lsst::afw::math::SpatialCellSet const &psfCells, int const nStarPerCell=-1)
template<typename PixelT >
std::pair< bool, double > fitSpatialKernelFromPsfCandidates (lsst::afw::math::Kernel *kernel, lsst::afw::math::SpatialCellSet const &psfCells, int const nStarPerCell=-1, double const tolerance=1e-5, double const lambda=0.0)
template<typename PixelT >
std::pair< bool, double > fitSpatialKernelFromPsfCandidates (lsst::afw::math::Kernel *kernel, lsst::afw::math::SpatialCellSet const &psfCells, bool const doNonLinearFit, int const nStarPerCell=-1, double const tolerance=1e-5, double const lambda=0.0)
template<typename ImageT >
double subtractPsf (lsst::afw::detection::Psf const &psf, ImageT *data, double x, double y, double psfFlux=std::numeric_limits< double >::quiet_NaN())
template<typename Image >
std::pair< std::vector< double >
, lsst::afw::math::KernelList > fitKernelParamsToImage (lsst::afw::math::LinearCombinationKernel const &kernel, Image const &image, lsst::afw::geom::Point2D const &pos)
template<typename Image >
std::pair
< lsst::afw::math::Kernel::Ptr,
std::pair< double, double > > fitKernelToImage (lsst::afw::math::LinearCombinationKernel const &kernel, Image const &image, lsst::afw::geom::Point2D const &pos)
afw::geom::Box2I getOverallBBox (std::vector< boost::shared_ptr< afw::image::Image< double > >> const &imgVector)
void addToImage (boost::shared_ptr< afw::image::Image< double > > image, std::vector< boost::shared_ptr< afw::image::Image< double > >> const &imgVector, std::vector< double > const &weightVector)
LSST_MEAS_ALGORITHM_PRIVATE_IMPLEMENTATION (ApertureFlux)
LSST_MEAS_ALGORITHM_PRIVATE_IMPLEMENTATION (EllipticalApertureFlux)
template std::pair< double,
double > photometry::calculateSincApertureFlux< lsst::afw::image::MaskedImage< float > > (lsst::afw::image::MaskedImage< float > const &, lsst::afw::geom::ellipses::Ellipse const &, double const)
template std::pair< double,
double > photometry::calculateSincApertureFlux< lsst::afw::image::MaskedImage< double > > (lsst::afw::image::MaskedImage< double > const &, lsst::afw::geom::ellipses::Ellipse const &, double const)
LSST_MEAS_ALGORITHM_PRIVATE_IMPLEMENTATION (SincFlux)
template bool detail::getAdaptiveMoments< lsst::afw::image::Image< int > > (lsst::afw::image::Image< int > const &, double, double, double, double, detail::SdssShapeImpl *, int, float, float)
template std::pair< double,
double > detail::getFixedMomentsFlux< lsst::afw::image::Image< int > > (lsst::afw::image::Image< int > const &, double, double, double, detail::SdssShapeImpl const &)
template bool detail::getAdaptiveMoments< lsst::afw::image::MaskedImage< int > > (lsst::afw::image::MaskedImage< int > const &, double, double, double, double, detail::SdssShapeImpl *, int, float, float)
template std::pair< double,
double > detail::getFixedMomentsFlux< lsst::afw::image::MaskedImage< int > > (lsst::afw::image::MaskedImage< int > const &, double, double, double, detail::SdssShapeImpl const &)
template bool detail::getAdaptiveMoments< lsst::afw::image::Image< float > > (lsst::afw::image::Image< float > const &, double, double, double, double, detail::SdssShapeImpl *, int, float, float)
template std::pair< double,
double > detail::getFixedMomentsFlux< lsst::afw::image::Image< float > > (lsst::afw::image::Image< float > const &, double, double, double, detail::SdssShapeImpl const &)
template bool detail::getAdaptiveMoments< lsst::afw::image::MaskedImage< float > > (lsst::afw::image::MaskedImage< float > const &, double, double, double, double, detail::SdssShapeImpl *, int, float, float)
template std::pair< double,
double > detail::getFixedMomentsFlux< lsst::afw::image::MaskedImage< float > > (lsst::afw::image::MaskedImage< float > const &, double, double, double, detail::SdssShapeImpl const &)
template bool detail::getAdaptiveMoments< lsst::afw::image::Image< double > > (lsst::afw::image::Image< double > const &, double, double, double, double, detail::SdssShapeImpl *, int, float, float)
template std::pair< double,
double > detail::getFixedMomentsFlux< lsst::afw::image::Image< double > > (lsst::afw::image::Image< double > const &, double, double, double, detail::SdssShapeImpl const &)
template bool detail::getAdaptiveMoments< lsst::afw::image::MaskedImage< double > > (lsst::afw::image::MaskedImage< double > const &, double, double, double, double, detail::SdssShapeImpl *, int, float, float)
template std::pair< double,
double > detail::getFixedMomentsFlux< lsst::afw::image::MaskedImage< double > > (lsst::afw::image::MaskedImage< double > const &, double, double, double, detail::SdssShapeImpl const &)
template<class ShapeletPtr >
int getImageSize (ShapeletPtr shapelet, int size)
std::vector
< lsst::afw::math::Kernel::SpatialFunctionPtr > buildSetOfSpatialFunctions (ShapeletInterpolation::ConstPtr interp)
void setSpatialParameters (afwMath::Kernel *kernel, std::vector< double > const &coeffs)
void setSpatialParameters (afwMath::Kernel *kernel, Eigen::VectorXd const &vec)
template<typename MaskedImageT >
double subtractPsf (afwDetection::Psf const &psf, MaskedImageT *data, double x, double y, double psfFlux)
Detailed Description
Fit spatial kernel using approximate fluxes for candidates, and solving a linear system of equations
Typedef Documentation
typedef std::map<std::string,boost::shared_ptr< Algorithm const > > lsst::meas::algorithms::AlgorithmMap
typedef std::vector<Defect::Ptr>::const_iterator lsst::meas::algorithms::DefectCIter
Function Documentation
void lsst::meas::algorithms::addToImage (boost::shared_ptr< afw::image::Image< double > > image, std::vector< boost::shared_ptr< afw::image::Image< double > >> const & imgVector, std::vector< double > const & weightVector)
References lsst::afw::geom::Box2I::clip(), lsst::afw::image::Image< PixelT >::getBBox(), lsst::afw::image::PARENT, PTR, lsst::afw::image::Image< PixelT >::scaledPlus(), and sum.
Referenced by lsst::meas::algorithms::CoaddPsf::doComputeKernelImage().
std::vector<lsst::afw::math::Kernel::SpatialFunctionPtr> lsst::meas::algorithms::buildSetOfSpatialFunctions (ShapeletInterpolation::ConstPtr interp)
template<typename PixelT > int lsst::meas::algorithms::countPsfCandidates (afwMath::SpatialCellSet const & psfCells, int const nStarPerCell)
Count the number of candidates in use
References lsst::afw::math::SpatialCellSet::visitCandidates().
template<typename PixelT > std::pair< afwMath::LinearCombinationKernel::Ptr, std::vector< double > > lsst::meas::algorithms::createKernelFromPsfCandidates (afwMath::SpatialCellSet const & psfCells, lsst::afw::geom::Extent2I const & dims, lsst::afw::geom::Point2I const & xy0, int const nEigenComponents, int const spatialOrder, int const ksize, int const nStarPerCell, bool const constantWeight, int const border)
Return a Kernel::Ptr and a list of eigenvalues resulting from analysing the provided SpatialCellSet
The Kernel is a LinearCombinationKernel of the first nEigenComponents eigenImages
N.b. This is templated over the Pixel type of the science image
Parameters
psfCells A SpatialCellSet containing PsfCandidates
dims Dimensions of image
xy0 Origin of image
nEigenComponents number of eigen components to keep; <= 0 => infty
spatialOrder Order of spatial variation (cf. afw::math::PolynomialFunction2)
ksize Size of generated Kernel images
nStarPerCell max no. of stars per cell; <= 0 => infty
constantWeight should each star have equal weight in the fit?
border Border size for background subtraction
References lsst::meas::algorithms::PsfImagePca< ImageT >::analyze(), lsst::afw::image::ImagePca< ImageT >::getEigenImages(), lsst::afw::image::ImagePca< ImageT >::getEigenValues(), lsst::afw::image::Mask< MaskPixelT >::getPlaneBitMask(), k, lsst::afw::math::SpatialCellMaskedImageCandidate< PixelT >::setHeight(), lsst::afw::math::SpatialCellMaskedImageCandidate< PixelT >::setWidth(), sum, lsst::afw::image::ImagePca< ImageT >::updateBadPixels(), and lsst::afw::math::SpatialCellSet::visitCandidates().
template bool lsst::meas::algorithms::detail::getAdaptiveMoments< lsst::afw::image::Image< double > > (lsst::afw::image::Image< double > const & , double , double , double , double , detail::SdssShapeImpl * , int , float , float)
template bool lsst::meas::algorithms::detail::getAdaptiveMoments< lsst::afw::image::Image< float > > (lsst::afw::image::Image< float > const & , double , double , double , double , detail::SdssShapeImpl * , int , float , float)
template bool lsst::meas::algorithms::detail::getAdaptiveMoments< lsst::afw::image::Image< int > > (lsst::afw::image::Image< int > const & , double , double , double , double , detail::SdssShapeImpl * , int , float , float)
template bool lsst::meas::algorithms::detail::getAdaptiveMoments< lsst::afw::image::MaskedImage< double > > (lsst::afw::image::MaskedImage< double > const & , double , double , double , double , detail::SdssShapeImpl * , int , float , float)
template bool lsst::meas::algorithms::detail::getAdaptiveMoments< lsst::afw::image::MaskedImage< float > > (lsst::afw::image::MaskedImage< float > const & , double , double , double , double , detail::SdssShapeImpl * , int , float , float)
template bool lsst::meas::algorithms::detail::getAdaptiveMoments< lsst::afw::image::MaskedImage< int > > (lsst::afw::image::MaskedImage< int > const & , double , double , double , double , detail::SdssShapeImpl * , int , float , float)
template std::pair<double, double> lsst::meas::algorithms::detail::getFixedMomentsFlux< lsst::afw::image::Image< double > > (lsst::afw::image::Image< double > const & , double , double , double , detail::SdssShapeImpl const &)
template std::pair<double, double> lsst::meas::algorithms::detail::getFixedMomentsFlux< lsst::afw::image::Image< float > > (lsst::afw::image::Image< float > const & , double , double , double , detail::SdssShapeImpl const &)
template std::pair<double, double> lsst::meas::algorithms::detail::getFixedMomentsFlux< lsst::afw::image::Image< int > > (lsst::afw::image::Image< int > const & , double , double , double , detail::SdssShapeImpl const &)
template std::pair<double, double> lsst::meas::algorithms::detail::getFixedMomentsFlux< lsst::afw::image::MaskedImage< double > > (lsst::afw::image::MaskedImage< double > const & , double , double , double , detail::SdssShapeImpl const &)
template std::pair<double, double> lsst::meas::algorithms::detail::getFixedMomentsFlux< lsst::afw::image::MaskedImage< float > > (lsst::afw::image::MaskedImage< float > const & , double , double , double , detail::SdssShapeImpl const &)
template std::pair<double, double> lsst::meas::algorithms::detail::getFixedMomentsFlux< lsst::afw::image::MaskedImage< int > > (lsst::afw::image::MaskedImage< int > const & , double , double , double , detail::SdssShapeImpl const &)
template<typename MaskedImageT > std::vector< detection::Footprint::Ptr > lsst::meas::algorithms::findCosmicRays (MaskedImageT & mimage, detection::Psf const & psf, double const bkgd, lsst::pex::policy::Policy const & policy, bool const keep)
Find cosmic rays in an Image, and mask and remove them.
Returns
vector of CR's Footprints
In this loop, we look for strings of CRpixels on the same row and adjoining columns; each of these becomes a Span with a unique ID.
In this loop, we look for strings of CRpixels on the same row and adjoining columns; each of these becomes a Span with a unique ID.
Parameters
mimage Image to search
psf the Image's PSF
bkgd unsubtracted background of frame, DN
policy Policy directing the behavior
keep if true, don't remove the CRs
References col, footprintAndMask(), lsst::pex::policy::Policy::getDouble(), lsst::pex::policy::Policy::getInt(), lsst::afw::detection::Psf::getLocalKernel(), lsst::afw::detection::Footprint::getNpix(), lsst::afw::detection::Footprint::getSpans(), id, LSST_EXCEPT, row, and setMaskFromFootprintList().
template<typename Image > std::pair< std::vector< double >, afwMath::KernelList > lsst::meas::algorithms::fitKernelParamsToImage (afwMath::LinearCombinationKernel const & kernel, Image const & image, afwGeom::Point2D const & pos)
Fit a LinearCombinationKernel to an Image, allowing the coefficients of the components to vary
Returns
std::pair(coefficients, std::pair(kernels, center amplitude))
Parameters
kernel the Kernel to fit
image the image to be fit
pos the position of the object
References b, lsst::afw::math::LinearCombinationKernel::getKernelList(), and LSST_EXCEPT.
Referenced by fitKernelToImage().
template<typename Image > std::pair< afwMath::Kernel::Ptr, std::pair< double, double > > lsst::meas::algorithms::fitKernelToImage (afwMath::LinearCombinationKernel const & kernel, Image const & image, afwGeom::Point2D const & pos)
Fit a LinearCombinationKernel to an Image, allowing the coefficients of the components to vary
Returns
std::pair(best-fit kernel, std::pair(amp, chi^2))
Parameters
kernel the Kernel to fit
image the image to be fit
pos the position of the object
References fitKernelParamsToImage(), and k.
template<typename PixelT > std::pair< bool, double > lsst::meas::algorithms::fitSpatialKernelFromPsfCandidates (afwMath::Kernel * kernel, afwMath::SpatialCellSet const & psfCells, int const nStarPerCell, double const tolerance, double const lambda)
Fit spatial kernel using full-nonlinear optimization to estimate candidate amplitudes
Parameters
kernel the Kernel to fit
psfCells A SpatialCellSet containing PsfCandidates
nStarPerCell max no. of stars per cell; <= 0 => infty
tolerance Tolerance; how close chi^2 should be to true minimum
lambda floor for variance is lambda*data
References lsst::afw::math::Kernel::getNKernelParameters(), lsst::afw::math::Kernel::getNSpatialParameters(), lsst::meas::algorithms::MinimizeChi2< PixelT >::setErrorDef(), setSpatialParameters(), and lsst::afw::math::SpatialCellSet::visitAllCandidates().
template<typename PixelT > std::pair< bool, double > lsst::meas::algorithms::fitSpatialKernelFromPsfCandidates (lsst::afw::math::Kernel * kernel, lsst::afw::math::SpatialCellSet const & psfCells, bool const doNonLinearFit, int const nStarPerCell = -1, double const tolerance = 1e-5, double const lambda = 0.0)
Parameters
kernel the Kernel to fit
psfCells A SpatialCellSet containing PsfCandidates
doNonLinearFit Use the full-up nonlinear fitter
nStarPerCell max no. of stars per cell; <= 0 => infty
tolerance Tolerance; how close chi^2 should be to true minimum
lambda floor for variance is lambda*data
References b, copy(), lsst::afw::math::Kernel::getNKernelParameters(), lsst::afw::math::Kernel::getNSpatialParameters(), lsst::meas::algorithms::evalChi2Visitor< PixelT >::getValue(), LSST_EXCEPT, setSpatialParameters(), lsst::afw::math::SpatialCellSet::visitAllCandidates(), and lsst::afw::math::SpatialCellSet::visitCandidates().
template<class ShapeletPtr > int lsst::meas::algorithms::getImageSize (ShapeletPtr shapelet, int size) inline
Eigen::Matrix2d lsst::meas::algorithms::getJacobian (const lsst::afw::image::Wcs & wcs, const lsst::afw::geom::PointD & pos)
a helper function to deal with the fact that Wcs doesn't directly return a Jacobian.
This function calculates the local Jacobian of the distortion pattern at a given location.
The input position is given in chip coordinates, since that's what we generally have when we want to calculate the local distortion.
The return matrix is:
J = (du/dx du/dy) (dv/dx dv/dy)
where (u,v) are the sky coordinates, and (x,y) are the chip coordinates.
Parameters
wcs The wcs defining the distortion function
pos The position in chip coordinates at which to find the Jacobian
References lsst::afw::geom::degrees, lsst::afw::geom::AffineTransform::getMatrix(), and lsst::afw::image::Wcs::linearizePixelToSky().
afw::geom::Box2I lsst::meas::algorithms::getOverallBBox (std::vector< boost::shared_ptr< afw::image::Image< double > >> const & imgVector)
References lsst::afw::geom::Box2I::include(), lsst::afw::image::PARENT, and PTR.
Referenced by lsst::meas::algorithms::CoaddPsf::doComputeKernelImage().
template<typename MaskedImageT > void lsst::meas::algorithms::interpolateOverDefects (MaskedImageT & mimage, lsst::afw::detection::Psf const & psf, std::vector< Defect::Ptr > & _badList, double fallbackValue = std::numeric_limits<typename MaskedImageT::Image::Pixel>::max())
Process a set of known bad pixels in an image.
Parameters
mimage Image to patch
psf the Image's PSF
_badList List of Defects to patch
fallbackValue Value to fallback to if all else fails
References lsst::afw::geom::Box2I::getMax(), lsst::afw::geom::Box2I::getMin(), and lsst::afw::geom::Box2I::shift().
lsst::meas::algorithms::LSST_MEAS_ALGORITHM_PRIVATE_IMPLEMENTATION (EllipticalApertureFlux)
lsst::meas::algorithms::LSST_MEAS_ALGORITHM_PRIVATE_IMPLEMENTATION (ApertureFlux)
lsst::meas::algorithms::LSST_MEAS_ALGORITHM_PRIVATE_IMPLEMENTATION (SincFlux)
template<typename ExposureT > boost::shared_ptr< ExposurePatch<ExposureT> > lsst::meas::algorithms::makeExposurePatch (boost::shared_ptr< ExposureT const > exp, boost::shared_ptr< afw::detection::Footprint const > foot, afw::geom::Point2D const & center)
Factory function for ExposurePatch.
template<typename ExposureT > boost::shared_ptr< ExposurePatch<ExposureT> > lsst::meas::algorithms::makeExposurePatch (boost::shared_ptr< ExposureT const > exp, afw::detection::Footprint const & standardFoot, afw::geom::Point2D const & standardCenter, afw::image::Wcs const & standardWcs)
References PTR.
template<typename PixelT > boost::shared_ptr<PsfCandidate<PixelT> > lsst::meas::algorithms::makePsfCandidate (boost::shared_ptr< afw::table::SourceRecord > const & source, boost::shared_ptr< afw::image::Exposure< PixelT > > image)
Return a PsfCandidate of the right sort
Cf. std::make_pair
Parameters
source The detected Source
image The image wherein lies the object
Referenced by lsst.meas.algorithms.psfSelectionFromMatchList::selectPsfSources().
template std::pair<double, double> lsst::meas::algorithms::photometry::calculateSincApertureFlux< lsst::afw::image::MaskedImage< double > > (lsst::afw::image::MaskedImage< double > const & , lsst::afw::geom::ellipses::Ellipse const & , double const)
template std::pair<double, double> lsst::meas::algorithms::photometry::calculateSincApertureFlux< lsst::afw::image::MaskedImage< float > > (lsst::afw::image::MaskedImage< float > const & , lsst::afw::geom::ellipses::Ellipse const & , double const)
void lsst::meas::algorithms::setSpatialParameters (afwMath::Kernel * kernel, std::vector< double > const & coeffs)
Fit a Kernel's spatial variability from a set of stars
References copy(), lsst::afw::math::Kernel::getNKernelParameters(), lsst::afw::math::Kernel::getNSpatialParameters(), and lsst::afw::math::Kernel::setSpatialParameters().
Referenced by fitSpatialKernelFromPsfCandidates(), and lsst::meas::algorithms::MinimizeChi2< PixelT >::operator()().
void lsst::meas::algorithms::setSpatialParameters (afwMath::Kernel * kernel, Eigen::VectorXd const & vec)
Fit a Kernel's spatial variability from a set of stars
References lsst::afw::math::Kernel::getNKernelParameters(), lsst::afw::math::Kernel::getNSpatialParameters(), and lsst::afw::math::Kernel::setSpatialParameters().
template<typename ImageT > double lsst::meas::algorithms::subtractPsf (lsst::afw::detection::Psf const & psf, ImageT * data, double x, double y, double psfFlux = std::numeric_limits< double >::quiet_NaN())
template<typename MaskedImageT > double lsst::meas::algorithms::subtractPsf (afwDetection::Psf const & psf, MaskedImageT * data, double x, double y, double psfFlux)
Subtract a PSF from an image at a given position
Parameters
psf the PSF to subtract
data Image to subtract PSF from
x column position
y row position
psfFlux object's PSF flux (if not NaN)
References lsst::afw::detection::Psf::computeImage(), lsst::afw::math::Statistics::getValue(), lsst::utils::isnan(), and LSST_EXCEPT_ADD.