#--------- This file is automatically generated by LSST's sconsUtils ---------#
__version__ = '7.1.2.0+2'
__repo_version__ = '7.1.2.0'
__repo_version__ = '7.1.2.0'
__fingerprint__ = '0x0'
__version_info__ = (7, 1, 2, 0)
__rebuild_version__ = 2
__dependency_versions__ = {
    'boost': '1.51.0+3',
    'python': 'unknown',
    'boost_regex': '1.51.0+3',
    'base': '7.1.1.0+1',
    'pex_exceptions': '6.2.0.0+3',
    'utils': '7.1.2.0+1',
    'daf_base': '7.1.1.0+1',
    'boost_system': '1.51.0+3',
    'boost_filesystem': '1.51.0+3',
    'pex_logging': '6.2.1.0+4',
    'pex_policy': '6.2.0.0+4',
    'mysqlclient': '5.1.65+2',
    'boost_serialization': '1.51.0+3',
    'daf_persistence': '7.1.1.0+2',
    'pex_config': '7.1.2.0+1',
    'eigen': '3.1.1+1',
    'fftw': '3.3.2+1',
    'numpy': '1.6.2+1',
    'ndarray': '7.1.1.0+1',
    'xpa': '2.1.14+1',
    'minuit2': '5.22.00+1',
    'gsl': '1.15+1',
    'cfitsio': '3310+1',
    'wcslib': '4.14+2',
    'cuda_toolkit': None,
    'afw': '7.1.2.0+1',
    'boost_math': '1.51.0+3',
    'pipe_base': '7.2.0.0+1',
    'boost_test': '1.51.0+3',
    'swig': 'unknown',
}
__all__ = ('__version__', '__repo_version__', '__repo_version__', '__fingerprint__', '__version_info__', '__rebuild_version__', '__dependency_versions__')
